# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import triton
import triton.language as tl
from triton.language.extra.mlu.libdevice import philox as _philox

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)
from flag_gems.utils.shape_utils import volume

from ..utils import TOTAL_CORE_NUM
from .randn import pair_uniform_to_normal

logger = logging.getLogger(__name__)
UNROLL = 4


@triton.heuristics(runtime.get_heuristic_config("randn"))
@triton.jit(do_not_specialize=["philox_seed", "philox_offset", "N", "mean", "std"])
def log_normal_kernel(
    out_ptr,
    N,
    mean,
    std,
    philox_seed,
    philox_offset,
    BLOCK: tl.constexpr,
):
    UNROLL: tl.constexpr = 4
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)

    pid = tl.program_id(0)
    num_jobs = tl.num_programs(0)
    i4_start = pid * BLOCK
    block_start = pid * UNROLL * BLOCK
    step = num_jobs * BLOCK * UNROLL

    res = tl.empty([UNROLL, BLOCK], dtype=tl.float32)
    for block_offset in range(block_start, N, step):
        sl = (philox_seed & 0xFFFFFFFF).to(tl.uint32)
        sh = ((philox_seed >> 32) & 0xFFFFFFFF).to(tl.uint32)
        c0 = (philox_offset & 0xFFFFFFFF).to(tl.uint32)
        c1 = ((philox_offset >> 32) & 0xFFFFFFFF).to(tl.uint32)
        r = _philox(BLOCK, sl, sh, c0 + i4_start, c1, 0, 0, 10)
        r = uint_to_uniform_float(r)

        res[0, :], res[1, :] = pair_uniform_to_normal(r[0, :], r[1, :])
        res[2, :], res[3, :] = pair_uniform_to_normal(r[2, :], r[3, :])
        values = tl.exp(
            tl.reshape(res, [BLOCK * UNROLL], can_reorder=True) * std + mean
        )

        off = block_offset + tl.arange(0, BLOCK * UNROLL)
        tl.store(out_ptr + off, values, mask=off < N)
        i4_start += num_jobs * BLOCK


def log_normal_(self, mean=1.0, std=2.0, *, generator=None):
    logger.debug("GEMS_CAMBRICON LOG_NORMAL_")
    N = volume(self.shape)
    if N == 0:
        return self

    grid_fn = lambda meta: (
        min(triton.cdiv(N, meta["BLOCK"] * UNROLL), TOTAL_CORE_NUM),
    )
    increment = triton.cdiv(N, UNROLL)
    philox_seed, philox_offset = philox_backend_seed_offset(
        increment, generator=generator
    )
    with torch_device_fn.device(self.device):
        log_normal_kernel[grid_fn](
            self,
            N,
            mean,
            std,
            philox_seed,
            philox_offset,
            num_warps=1,
            num_stages=3,
        )
    return self
