# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _nll_loss2d_none_kernel(
    self_input_ptr,
    target_ptr,
    weight_ptr,
    out_ptr,
    N,
    C,
    H,
    W,
    total,
    HAS_WEIGHT: tl.constexpr,
    IGNORE_INDEX: tl.constexpr,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < total

    W_val = W
    HW = H * W_val
    n = offsets // HW
    hw_remain = offsets % HW
    h = hw_remain // W_val
    w = hw_remain % W_val

    target_index = n * HW + h * W_val + w
    t = tl.load(target_ptr + target_index, mask=mask, other=IGNORE_INDEX)

    valid = (t != IGNORE_INDEX) & mask
    t_clamped = tl.where(valid, t, 0)
    self_index = n * C * HW + t_clamped * HW + h * W_val + w
    s = tl.load(self_input_ptr + self_index, mask=mask, other=0.0).to(tl.float32)

    if HAS_WEIGHT:
        wgt = tl.load(weight_ptr + t_clamped, mask=mask, other=0.0).to(tl.float32)
    else:
        wgt = tl.full((BLOCK,), 1.0, dtype=tl.float32)

    loss = -s * wgt
    loss = tl.where(valid, loss, 0.0)

    tl.store(out_ptr + offsets, loss, mask=mask)


@triton.jit
def _nll_loss2d_reduce_kernel(
    self_input_ptr,
    target_ptr,
    weight_ptr,
    partial_loss_ptr,
    partial_weight_ptr,
    N,
    C,
    H,
    W,
    total,
    HAS_WEIGHT: tl.constexpr,
    REDUCTION: tl.constexpr,
    IGNORE_INDEX: tl.constexpr,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < total

    W_val = W
    HW = H * W_val
    n = offsets // HW
    hw_remain = offsets % HW
    h = hw_remain // W_val
    w = hw_remain % W_val

    target_index = n * HW + h * W_val + w
    t = tl.load(target_ptr + target_index, mask=mask, other=IGNORE_INDEX)

    valid = (t != IGNORE_INDEX) & mask
    t_clamped = tl.where(valid, t, 0)
    self_index = n * C * HW + t_clamped * HW + h * W_val + w
    s = tl.load(self_input_ptr + self_index, mask=mask, other=0.0).to(tl.float32)

    if HAS_WEIGHT:
        wgt = tl.load(weight_ptr + t_clamped, mask=mask, other=0.0).to(tl.float32)
    else:
        wgt = tl.full((BLOCK,), 1.0, dtype=tl.float32)

    loss = -s * wgt
    loss = tl.where(valid, loss, 0.0)

    # Stage 1: write this block's partial loss (and, for mean, partial weight)
    # to a scratch buffer. No atomics and no pre-zeroing required, so the whole
    # reduction is two plain kernel launches with contiguous writes.
    block_loss = tl.sum(loss)
    if REDUCTION == 2:
        tl.store(partial_loss_ptr + pid, block_loss)
    else:
        block_weight = tl.sum(tl.where(valid, wgt, 0.0))
        tl.store(partial_loss_ptr + pid, block_loss)
        tl.store(partial_weight_ptr + pid, block_weight)


@triton.jit
def _nll_loss2d_finalize_kernel(
    partial_loss_ptr,
    partial_weight_ptr,
    out_ptr,
    num_blocks,
    REDUCTION: tl.constexpr,
    OUT_DTYPE: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # Single-program-block finalize: sum the stage-1 partials, divide by the
    # total weight for the mean case, cast, and write the scalar output. Doing
    # the divide/cast in-kernel avoids the chained per-scalar torch ops that
    # otherwise dominate this operator's latency.
    offsets = tl.arange(0, BLOCK)
    mask = offsets < num_blocks
    loss = tl.sum(tl.load(partial_loss_ptr + offsets, mask=mask, other=0.0))
    if REDUCTION == 2:
        result = loss
    else:
        tw = tl.sum(tl.load(partial_weight_ptr + offsets, mask=mask, other=0.0))
        result = loss / tw
    tl.store(out_ptr, result.to(OUT_DTYPE))


@triton.jit
def _nll_loss2d_backward_kernel(
    out_grad_ptr,
    target_ptr,
    weight_ptr,
    grad_input_ptr,
    total_weight_ptr,
    N,
    C,
    H,
    W,
    total,
    HAS_WEIGHT: tl.constexpr,
    REDUCTION: tl.constexpr,
    IGNORE_INDEX: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # Scatter the input gradient. Each valid (n, h, w) position maps to exactly
    # one input element self[n, t, h, w] (only the target class of that position
    # sees a nonzero gradient), so every write lands on a unique address and no
    # atomics are needed. The grad buffer is pre-zeroed by the caller.
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < total

    HW = H * W
    n = offsets // HW
    hw_remain = offsets % HW
    h = hw_remain // W
    w = hw_remain % W

    target_index = n * HW + h * W + w
    t = tl.load(target_ptr + target_index, mask=mask, other=IGNORE_INDEX)

    valid = (t != IGNORE_INDEX) & mask
    t_clamped = tl.where(valid, t, 0)

    if HAS_WEIGHT:
        wgt = tl.load(weight_ptr + t_clamped, mask=mask, other=0.0).to(tl.float32)
    else:
        wgt = tl.full((BLOCK,), 1.0, dtype=tl.float32)

    # out_grad is per-position (reduction=0) or a single scalar (sum/mean).
    if REDUCTION == 0:
        og = tl.load(out_grad_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
    else:
        og = tl.load(out_grad_ptr).to(tl.float32)

    grad_val = -og * wgt
    if REDUCTION == 1:
        # mean divides by the total weight accumulated in forward.
        grad_val = grad_val / tl.load(total_weight_ptr).to(tl.float32)
    grad_val = tl.where(valid, grad_val, 0.0)

    grad_index = n * C * HW + t_clamped * HW + h * W + w
    tl.store(grad_input_ptr + grad_index, grad_val, mask=mask)


_TORCH_TO_TL = {
    torch.float16: tl.float16,
    torch.bfloat16: tl.bfloat16,
    torch.float32: tl.float32,
}


class _NLLLoss2d(torch.autograd.Function):
    """Differentiable nll_loss2d.

    The forward kernels write straight into freshly allocated buffers, so their
    output has no ``grad_fn`` and ``torch.autograd.grad`` would raise
    "does not require grad and does not have a grad_fn". Wrapping the kernels in
    an autograd Function restores the gradient graph; backward scatters the
    gradient onto the target channel of each position in ``self``.
    """

    @staticmethod
    def forward(ctx, self, target, weight, reduction, ignore_index):
        logger.debug("GEMS_CAMBRICON NLL_LOSS2D")

        assert self.ndim == 4, "nll_loss2d: expected 4D input (N, C, H, W)"
        assert self.dtype in (
            torch.float16,
            torch.bfloat16,
            torch.float32,
        ), f"nll_loss2d: unsupported dtype {self.dtype}"

        N, C, H, W = self.shape
        total = N * H * W

        reduction_val = (
            int(reduction.item())
            if isinstance(reduction, torch.Tensor)
            else int(reduction)
        )
        ignore_index_val = (
            int(ignore_index.item())
            if isinstance(ignore_index, torch.Tensor)
            else int(ignore_index)
        )
        has_weight = weight is not None
        out_dtype = self.dtype

        self = self.contiguous()
        target = target.contiguous()
        if weight is not None:
            weight = weight.contiguous()

        # BLOCK=1024 balances occupancy against the number of stage-1 partials
        # the single-block finalize kernel must later reduce.
        BLOCK = 1024
        grid = (triton.cdiv(total, BLOCK),)

        # reduction: 0=none, 1=mean, 2=sum
        if reduction_val == 0:
            out = torch.empty((N, H, W), dtype=torch.float32, device=self.device)
            _nll_loss2d_none_kernel[grid](
                self,
                target,
                weight,
                out,
                N,
                C,
                H,
                W,
                total,
                HAS_WEIGHT=has_weight,
                IGNORE_INDEX=ignore_index_val,
                BLOCK=BLOCK,
                num_warps=8,
                num_stages=2,
            )
            out = out.to(out_dtype)
            total_weight = self.new_zeros(())
        else:
            num_blocks = grid[0]
            # One scratch allocation holding both partial arrays: row 0 = loss,
            # row 1 = weight. Views are free, so this is a single allocation.
            partials = torch.empty(
                (2, num_blocks), dtype=torch.float32, device=self.device
            )
            partial_loss = partials[0]
            partial_weight = partials[1]

            _nll_loss2d_reduce_kernel[grid](
                self,
                target,
                weight,
                partial_loss,
                partial_weight,
                N,
                C,
                H,
                W,
                total,
                HAS_WEIGHT=has_weight,
                REDUCTION=reduction_val,
                IGNORE_INDEX=ignore_index_val,
                BLOCK=BLOCK,
                num_warps=8,
                num_stages=2,
            )

            out = torch.empty((), dtype=out_dtype, device=self.device)
            finalize_block = triton.next_power_of_2(num_blocks)
            _nll_loss2d_finalize_kernel[(1,)](
                partial_loss,
                partial_weight,
                out,
                num_blocks,
                REDUCTION=reduction_val,
                OUT_DTYPE=_TORCH_TO_TL[out_dtype],
                BLOCK=finalize_block,
            )
            # For mean, the backward divides by the sum of weights over valid
            # positions; compute it once here from the stage-1 partials.
            if reduction_val == 1:
                total_weight = partial_weight.sum()
            else:
                total_weight = self.new_zeros(())

        ctx.save_for_backward(self, target, weight, total_weight)
        ctx.reduction = reduction_val
        ctx.ignore_index = ignore_index_val
        ctx.has_weight = has_weight
        return out

    @staticmethod
    def backward(ctx, grad_output):
        self, target, weight, total_weight = ctx.saved_tensors
        reduction = ctx.reduction
        ignore_index = ctx.ignore_index
        has_weight = ctx.has_weight
        N, C, H, W = self.shape
        total = N * H * W

        grad_input = torch.zeros_like(self).contiguous()
        grad_output = grad_output.contiguous()
        target = target.contiguous()
        if weight is not None:
            weight = weight.contiguous()

        BLOCK = 1024
        grid = (triton.cdiv(total, BLOCK),)
        _nll_loss2d_backward_kernel[grid](
            grad_output,
            target,
            weight,
            grad_input,
            total_weight,
            N,
            C,
            H,
            W,
            total,
            HAS_WEIGHT=has_weight,
            REDUCTION=reduction,
            IGNORE_INDEX=ignore_index,
            BLOCK=BLOCK,
            num_warps=8,
            num_stages=2,
        )
        # Only the input needs a gradient: target is integral and weight is not
        # tracked here, so all other outputs are None.
        return grad_input, None, None, None, None


def nll_loss2d(self, target, weight=None, reduction=1, ignore_index=-100):
    return _NLLLoss2d.apply(self, target, weight, reduction, ignore_index)
