# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry, pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit
def special_bessel_j0_func(x):
    return tl_extra_shim.j0(x.to(tl.float32))


@libentry()
@triton.jit
def _bessel_j0_fast_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    # Flat fast path for contiguous inputs: avoids the pointwise_dynamic
    # dispatch overhead (~0.1ms/call on hygon) which dominates small shapes.
    pid = tl.program_id(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offs < n_elements
    x = tl.load(x_ptr + offs, mask=mask, other=0.0)
    # match the pointwise path: compute in f32 for all dtypes (the original
    # pointwise_dynamic kernel also computes f64 inputs in f32)
    r = tl_extra_shim.j0(x.to(tl.float32))
    tl.store(out_ptr + offs, r.to(out_ptr.dtype.element_ty), mask=mask)


def special_bessel_j0(A):
    logger.debug("GEMS_HYGON SPECIAL_BESSEL_J0")
    if A.dtype not in (torch.float32, torch.float64):
        raise TypeError(
            f"special_bessel_j0: unsupported dtype {A.dtype}, only float32 and float64 are supported"
        )
    if A.is_contiguous() and A.numel() > 0:
        out = torch.empty_like(A)
        n = A.numel()
        grid = (triton.cdiv(n, 4096),)
        _bessel_j0_fast_kernel[grid](A, out, n, BLOCK_SIZE=4096, num_warps=8)
        return out
    return special_bessel_j0_func(A)
