# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _copy_kernel(in_ptr, out_ptr, n, BLOCK_SIZE: tl.constexpr):
    """Flat-memory copy with grid-stride loop."""
    pid = tl.program_id(0)
    num_programs = tl.num_programs(0)
    block_start = pid * BLOCK_SIZE
    num_total = num_programs * BLOCK_SIZE
    for off in range(0, tl.cdiv(n, num_total)):
        idx = block_start + off * num_total + tl.arange(0, BLOCK_SIZE)
        mask = idx < n
        tl.store(out_ptr + idx, tl.load(in_ptr + idx, mask=mask), mask=mask)


def diagonal_scatter(input, src, offset=0, dim1=0, dim2=1):
    """Iluvatar-specific diagonal scatter.

    The generic implementation calls ``clone()``, which is overridden by
    FlagGems inside ``use_gems()`` and incurs ~230us of dispatch overhead
    per call.  This version avoids ``clone()`` entirely:

    1. ``empty_like`` allocates the output (fast — not overridden in a
       way that adds per-call overhead).
    2. A grid-stride-loop Triton kernel copies data from the input into
       the output.
    3. The same diagonal-view ``copy_`` used by the simple approach
       writes the source values into the correct diagonal positions.

    The two-CUDA-kernel approach is still dominated by the ``clone``
    equivalent (step 2), but avoids the additional permute-contiguous
    round-trips that the generic implementation performs.
    """
    logger.debug("GEMS_ILUVATAR DIAGONAL_SCATTER")

    ndim = input.ndim
    if dim1 < 0:
        dim1 += ndim
    if dim2 < 0:
        dim2 += ndim

    output = torch.empty_like(input)
    n_elements = input.numel()
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(n_elements, BLOCK_SIZE),)
    _copy_kernel[grid](input, output, n_elements, BLOCK_SIZE)

    diag = torch.diagonal(output, offset, dim1, dim2)
    diag.copy_(src)
    return output
