# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


# ---- Euclidean GCD core (one cheap integer div per iteration) ----


@triton.jit
def _gcd_euclid_i32(x, y):
    """Per-lane Euclid-by-remainder GCD for i16/i32.

    Operates in unsigned to handle INT_MIN safely.  Lanes converge
    independently; the ``tl.sum`` ballot only needs to wait for the
    slowest lane, not rebuild a mask across the full block.

    On Iluvatar hardware a single integer div/rem is much cheaper
    than the multiple ffs (ctz) + where chains of the generic binary
    GCD.
    """
    ax = x.to(tl.uint32)
    ay = y.to(tl.uint32)
    a = ax
    b = ay
    active = b != 0
    while tl.sum(active.to(tl.int32), axis=0) > 0:
        safe_b = tl.where(active, b, 1)
        r = a % safe_b
        a = tl.where(active, b, a)
        b = tl.where(active, r, b)
        active = active & (b != 0)
    return a.to(tl.int32)


# ---- In-place kernels (write result directly over self) ----


@triton.jit
def gcd_inplace_kernel_i16(
    x_ptr,
    y_ptr,
    n_elements,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i32(x.to(tl.int32), y.to(tl.int32))
    tl.store(x_ptr + offsets, res.to(x_ptr.type.element_ty), mask=mask)


@triton.jit
def gcd_inplace_kernel_i32(
    x_ptr,
    y_ptr,
    n_elements,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i32(x, y)
    tl.store(x_ptr + offsets, res.to(x_ptr.type.element_ty), mask=mask)


# ---- Out-of-place kernels (used for the slow promotion path) ----


@triton.jit
def gcd_kernel_i16(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i32(x.to(tl.int32), y.to(tl.int32))
    tl.store(out_ptr + offsets, res.to(out_ptr.type.element_ty), mask=mask)


@triton.jit
def gcd_kernel_i32(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i32(x, y)
    tl.store(out_ptr + offsets, res.to(out_ptr.type.element_ty), mask=mask)


# ---- Host helpers ----


def _kernel_meta(dtype):
    """Return (out_of_place_kernel, inplace_kernel, BLOCK, num_warps)."""
    # num_warps=1: the Euclid kernel is divergence-tolerant and a single
    # warp keeps the integer-div unit fully fed.  More warps oversubscribe
    # it and inflate the ``tl.sum`` ballot across the larger block.
    if dtype in (torch.int8, torch.int16):
        return gcd_kernel_i16, gcd_inplace_kernel_i16, 128, 1
    if dtype == torch.int32:
        return gcd_kernel_i32, gcd_inplace_kernel_i32, 128, 1
    raise TypeError(f"unsupported dtype for gcd_: {dtype}")


def _materialize_inputs(self, other):
    """Materialize and broadcast inputs, matching the generic logic."""
    promoted_dtype = torch.promote_types(self.dtype, other.dtype)
    lhs = self if self.dtype == promoted_dtype else self.to(promoted_dtype)
    rhs = other if other.dtype == promoted_dtype else other.to(promoted_dtype)
    if lhs.shape == rhs.shape:
        return lhs.contiguous(), rhs.contiguous(), promoted_dtype
    lhs, rhs = torch.broadcast_tensors(lhs, rhs)
    return lhs.contiguous(), rhs.contiguous(), promoted_dtype


# ---- Public API ----


def gcd_(self, other):
    """Iluvatar-specific in-place GCD.

    Uses per-lane Euclid-by-remainder GCD with a single-warp launch.
    Each lane converges independently — the ``tl.sum`` ballot only
    waits for the slowest lane rather than performing a full cross-block
    scan per iteration.

    The generic implementation uses binary GCD (Stein's algorithm) with
    multiple ``ctz`` + ``where`` chains per iteration.  On Iluvatar
    hardware a single integer ``%`` is cheaper than the batched
    ``ctz`` + bitwise-ops chain.
    """
    logger.debug("GEMS_ILUVATAR GCD_")

    if self.dtype != other.dtype or self.shape != other.shape:
        # Promotion / broadcast: compute out-of-place, then copy back.
        lhs, rhs, promoted_dtype = _materialize_inputs(self, other)
        result = torch.empty_like(lhs, dtype=promoted_dtype)
        numel = result.numel()
        if numel == 0:
            return self
        kernel, _, block, num_warps = _kernel_meta(promoted_dtype)
        grid = (triton.cdiv(numel, block),)
        kernel[grid](
            lhs.reshape(-1),
            rhs.reshape(-1),
            result.reshape(-1),
            numel,
            BLOCK=block,
            num_warps=num_warps,
        )
        self.copy_(result.view(self.shape))
        return self

    lhs = self.contiguous()
    rhs = other.contiguous()
    numel = lhs.numel()
    if numel == 0:
        return self

    _, kernel, block, num_warps = _kernel_meta(self.dtype)
    grid = (triton.cdiv(numel, block),)
    kernel[grid](
        lhs.reshape(-1),
        rhs.reshape(-1),
        numel,
        BLOCK=block,
        num_warps=num_warps,
    )
    return self
