# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _index_copy_flat_kernel(
    inp_ptr,
    src_ptr,
    index_ptr,
    dim_size,
    L,
    outer,
    BLOCK: tl.constexpr,
):
    # inner == 1 specialization: one output element per (o, i) pair.
    # grid = (cdiv(L, BLOCK), outer).  A small BLOCK (256) wins on this backend
    # by keeping many small blocks in flight for the scattered destination
    # writes.  The index vector is loaded once per block.
    pid0 = tl.program_id(0)
    pid1 = tl.program_id(1)
    i = (pid0 * BLOCK + tl.arange(0, BLOCK)).to(tl.int64)
    mask = i < L
    idx = tl.load(index_ptr + i, mask=mask, other=0).to(tl.int64)
    o = pid1
    src_off = o * L + i
    dst_off = o * dim_size + idx
    v = tl.load(src_ptr + src_off, mask=mask)
    tl.store(inp_ptr + dst_off, v, mask=mask)


@triton.jit
def _index_copy_row_kernel(
    inp_ptr,
    src_ptr,
    index_ptr,
    dim_size,
    L,
    inner,
    BLOCK_T: tl.constexpr,
    R: tl.constexpr,
):
    # inner > 1 specialization: a 2D tile of R index rows x BLOCK_T inner
    # columns per block.  The index is loaded as a length-R vector and the
    # program_id decomposition (t, i, o) avoids integer div/mod in the hot
    # path.  grid = (cdiv(inner, BLOCK_T), cdiv(L, R), outer).
    pid0 = tl.program_id(0)
    pid1 = tl.program_id(1)
    o = tl.program_id(2)
    i = pid1 * R + tl.arange(0, R)
    t = pid0 * BLOCK_T + tl.arange(0, BLOCK_T)
    mask_i = i < L
    idx = tl.load(index_ptr + i, mask=mask_i, other=0).to(tl.int64)
    mask_t = t < inner
    src_off = (o * L + i)[:, None] * inner + t[None, :]
    dst_off = (o * dim_size + idx)[:, None] * inner + t[None, :]
    m = mask_i[:, None] & mask_t[None, :]
    v = tl.load(src_ptr + src_off, mask=m)
    tl.store(inp_ptr + dst_off, v, mask=m)


@triton.jit
def _index_copy_generic_kernel(
    inp_ptr,
    src_ptr,
    index_ptr,
    dim_size,
    L,
    outer,
    inner,
    total,
    BLOCK: tl.constexpr,
):
    # Fallback for shapes whose grid dims exceed the hardware limits.
    pid = tl.program_id(0)
    offs = (pid * BLOCK + tl.arange(0, BLOCK)).to(tl.int64)
    mask = offs < total

    t = offs % inner
    oi = offs // inner
    i = oi % L
    o = oi // L

    idx = tl.load(index_ptr + i, mask=mask, other=0).to(tl.int64)

    src_off = (o * L + i) * inner + t
    dst_off = (o * dim_size + idx) * inner + t

    v = tl.load(src_ptr + src_off, mask=mask)
    tl.store(inp_ptr + dst_off, v, mask=mask)


def index_copy_(inp, dim, index, src):
    logger.debug("GEMS_ILUVATAR INDEX_COPY_")
    if isinstance(dim, torch.Tensor):
        dim = dim.item()
    rank = inp.dim()
    if rank == 0:
        raise IndexError("index_copy_ expects a tensor with at least one dimension")
    if not -rank <= dim < rank:
        raise IndexError(f"index_copy_ dimension {dim} is out of range for rank {rank}")
    if index.dim() != 1:
        raise IndexError("index_copy_ expects index to be one-dimensional")
    if index.dtype not in (torch.int32, torch.int64):
        raise TypeError("index_copy_ expects an int32 or int64 index")
    if inp.dtype != src.dtype:
        raise TypeError("index_copy_ expects input and source to have the same dtype")
    if inp.device != src.device or inp.device != index.device:
        raise ValueError(
            "index_copy_ expects input, source, and index on the same device"
        )
    if inp.dim() != src.dim():
        raise ValueError("index_copy_ expects input and source to have the same rank")
    d = dim % rank
    if index.numel() != src.size(d):
        raise ValueError("index_copy_ expects index length to equal source size at dim")
    if any(inp.size(k) != src.size(k) for k in range(rank) if k != d):
        raise ValueError("index_copy_ input and source sizes must match outside dim")
    if not (inp.is_contiguous() and src.is_contiguous() and index.is_contiguous()):
        raise ValueError(
            "the Iluvatar index_copy_ implementation requires contiguous tensors"
        )

    shape = inp.shape
    size_dim = shape[d]
    L = index.numel()
    inner = 1
    for k in range(d + 1, rank):
        inner *= shape[k]
    outer = 1
    for k in range(0, d):
        outer *= shape[k]
    total = L * inner * outer

    if total > 0:
        if inner == 1 and outer <= 65535:
            BLOCK = min(triton.next_power_of_2(L), 256)
            grid = (triton.cdiv(L, BLOCK), outer)
            _index_copy_flat_kernel[grid](
                inp, src, index, size_dim, L, outer, BLOCK=BLOCK
            )
        elif L <= 65535 and outer <= 65535:
            b = min(triton.next_power_of_2(inner), 1024)
            r = max(1, min(256 // b, 32))
            grid = (triton.cdiv(inner, b), triton.cdiv(L, r), outer)
            if b >= 1024:
                # 1024-wide row tiles run ~21% faster with 8 warps on this device.
                _index_copy_row_kernel[grid](
                    inp, src, index, size_dim, L, inner, BLOCK_T=b, R=r, num_warps=8
                )
            else:
                _index_copy_row_kernel[grid](
                    inp, src, index, size_dim, L, inner, BLOCK_T=b, R=r
                )
        else:
            BLOCK = 1024
            grid = (triton.cdiv(total, BLOCK),)
            _index_copy_generic_kernel[grid](
                inp, src, index, size_dim, L, outer, inner, total, BLOCK=BLOCK
            )

    return inp
