# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)

_CUDA_KEYSET = torch._C.DispatchKeySet(torch._C.DispatchKey.CUDA)


def index_select_backward(grad, self_sizes, dim, index):
    """Iluvatar-specific index_select_backward.

    The generic implementation uses ``tl.atomic_add`` inside a 2-D-grid
    Triton kernel.  On Iluvatar hardware atomic-add is serialised
    across lanes hitting the same output element, and the Triton
    wrapper overhead (~500us per call for a small scatter) dominates
    the actual compute.

    This specialization rebuilds the reduction from primitives that
    dodge the FlagGems aten overrides:

    1. ``grad.new_empty(self_sizes)`` + ``torch._foreach_zero_([out])``
       — the ``_foreach_*`` family is not overridden by Gems, so
       zero-init stays on the native fast path (~0.01ms vs ~0.08ms
       for the overridden ``torch.zeros``).

    2. ``aten.index_add.out.redispatch(CUDA_KEYSET, ...)`` — this
       overload is NOT overridden by Gems (only ``index_add`` default
       and ``index_add_`` are), so it runs PyTorch's hardware-optimised
       atomic scatter directly.

    Same approach as the Hygon backend (PR #231).
    """
    logger.debug("GEMS_ILUVATAR INDEX_SELECT_BACKWARD")

    if index.ndim == 0:
        index = index.unsqueeze(0)

    dim = dim if dim >= 0 else dim + len(self_sizes)

    out = grad.new_empty(self_sizes)
    torch._foreach_zero_([out])

    torch.ops.aten.index_add.out.redispatch(
        _CUDA_KEYSET,
        out,
        dim,
        index,
        grad,
        alpha=1,
        out=out,
    )
    return out
