# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic
from flag_gems.utils.codegen_config_utils import CodeGenConfig, get_codegen_config

logger = logging.getLogger(__name__)

_base_config = get_codegen_config()
_softplus_config = CodeGenConfig(
    max_tile_size=4096,
    max_grid_size=_base_config.max_grid_size,
    max_num_warps_per_cta=_base_config.max_num_warps_per_cta,
    prefer_block_pointer=_base_config.prefer_block_pointer,
    prefer_1d_tile=_base_config.prefer_1d_tile,
)


@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 4096}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 8192}, num_warps=16),
        triton.Config({"BLOCK_SIZE": 16384}, num_warps=16),
    ],
    key=["n_elements"],
)
@triton.jit
def _softplus_backward_contiguous_kernel(
    grad_output_ptr,
    x_ptr,
    output_ptr,
    n_elements,
    beta,
    threshold,
    BLOCK_SIZE: tl.constexpr,
):
    """Autotuned kernel for contiguous softplus backward pass.

    Uses a grid-stride loop to handle tensors of any size with a
    single launch configuration per tensor size.  This provides
    better memory throughput than block-pointer codegen for
    half-precision types because Triton can merge adjacent loads
    into wider vectorized transactions.
    """
    pid = tl.program_id(0)
    num_programs = tl.num_programs(0)

    block_start = pid * BLOCK_SIZE
    num_total_blocks = num_programs * BLOCK_SIZE
    for block_idx in range(0, tl.cdiv(n_elements, num_total_blocks)):
        current_start = block_start + block_idx * num_total_blocks
        offsets = current_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements

        x = tl.load(x_ptr + offsets, mask=mask)
        grad = tl.load(grad_output_ptr + offsets, mask=mask)

        x_fp = x.to(tl.float32)
        z = x_fp * beta
        # d/dx softplus(x, beta) = sigmoid(beta*x) when z <= threshold
        dydx = tl.where(z > threshold, 1.0, tl.sigmoid(z))
        dx = (grad * dydx).to(x.dtype)

        tl.store(output_ptr + offsets, dx, mask=mask)


def _softplus_backward_fast(grad_output, x, beta, threshold):
    """Fast path for contiguous tensors using autotuned kernel."""
    assert x.is_contiguous() and grad_output.is_contiguous()
    output = torch.empty_like(x)
    n_elements = x.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    _softplus_backward_contiguous_kernel[grid](
        grad_output, x, output, n_elements, beta, threshold
    )
    return output


@pointwise_dynamic(
    is_tensor=[True, True, False, False],
    promotion_methods=[(0, 1, "DEFAULT")],
    config=_softplus_config,
)
@triton.jit
def _softplus_backward_generic(grad_output, x, beta, threshold):
    """Generic backward kernel for non-contiguous or float32 tensors."""
    x_fp = x.to(tl.float32)
    z = x_fp * beta
    dydx = tl.where(z > threshold, 1.0, tl.sigmoid(z))
    dx = (grad_output * dydx).to(x.dtype)
    return dx


def softplus_backward(grad_output, self, beta=1.0, threshold=20.0):
    logger.debug("GEMS_ILUVATAR SOFTPLUS_BACKWARD")
    if (
        self.is_contiguous()
        and grad_output.is_contiguous()
        and self.dtype in (torch.float16, torch.bfloat16)
    ):
        grad_input = _softplus_backward_fast(grad_output, self, beta, threshold)
    else:
        grad_input = _softplus_backward_generic(grad_output, self, beta, threshold)
    return grad_input
