# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# Shapes for permute_copy: (original_shape, dims)
PERMUTE_COPY_SHAPES = [
    ((4, 8), (1, 0)),
    ((8, 16), (0, 1)),
    ((16, 32), (1, 0)),
    ((32, 64, 128), (2, 0, 1)),
    ((4, 8, 16), (1, 2, 0)),
    ((8, 16, 32, 64), (3, 1, 0, 2)),
]


@pytest.mark.permute_copy
@pytest.mark.parametrize("shape_dims", PERMUTE_COPY_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_permute_copy(shape_dims, dtype):
    shape, dims = shape_dims

    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.permute_copy(ref_inp, dims)
    res_out = flag_gems.permute_copy(inp, dims)

    utils.gems_assert_close(res_out, ref_out, dtype)
