# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


# Test covers all FLOAT_DTYPES to validate the kernel's correctness for every
# supported input type (the kernel upcasts to float32 internally, then casts
# back). torch.special.bessel_j1 only supports float32/float64 on all backends,
# so we compute the reference in float32 for Half/BFloat16 inputs and cast back.
@pytest.mark.special_bessel_j1
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_special_bessel_j1(shape, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp, True)
    if dtype in (torch.float16, torch.bfloat16):
        ref_out = torch.special.bessel_j1(ref_inp.float()).to(dtype)
    else:
        ref_out = torch.special.bessel_j1(ref_inp)
    res_out = flag_gems.special_bessel_j1(inp)
    utils.gems_assert_close(res_out, ref_out, dtype)
