# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _resize_copy_kernel(src_ptr, dst_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(axis=0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < n_elements
    val = tl.load(src_ptr + offs, mask=mask)
    tl.store(dst_ptr + offs, val, mask=mask)


_BLOCK = 256


def _resize_output_(inp, size, device):
    # resize_output_: in-place resize of `inp` to `size`, preserving data and
    # returning the same aliased tensor object.
    #
    # Same-shape fast path (mirrors torch._resize_output_ semantics: a resize to
    # the current shape is a no-op) - pure metadata, no device work.
    logger.debug("GEMS_THEAD _RESIZE_OUTPUT_")
    if tuple(inp.shape) == tuple(size):
        return inp

    if inp.device == device:
        # Same device: PyTorch resize_ changes shape metadata in place while
        # keeping the data (torch resize semantics); no GPU kernel is needed.
        inp.resize_(size)
        return inp

    # Cross-device path: build the resized buffer on the target device, move
    # the overlapping elements with a Triton copy kernel, then resize in place.
    # Flattened views keep the linear kernel indexing correct for any layout.
    out = torch.empty(size, dtype=inp.dtype, device=device)
    n = min(inp.numel(), out.numel())
    if n > 0:
        grid = (triton.cdiv(n, _BLOCK),)
        inp_flat = inp.reshape(-1)[:n]
        out_flat = out.reshape(-1)[:n]
        _resize_copy_kernel[grid](inp_flat, out_flat, n, BLOCK=_BLOCK)
        inp.resize_(size)
        _resize_copy_kernel[grid](out_flat, inp_flat, n, BLOCK=_BLOCK)
    else:
        inp.resize_(size)
    return inp
