# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _adaptive_max_pool2d_backward_sort_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_input_ptr,
    plane_out,
    plane_in,
    KBITS: tl.constexpr,
    KSUM: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # Deterministic per-plane dedup via packed-key sort (index_add-order sums).
    p = tl.program_id(0)
    offs = tl.arange(0, BLOCK)
    mask = offs < plane_out
    base = p * plane_out
    idx = tl.load(indices_ptr + base + offs, mask=mask, other=0).to(tl.int64)
    g = tl.load(grad_output_ptr + base + offs, mask=mask, other=0.0)
    if KBITS == 16:
        gbits = g.to(tl.uint16, bitcast=True).to(tl.int64)
        key = (idx << 32) | (offs.to(tl.int64) << 16) | gbits
        s = tl.sort(key)
        s_idx = s >> 32
        s_g = (
            (s & 0xFFFF)
            .to(tl.uint16)
            .to(grad_output_ptr.dtype.element_ty, bitcast=True)
        )
    else:
        gbits = g.to(tl.int32, bitcast=True).to(tl.int64) & 0xFFFFFFFF
        key = (idx << 48) | (offs.to(tl.int64) << 32) | gbits
        s = tl.sort(key)
        s_idx = s >> 48
        s_g = (
            (s & 0xFFFFFFFF)
            .to(tl.uint32)
            .to(tl.int32, bitcast=True)
            .to(tl.float32, bitcast=True)
        )
    prev = tl.gather(s_idx, tl.maximum(offs - 1, 0), axis=0)
    gs = (offs == 0) | (s_idx != prev)
    acc = s_g
    for t in tl.static_range(1, KSUM):
        sh_idx = tl.gather(s_idx, tl.minimum(offs + t, BLOCK - 1), axis=0)
        sh_g = tl.gather(s_g, tl.minimum(offs + t, BLOCK - 1), axis=0)
        acc += tl.where((offs + t < BLOCK) & (s_idx == sh_idx), sh_g, 0.0)
    tl.store(grad_input_ptr + p * plane_in + s_idx, acc, mask=gs)


@triton.jit
def _adaptive_max_pool2d_backward_slots4_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_input_ptr,
    H_out: tl.constexpr,
    W_out: tl.constexpr,
    H_in: tl.constexpr,
    W_in: tl.constexpr,
    plane_out: tl.constexpr,
    plane_in: tl.constexpr,
    BLOCK: tl.constexpr,
    ZBLOCK: tl.constexpr,
):
    # Single-launch fused kernel: zero the plane input, then 4 ordered race-free
    # RMW passes grouped by candidate slot (k,j) = (oh-oh0(P), ow-ow0(P)).
    # Requires real adaptive-pool indices (downsampling): each input position is
    # written by at most one output per slot, and slot order == output order.
    # All dims are compile-time so per-lane divisions become multiply-shift.
    # The trailing barrier after the last pass is omitted: kernel end syncs.
    p = tl.program_id(0)
    zbase = p * plane_in
    z = tl.arange(0, ZBLOCK)
    for start in range(0, plane_in, ZBLOCK):
        zmask = (start + z) < plane_in
        tl.store(
            grad_input_ptr + zbase + start + z,
            tl.zeros((ZBLOCK,), dtype=grad_input_ptr.dtype.element_ty),
            mask=zmask,
        )
    tl.debug_barrier()
    offs = tl.arange(0, BLOCK)
    mask = offs < plane_out
    base = p * plane_out
    idx = tl.load(indices_ptr + base + offs, mask=mask, other=0).to(tl.int32)
    g = tl.load(grad_output_ptr + base + offs, mask=mask, other=0.0)
    oh = offs // W_out
    ow = offs % W_out
    hP = idx // W_in
    wP = idx % W_in
    k = oh - (hP * H_out) // H_in
    j = ow - (wP * W_out) // W_in
    for t in tl.static_range(4):
        kp = t // 2
        jp = t % 2
        pmask = mask & (k == kp) & (j == jp)
        v = tl.load(grad_input_ptr + zbase + idx, mask=pmask, other=0.0)
        tl.store(grad_input_ptr + zbase + idx, v + g, mask=pmask)
        if t < 3:
            tl.debug_barrier()


@triton.jit
def _adaptive_max_pool2d_backward_zero_atomic_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_input_ptr,
    plane_out: tl.constexpr,
    plane_in: tl.constexpr,
    BLOCK: tl.constexpr,
    ZBLOCK: tl.constexpr,
):
    # Fused fp32 timed path: zero the plane input, then a single relaxed-atomic
    # scatter pass. fp32 atomics run at ~store speed on this backend, so the
    # barrier-serialized 4-slot RMW is unnecessary for fp32.
    p = tl.program_id(0)
    zbase = p * plane_in
    z = tl.arange(0, ZBLOCK)
    for start in range(0, plane_in, ZBLOCK):
        zmask = (start + z) < plane_in
        tl.store(
            grad_input_ptr + zbase + start + z,
            tl.zeros((ZBLOCK,), dtype=grad_input_ptr.dtype.element_ty),
            mask=zmask,
        )
    tl.debug_barrier()
    offs = tl.arange(0, BLOCK)
    mask = offs < plane_out
    base = p * plane_out
    idx = tl.load(indices_ptr + base + offs, mask=mask, other=0).to(tl.int32)
    g = tl.load(grad_output_ptr + base + offs, mask=mask, other=0.0)
    tl.atomic_add(grad_input_ptr + zbase + idx, g, mask=mask, sem="relaxed")


@triton.jit
def _adaptive_max_pool2d_backward_bulk_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_input_ptr,
    plane_out: tl.constexpr,
    plane_in: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # Flat 1D maskless atomic scatter. grid covers exactly total/BLOCK elements.
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    g = tl.load(grad_output_ptr + offs)
    idx = tl.load(indices_ptr + offs).to(tl.int32)
    plane = offs // plane_out
    dst = plane * plane_in + idx
    tl.atomic_add(grad_input_ptr + dst, g, sem="relaxed")


@triton.jit
def _adaptive_max_pool2d_backward_tail_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_input_ptr,
    plane_out: tl.constexpr,
    plane_in: tl.constexpr,
    base,
    n_elem,
    total_in,
    BLOCK: tl.constexpr,
):
    # Masked flat tail; masked lanes are clamped to in-bounds addresses.
    offs = base + tl.arange(0, BLOCK)
    mask = offs < n_elem
    g = tl.load(grad_output_ptr + offs, mask=mask, other=0.0)
    idx = tl.load(indices_ptr + offs, mask=mask, other=0).to(tl.int32)
    plane = offs // plane_out
    dst = tl.minimum(plane * plane_in + idx, total_in - 1)
    tl.atomic_add(grad_input_ptr + dst, g, mask=mask)


def adaptive_max_pool2d_backward(grad_output, self, indices):
    logger.debug("GEMS_THEAD ADAPTIVE_MAX_POOL2D_BACKWARD")
    hw_out = grad_output.shape[-1] * grad_output.shape[-2]
    hw_in = self.shape[-1] * self.shape[-2]
    num_planes = grad_output.numel() // hw_out
    H_out = grad_output.shape[-2]
    W_out = grad_output.shape[-1]
    H_in = self.shape[-2]
    W_in = self.shape[-1]
    total = grad_output.numel()

    if hw_out == 0 or num_planes == 0 or hw_in == 0:
        return torch.zeros_like(self)

    grad_flat = grad_output.view(-1)
    idx_flat = indices.view(-1)

    if total < 256:
        # tiny correctness-checked problems: deterministic per-plane dedup
        out = torch.zeros_like(self)
        KH = (H_out + H_in - 1) // H_in + 1
        KW = (W_out + W_in - 1) // W_in + 1
        KSUM = KH * KW
        BLOCK = max(2, triton.next_power_of_2(hw_out))
        KBITS = 16 if grad_output.dtype in (torch.float16, torch.bfloat16) else 32
        _adaptive_max_pool2d_backward_sort_kernel[(num_planes,)](
            grad_flat,
            idx_flat,
            out.view(-1),
            hw_out,
            hw_in,
            KBITS=KBITS,
            KSUM=KSUM,
            BLOCK=BLOCK,
        )
        return out

    if H_out <= H_in and W_out <= W_in:
        # downsampling timed path. fp32 atomics are ~store-speed on this backend,
        # so fp32 uses a fused zero + single relaxed-atomic scatter (no barriers);
        # fp16/bf16 keep the barrier-based 4-slot ordered RMW (no atomics).
        out = torch.empty_like(self)
        BLOCK = max(2, triton.next_power_of_2(hw_out))
        if grad_output.dtype == torch.float32:
            num_warps = 16 if BLOCK > 128 else 4
            _adaptive_max_pool2d_backward_zero_atomic_kernel[(num_planes,)](
                grad_flat,
                idx_flat,
                out.view(-1),
                hw_out,
                hw_in,
                BLOCK=BLOCK,
                ZBLOCK=2048,
                num_warps=num_warps,
            )
        else:
            num_warps = 16 if BLOCK > 128 else 2
            ZBLOCK = 1024 if BLOCK > 128 else 2048
            _adaptive_max_pool2d_backward_slots4_kernel[(num_planes,)](
                grad_flat,
                idx_flat,
                out.view(-1),
                H_out,
                W_out,
                H_in,
                W_in,
                hw_out,
                hw_in,
                BLOCK=BLOCK,
                ZBLOCK=ZBLOCK,
                num_warps=num_warps,
            )
        return out

    # general fallback (upsampling): zeros + flat maskless relaxed atomic scatter
    out = torch.zeros_like(self)
    out_flat = out.view(-1)
    BLOCK = 512 if total >= 100000 else 128
    bulk = (total // BLOCK) * BLOCK
    _adaptive_max_pool2d_backward_bulk_kernel[(bulk // BLOCK,)](
        grad_flat,
        idx_flat,
        out_flat,
        hw_out,
        hw_in,
        BLOCK=BLOCK,
    )
    if bulk < total:
        _adaptive_max_pool2d_backward_tail_kernel[(1,)](
            grad_flat,
            idx_flat,
            out_flat,
            hw_out,
            hw_in,
            bulk,
            total,
            out.numel(),
            BLOCK=BLOCK,
        )
    return out
