# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

MAX_D = tl.constexpr(8)
BLOCK = 512
WARPS = 8

logger = logging.getLogger(__name__)


@triton.jit
def _overwrite_kernel(src_ptr, buf_ptr, n, BLOCK: tl.constexpr):
    # Pure copy path: view covers every buffer position (c == 1, off == 0,
    # src_numel == buf_size). One unmasked load + store per element.
    pid = tl.program_id(0)
    q = pid * BLOCK + tl.arange(0, BLOCK)
    mask = q < n
    v = tl.load(
        src_ptr + q,
        mask=mask,
        other=0,
        cache_modifier=".cg",
        eviction_policy="evict_first",
    )
    tl.store(buf_ptr + q, v, mask=mask, eviction_policy="evict_first")


@triton.jit
def _fused_affine_kernel(
    self_ptr,
    buf_ptr,
    src_ptr,
    s0,
    numel,
    off,
    src_numel,
    buf_size,
    C: tl.constexpr,
    I64: tl.constexpr,
    FULL: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # View positions are exactly q == off + C*j for j in [0, src_numel).
    pid = tl.program_id(0)
    if I64:
        q = pid.to(tl.int64) * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    else:
        q = pid * BLOCK + tl.arange(0, BLOCK)
    if FULL:
        mask = tl.full([BLOCK], 1, tl.int1)
    else:
        mask = q < buf_size
    r = q - off
    if C == 1:
        j = r
        covered = (r >= 0) & (r < src_numel)
    elif C == -1:
        j = -r
        covered = (r <= 0) & (r > -src_numel)
    else:
        j = r // C
        covered = (r % C == 0) & (j >= 0) & (j < src_numel)
    src_val = tl.load(
        src_ptr + j,
        mask=mask & covered,
        other=0,
        cache_modifier=".cg",
        eviction_policy="evict_first",
    )
    self_pos = q - s0
    self_ok = (self_pos >= 0) & (self_pos < numel)
    self_val = tl.load(
        self_ptr + self_pos,
        mask=mask & self_ok & (~covered),
        other=0,
        cache_modifier=".cg",
        eviction_policy="evict_first",
    )
    val = tl.where(covered, src_val, self_val)
    tl.store(
        buf_ptr + q, val, mask=mask & (covered | self_ok), eviction_policy="evict_first"
    )


@triton.jit
def _fused_chain_kernel(
    self_ptr,
    buf_ptr,
    src_ptr,
    s0,
    numel,
    off,
    src_numel,
    buf_size,
    S: tl.constexpr,
    R: tl.constexpr,
    P: tl.constexpr,
    ND: tl.constexpr,
    I64: tl.constexpr,
    FULL: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # Stride chain: s_{d-1} % s_d == 0 for d=1..ND-1, g = s_{ND-1} = R[0] > 0,
    # and S[d] <= R[d] for d >= 1 (injective view). Then
    #   p = off + g * t,  t = i_0*m_0 + ... + i_{ND-1}  (mixed radix, radices R[1..]),
    # so q is covered iff the radix digits fall inside [0, S[d]).
    # j = sum i_d * P[d] (row-major src index).
    pid = tl.program_id(0)
    if I64:
        q = pid.to(tl.int64) * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    else:
        q = pid * BLOCK + tl.arange(0, BLOCK)
    if FULL:
        mask = tl.full([BLOCK], 1, tl.int1)
    else:
        mask = q < buf_size
    g = R[0]
    r = q - off
    covered = (r >= 0) & (r % g == 0)
    t = r // g
    rem = t
    if I64:
        j = tl.zeros([BLOCK], dtype=tl.int64)
    else:
        j = tl.zeros([BLOCK], dtype=tl.int32)
    for d in tl.static_range(ND - 1, 0, -1):
        i = rem % R[d]
        rem = rem // R[d]
        covered = covered & (i < S[d])
        j += i * P[d]
    covered = covered & (rem < S[0])
    j += rem * P[0]
    src_val = tl.load(
        src_ptr + j,
        mask=mask & covered,
        other=0,
        cache_modifier=".cg",
        eviction_policy="evict_first",
    )
    self_pos = q - s0
    self_ok = (self_pos >= 0) & (self_pos < numel)
    self_val = tl.load(
        self_ptr + self_pos,
        mask=mask & self_ok & (~covered),
        other=0,
        cache_modifier=".cg",
        eviction_policy="evict_first",
    )
    val = tl.where(covered, src_val, self_val)
    tl.store(
        buf_ptr + q, val, mask=mask & (covered | self_ok), eviction_policy="evict_first"
    )


@triton.jit
def _copy_flat_kernel(
    self_ptr, buf_ptr, s0, numel, I64: tl.constexpr, BLOCK: tl.constexpr
):
    pid = tl.program_id(0)
    if I64:
        k = pid.to(tl.int64) * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    else:
        k = pid * BLOCK + tl.arange(0, BLOCK)
    mask = k < numel
    v = tl.load(self_ptr + k, mask=mask, other=0)
    tl.store(buf_ptr + s0 + k, v, mask=mask)


@triton.jit
def _copy_general_kernel(
    self_ptr,
    buf_ptr,
    s0,
    numel,
    meta_ptr,
    ND: tl.constexpr,
    I64: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # meta = self.shape (ND) followed by self.strides (ND)
    pid = tl.program_id(0)
    if I64:
        k = pid.to(tl.int64) * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
        acc = tl.zeros([BLOCK], dtype=tl.int64)
    else:
        k = pid * BLOCK + tl.arange(0, BLOCK)
        acc = tl.zeros([BLOCK], dtype=tl.int32)
    mask = k < numel
    rem = k
    for d in tl.static_range(ND - 1, -1, -1):
        sh = tl.load(meta_ptr + d)
        st = tl.load(meta_ptr + ND + d)
        i = rem % sh
        rem = rem // sh
        acc += i * st
    v = tl.load(self_ptr + acc, mask=mask, other=0)
    tl.store(buf_ptr + s0 + acc, v, mask=mask)


@triton.jit
def _scatter_kernel(
    src_ptr,
    buf_ptr,
    off,
    src_numel,
    SZ: tl.constexpr,
    ST: tl.constexpr,
    SST: tl.constexpr,
    ND: tl.constexpr,
    I64: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # p = off + sum i_d * ST[d]; src index = sum i_d * SST[d] (0 for broadcast dims)
    pid = tl.program_id(0)
    if I64:
        j = pid.to(tl.int64) * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
        pv = tl.zeros([BLOCK], dtype=tl.int64)
        ps = tl.zeros([BLOCK], dtype=tl.int64)
    else:
        j = pid * BLOCK + tl.arange(0, BLOCK)
        pv = tl.zeros([BLOCK], dtype=tl.int32)
        ps = tl.zeros([BLOCK], dtype=tl.int32)
    mask = j < src_numel
    rem = j
    for d in tl.static_range(ND - 1, -1, -1):
        i = rem % SZ[d]
        rem = rem // SZ[d]
        pv += i * ST[d]
        ps += i * SST[d]
    v = tl.load(src_ptr + ps, mask=mask, other=0)
    tl.store(buf_ptr + off + pv, v, mask=mask)


def as_strided_scatter(self, src, size, stride, storage_offset=None):
    logger.debug("GEMS_THEAD AS_STRIDED_SCATTER")
    if torch.is_tensor(size):
        size = size.tolist()
    if torch.is_tensor(stride):
        stride = stride.tolist()
    size = [int(s) for s in size]
    stride = [int(s) for s in stride]
    D = len(size)
    MAX_D_INT = int(MAX_D)
    if D > MAX_D_INT:
        raise RuntimeError("as_strided_scatter: at most %d dims supported" % MAX_D_INT)
    if len(stride) != D:
        raise ValueError("size and stride must have equal length")

    if storage_offset is None:
        off = self.storage_offset()
    else:
        off = int(storage_offset)

    s0 = self.storage_offset()
    numel = self.numel()
    dtype = self.dtype
    device = self.device

    src_numel = 1
    for s in size:
        src_numel *= s

    # effective src strides (broadcast-aware, right-aligned)
    sd_ = src.dim() - D
    sst = []
    for d in range(D):
        sdim = d + sd_
        if sdim < 0:
            sst.append(0)
        elif src.shape[sdim] == size[d]:
            sst.append(src.stride(sdim))
        elif src.shape[sdim] == 1:
            sst.append(0)
        else:
            raise ValueError("src shape not broadcastable to view size")
    for d in range(max(0, sd_)):
        if src.shape[d] != 1:
            raise ValueError("src shape not broadcastable to view size")

    # view position upper bound
    vhi = off
    for d in range(D):
        if size[d] > 0 and stride[d] > 0:
            vhi += (size[d] - 1) * stride[d]

    # buffer spans the full storage of self (preserves storage geometry),
    # and is at least large enough for every view position
    storage_elems = self.untyped_storage().nbytes() // self.element_size()
    buf_size = max(storage_elems, vhi + 1)
    buf = torch.empty(buf_size, dtype=dtype, device=device)

    # 64-bit guard: use int64 index math if any magnitude can exceed int32
    vals = [numel, src_numel, s0, off, buf_size, vhi]
    for st in stride:
        vals.append(abs(st))
    for sts in self.stride():
        vals.append(abs(sts))
    for d in range(D):
        if size[d] > 0:
            vals.append(abs((size[d] - 1) * stride[d]))
    for d in range(self.dim()):
        if self.shape[d] > 0:
            vals.append(abs((self.shape[d] - 1) * self.stride()[d]))
    need64 = any(v >= 2**31 for v in vals)

    self_contig = self.is_contiguous()
    src_contig = src.is_contiguous()

    # affine view: stride[d] == c * prod(size[d+1:])  =>  p = off + c*j
    affine_c = None
    if D > 0:
        c0 = stride[-1]
        prod_ = 1
        ok = True
        for d in range(D - 1, -1, -1):
            if stride[d] != c0 * prod_:
                ok = False
                break
            prod_ *= size[d]
        if ok:
            affine_c = c0

    # chain view (non-affine, invertible): s_{d-1} % s_d == 0, s_d > 0,
    # g = s_{ND-1} > 0, and size[d] <= R[d] for d >= 1
    chain_params = None
    if affine_c is None and D >= 1 and src_numel > 0:
        R = [0] * D
        R[0] = stride[D - 1]
        ok = R[0] > 0
        for d in range(1, D):
            if stride[d] <= 0 or stride[d - 1] % stride[d] != 0:
                ok = False
                break
            R[d] = stride[d - 1] // stride[d]
            if size[d] > R[d]:
                ok = False
                break
        if ok:
            P = [1] * D
            pacc = 1
            for d in range(D - 1, -1, -1):
                P[d] = pacc
                pacc *= size[d]
            chain_params = (tuple(R), tuple(P))

    if src_numel == 0:
        use_overwrite = False
        use_affine = False
        use_chain = False
    else:
        use_overwrite = (
            (affine_c == 1)
            and (off == 0)
            and (src_numel == buf_size)
            and self_contig
            and src_contig
            and (numel > 0)
        )
        use_affine = (
            (not use_overwrite)
            and (affine_c is not None)
            and (affine_c != 0)
            and self_contig
            and src_contig
        )
        use_chain = (
            (not use_overwrite)
            and (chain_params is not None)
            and self_contig
            and src_contig
        )

    if use_overwrite:
        if buf_size > 0:
            grid = (triton.cdiv(buf_size, BLOCK),)
            _overwrite_kernel[grid](src, buf, buf_size, BLOCK=BLOCK, num_warps=WARPS)
    elif use_affine:
        if buf_size > 0:
            grid = (triton.cdiv(buf_size, BLOCK),)
            _fused_affine_kernel[grid](
                self,
                buf,
                src,
                s0,
                numel,
                off,
                src_numel,
                buf_size,
                C=affine_c,
                I64=need64,
                FULL=(buf_size % BLOCK == 0),
                BLOCK=BLOCK,
                num_warps=WARPS,
            )
    elif use_chain:
        if buf_size > 0:
            grid = (triton.cdiv(buf_size, BLOCK),)
            _fused_chain_kernel[grid](
                self,
                buf,
                src,
                s0,
                numel,
                off,
                src_numel,
                buf_size,
                S=tuple(size),
                R=chain_params[0],
                P=chain_params[1],
                ND=D,
                I64=need64,
                FULL=(buf_size % BLOCK == 0),
                BLOCK=BLOCK,
                num_warps=WARPS,
            )
    else:
        if numel > 0:
            if self_contig:
                grid = (triton.cdiv(numel, BLOCK),)
                _copy_flat_kernel[grid](
                    self, buf, s0, numel, I64=need64, BLOCK=BLOCK, num_warps=WARPS
                )
            else:
                nd = self.dim()
                if nd > MAX_D_INT:
                    raise RuntimeError("as_strided_scatter: self has too many dims")
                dt = torch.int64 if need64 else torch.int32
                meta = torch.tensor(
                    list(self.shape) + list(self.stride()), dtype=dt, device=device
                )
                grid = (triton.cdiv(numel, BLOCK),)
                _copy_general_kernel[grid](
                    self,
                    buf,
                    s0,
                    numel,
                    meta,
                    ND=nd,
                    I64=need64,
                    BLOCK=BLOCK,
                    num_warps=WARPS,
                )
        if src_numel > 0:
            grid = (triton.cdiv(src_numel, BLOCK),)
            _scatter_kernel[grid](
                src,
                buf,
                off,
                src_numel,
                SZ=tuple(size),
                ST=tuple(stride),
                SST=tuple(sst),
                ND=D,
                I64=need64,
                BLOCK=BLOCK,
                num_warps=WARPS,
            )

    if self_contig:
        return buf[s0 : s0 + numel].view(self.shape)
    return torch.as_strided(buf, self.shape, self.stride(), s0)
