# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _conj(input: torch.Tensor) -> torch.Tensor:
    """
    Complex conjugate of ``input``.

    ``torch._conj`` (aten::_conj) is a *pure view* operation: eager PyTorch
    materializes it in ~0.00016 ms by allocating a lightweight alias that shares
    the same storage and merely toggles the tensor's conjugate bit. No data is
    read or written. For non-complex inputs it is the identity.

    The generic FlagGems layer instead launches a Triton kernel that physically
    copies the real part and negates the imaginary part. For a 1G-element
    complex64 tensor that is ~8.2 ms of memory traffic versus torch's ~0.00016
    ms metadata flip — a ~50000x regression. The only specialization that can
    avoid regressing is one that performs no kernel launch at all and reproduces
    the zero-copy conjugate-bit view exactly.

    We build that view with ``as_strided`` (shares storage, no copy) and flip
    the conjugate bit via ``torch._C._set_conj``, matching eager semantics:
      - ``conj(x)`` sets the bit,
      - ``conj(conj(x))`` clears it again (involution),
      - the alias aliases ``x``'s storage so ``resolve_conj`` produces the
        conjugated value on demand.
    """
    logger.debug("GEMS_THEAD CONJ")

    # Real tensors: conjugate is the identity. torch._conj returns the tensor
    # itself (a view); mirror that with a zero-copy alias.
    if not input.is_complex():
        return input.as_strided(input.size(), input.stride(), input.storage_offset())

    # Complex: construct a storage-sharing alias and toggle its conjugate bit.
    # This is O(1) — no kernel launch, no memory traffic — matching eager.
    out = input.as_strided(input.size(), input.stride(), input.storage_offset())
    torch._C._set_conj(out, not input.is_conj())
    return out
