# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl
from triton.language.extra import libdevice

logger = logging.getLogger(__name__)


@triton.jit
def _erfc_half_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
    OUT_IS_BF16: tl.constexpr,
):
    # erfc via Abramowitz & Stegun 7.1.26 (max abs error ~1.5e-7 in fp32),
    # computed in fp32 and rounded to the half output dtype.
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask)
    xf = x.to(tl.float32)
    ax = tl.abs(xf)
    t = 1.0 / (1.0 + 0.3275911 * ax)
    p = t * (
        (((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t
        + 0.254829592
    )
    e = tl.exp2(-ax * ax * 1.4426950408889634) * p
    y = tl.where(xf >= 0.0, e, 2.0 - e)
    if OUT_IS_BF16:
        y = y.to(tl.bfloat16)
    else:
        y = y.to(tl.float16)
    tl.store(out_ptr + offsets, y, mask=mask)


@triton.jit
def _erfc_f32_kernel(x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask)
    y = 1.0 - tl.math.erf(x)
    tl.store(out_ptr + offsets, y, mask=mask)


@triton.jit
def _erfc_f64_kernel(x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask)
    y = libdevice.erfc(x)
    tl.store(out_ptr + offsets, y, mask=mask)


def erfc(x: torch.Tensor) -> torch.Tensor:
    logger.debug("GEMS_THEAD ERFC")
    out = torch.empty_like(x)
    n = x.numel()
    dtype = x.dtype
    if dtype == torch.float16 or dtype == torch.bfloat16:
        grid = ((n + 2047) >> 11,)
        _erfc_half_kernel[grid](
            x,
            out,
            n,
            BLOCK_SIZE=2048,
            OUT_IS_BF16=(dtype == torch.bfloat16),
            num_warps=8,
        )
    elif dtype == torch.float64:
        grid = ((n + 1023) >> 10,)
        _erfc_f64_kernel[grid](x, out, n, BLOCK_SIZE=1024, num_warps=4)
    else:
        grid = ((n + 2047) >> 11,)
        _erfc_f32_kernel[grid](x, out, n, BLOCK_SIZE=2048, num_warps=16)
    return out
