# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _rep_pad3d_bwd_fast_kernel(
    go_ptr,
    out_ptr,
    NC,
    D,
    H,
    W,
    D2,
    H2,
    W2,
    pl,
    pr,
    pt,
    pb,
    pf,
    pbk,
    BLOCK_W: tl.constexpr,
    BLOCK_P: tl.constexpr,
    ROWS: tl.constexpr,
):
    # Non-negative pads; ROWS consecutive H-rows per program for per-warp ILP.
    nc = tl.program_id(0)
    d = tl.program_id(1)
    h0 = ROWS * tl.program_id(2)

    ds = tl.where(d == 0, 0, pf + d)
    de = tl.where(d == D - 1, D2, pf + d + 1)

    w = tl.arange(0, BLOCK_W)
    wmask = w < W
    p = tl.arange(0, BLOCK_P)

    base = go_ptr + nc * (D2 * H2 * W2)
    out_base = out_ptr + nc * (D * H * W) + d * (H * W)

    for r in tl.static_range(ROWS):
        h = h0 + r
        hs = tl.where(h == 0, 0, pt + h)
        he = tl.where(h == H - 1, H2, pt + h + 1)

        acc = tl.zeros((BLOCK_W,), dtype=tl.float32)
        lt = tl.zeros((BLOCK_P,), dtype=tl.float32)
        rt = tl.zeros((BLOCK_P,), dtype=tl.float32)
        for dd in tl.range(ds, de):
            for hh in tl.range(hs, he):
                rb = base + dd * (H2 * W2) + hh * W2
                acc += tl.load(rb + pl + w, mask=wmask, other=0.0).to(tl.float32)
                lt += tl.load(rb + p, mask=p < pl, other=0.0).to(tl.float32)
                rt += tl.load(rb + pl + W + p, mask=p < pr, other=0.0).to(tl.float32)
        left = tl.sum(lt)
        right = tl.sum(rt)

        acc = tl.where(w == 0, acc + left, acc)
        acc = tl.where(w == W - 1, acc + right, acc)

        out_off = out_base + h * W + w
        tl.store(out_off, acc.to(out_ptr.dtype.element_ty), mask=wmask)


@triton.jit
def _rep_pad3d_bwd_kernel(
    go_ptr,
    out_ptr,
    NC,
    D,
    H,
    W,
    D2,
    H2,
    W2,
    pl,
    pr,
    pt,
    pb,
    pf,
    pbk,
    BLOCK_W: tl.constexpr,
    BLOCK_P: tl.constexpr,
):
    # General (possibly negative / cropping) pads.
    # 3D grid: (nc, d, h); lanes cover the W dimension of one output row.
    nc = tl.program_id(0)
    d = tl.program_id(1)
    h = tl.program_id(2)

    # --- D-axis range [ds, de) of grad_output depth indices replicating to d.
    # General pad semantics: out[o] = in[clamp(o - lo, 0, S-1)].
    is_first = d == 0
    is_last = d == D - 1
    de0 = tl.maximum(0, tl.minimum(pf + 1, D2))  # d == 0 case
    dsL = tl.where(pbk >= 0, tl.maximum(0, pf + D - 1), D2)  # d == D-1 case
    valid_i = (pf + d >= 0) & (pf + d < D2)  # interior case
    ds = tl.where(
        D == 1,
        0,
        tl.where(is_first, 0, tl.where(is_last, dsL, tl.where(valid_i, pf + d, D2))),
    )
    de = tl.where(
        D == 1,
        D2,
        tl.where(
            is_first, de0, tl.where(is_last, D2, tl.where(valid_i, pf + d + 1, D2))
        ),
    )

    # --- H-axis range [hs, he).
    is_first_h = h == 0
    is_last_h = h == H - 1
    he0 = tl.maximum(0, tl.minimum(pt + 1, H2))
    hsL = tl.where(pb >= 0, tl.maximum(0, pt + H - 1), H2)
    valid_h = (pt + h >= 0) & (pt + h < H2)
    hs = tl.where(
        H == 1,
        0,
        tl.where(
            is_first_h, 0, tl.where(is_last_h, hsL, tl.where(valid_h, pt + h, H2))
        ),
    )
    he = tl.where(
        H == 1,
        H2,
        tl.where(
            is_first_h, he0, tl.where(is_last_h, H2, tl.where(valid_h, pt + h + 1, H2))
        ),
    )

    w = tl.arange(0, BLOCK_W)
    wmask = w < W
    p = tl.arange(0, BLOCK_P)

    base = go_ptr + nc * (D2 * H2 * W2)

    # W-axis: single replicated column pl + w (masked out when cropped), plus
    # left pad segment [0, cntL) added to lane 0 and right pad segment
    # [r_start, r_start + r_cnt) added to lane W-1.
    core_mask = wmask & (pl + w >= 0) & (pl + w < W2)
    cntL = tl.maximum(0, tl.minimum(pl, W2))
    r_start = tl.maximum(0, pl + W)
    r_cnt = tl.maximum(0, W2 - r_start)

    acc = tl.zeros((BLOCK_W,), dtype=tl.float32)
    for dd in tl.range(ds, de):
        for hh in tl.range(hs, he):
            rb = base + dd * (H2 * W2) + hh * W2
            acc += tl.load(rb + pl + w, mask=core_mask, other=0.0).to(tl.float32)

    lt = tl.zeros((BLOCK_P,), dtype=tl.float32)
    for w0 in tl.range(0, cntL, BLOCK_P):
        pp = w0 + p
        pm = pp < cntL
        ltile = tl.zeros((BLOCK_P,), dtype=tl.float32)
        for dd in tl.range(ds, de):
            for hh in tl.range(hs, he):
                rb = base + dd * (H2 * W2) + hh * W2
                ltile += tl.load(rb + pp, mask=pm, other=0.0).to(tl.float32)
        lt += ltile
    left = tl.sum(lt)

    rt = tl.zeros((BLOCK_P,), dtype=tl.float32)
    for w0 in tl.range(0, r_cnt, BLOCK_P):
        pp = r_start + w0 + p
        pm = p < r_cnt
        rtile = tl.zeros((BLOCK_P,), dtype=tl.float32)
        for dd in tl.range(ds, de):
            for hh in tl.range(hs, he):
                rb = base + dd * (H2 * W2) + hh * W2
                rtile += tl.load(rb + pp, mask=pm, other=0.0).to(tl.float32)
        rt += rtile
    right = tl.sum(rt)

    acc = tl.where(w == 0, acc + left, acc)
    acc = tl.where(w == W - 1, acc + right, acc)

    out_off = out_ptr + nc * (D * H * W) + d * (H * W) + h * W + w
    tl.store(out_off, acc.to(out_ptr.dtype.element_ty), mask=wmask)


def replication_pad3d_backward(grad_output, self, padding):
    logger.debug("GEMS_THEAD REPLICATION_PAD3D_BACKWARD")
    if isinstance(padding, torch.Tensor):
        pad = [int(v) for v in padding.detach().cpu().tolist()]
    elif isinstance(padding, (int,)):
        pad = [int(padding)] * 6
    else:
        pad = [int(v) for v in padding]
    if len(pad) != 6:
        raise ValueError(f"replication_pad3d expects 6 padding values, got {len(pad)}")
    pl, pr, pt, pb, pf, pbk = pad

    x = self
    if x.dim() == 5:
        N, C, D, H, W = x.shape
        NC = N * C
    elif x.dim() == 4:
        C, D, H, W = x.shape
        NC = C
    else:
        raise ValueError(f"replication_pad3d expects 4D or 5D input, got {x.dim()}D")

    D2 = D + pf + pbk
    H2 = H + pt + pb
    W2 = W + pl + pr

    # Validate grad_output shape, including the leading (batch/channel) dims.
    expected_go_shape = tuple(x.shape[:-3]) + (D2, H2, W2)
    if tuple(grad_output.shape) != expected_go_shape:
        raise ValueError(
            "grad_output leading dimensions do not match input: "
            f"got grad_output shape {tuple(grad_output.shape)}, "
            f"expected {expected_go_shape} for input shape {tuple(x.shape)} "
            f"and padding {tuple(pad)}"
        )

    xv = x.contiguous()
    go = grad_output.contiguous().view(NC, D2, H2, W2)
    out = torch.empty_like(xv)
    outv = out.view(NC, D, H, W)

    total = NC * D * H * W
    if total == 0:
        return out

    BLOCK_W = triton.next_power_of_2(W)
    BLOCK_P = triton.next_power_of_2(max(1, max(pl, pr)))
    if BLOCK_W <= 32:
        num_warps = 1
    elif BLOCK_W <= 64:
        num_warps = 2
    elif BLOCK_W <= 128:
        num_warps = 4
    else:
        num_warps = 8

    fast = (
        (pl >= 0) and (pr >= 0) and (pt >= 0) and (pb >= 0) and (pf >= 0) and (pbk >= 0)
    )
    if fast:
        # Shape-adaptive rows per program: narrow rows prefer 1, wide rows 2,
        # and only the deep (D>=32) family measured better with 4.
        if (W > 16) and (D >= 32) and (H % 4 == 0):
            rows = 4
        elif (W > 16) and (H % 2 == 0):
            rows = 2
        else:
            rows = 1
        grid = (NC, D, H // rows)
        _rep_pad3d_bwd_fast_kernel[grid](
            go,
            outv,
            NC,
            D,
            H,
            W,
            D2,
            H2,
            W2,
            pl,
            pr,
            pt,
            pb,
            pf,
            pbk,
            BLOCK_W=BLOCK_W,
            BLOCK_P=BLOCK_P,
            ROWS=rows,
            num_warps=num_warps,
        )
    else:
        grid = (NC, D, H)
        _rep_pad3d_bwd_kernel[grid](
            go,
            outv,
            NC,
            D,
            H,
            W,
            D2,
            H2,
            W2,
            pl,
            pr,
            pt,
            pb,
            pf,
            pbk,
            BLOCK_W=BLOCK_W,
            BLOCK_P=BLOCK_P,
            num_warps=num_warps,
        )
    return out
