# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl
from triton.language.extra import libdevice

logger = logging.getLogger(__name__)


@triton.jit
def _round0_loop_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    IS_FP64: tl.constexpr,
    BLOCK: tl.constexpr,
    ITERS: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    base = pid * (ITERS * BLOCK)
    for i in tl.static_range(ITERS):
        offs = base + i * BLOCK + tl.arange(0, BLOCK)
        x = tl.load(x_ptr + offs, cache_modifier=".cg")
        if IS_FP64:
            r = libdevice.nearbyint(x)
        else:
            r = libdevice.nearbyint(x.to(tl.float32)).to(x.dtype)
        tl.store(out_ptr + offs, r)


@triton.jit
def _round0_masked_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    IS_FP64: tl.constexpr,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < n_elements
    x = tl.load(x_ptr + offs, mask=mask, cache_modifier=".cg")
    if IS_FP64:
        r = libdevice.nearbyint(x)
    else:
        r = libdevice.nearbyint(x.to(tl.float32)).to(x.dtype)
    tl.store(out_ptr + offs, r, mask=mask)


@triton.jit
def _round_scaled_kernel(
    x_ptr,
    out_ptr,
    factor_ptr,
    n_elements,
    IS_FP64: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offs < n_elements
    x = tl.load(x_ptr + offs, mask=mask)
    # reference path: multiply by float-cast factor in opmath precision
    factor64 = tl.load(factor_ptr)
    f32 = factor64.to(tl.float32)
    if IS_FP64:
        y = x * factor64
        r = libdevice.nearbyint(y)
    else:
        y = x.to(tl.float32) * f32
        r = libdevice.nearbyint(y)
    # division in fp64 by the double factor, then cast back
    z = r.to(tl.float64) / factor64
    tl.store(out_ptr + offs, z.to(x.dtype), mask=mask)


def _launch_round0(A, out, numel, is_fp64):
    dt = A.dtype
    if numel <= 65536:
        if dt == torch.float32:
            block, warps, iters = 256, 1, 1
        else:
            block, warps, iters = 128, 1, 1
    elif numel <= (1 << 24):
        if dt == torch.float32:
            block, warps, iters = 1024, 1, 1
        else:
            block, warps, iters = 2048, 1, 1
    else:
        if dt == torch.float32:
            block, warps, iters = 1024, 8, 16
        else:
            block, warps, iters = 512, 4, 32
    span = block * iters
    if numel % span == 0:
        grid = (numel // span,)
        _round0_loop_kernel[grid](
            A, out, numel, IS_FP64=is_fp64, BLOCK=block, ITERS=iters, num_warps=warps
        )
    else:
        mblock = 1024 if numel > 65536 else 256
        mwarps = 4 if numel > 65536 else 1
        grid = (triton.cdiv(numel, mblock),)
        _round0_masked_kernel[grid](
            A, out, numel, IS_FP64=is_fp64, BLOCK=mblock, num_warps=mwarps
        )


def special_round(A, *, decimals=0):
    logger.debug("GEMS_THEAD SPECIAL_ROUND")
    out = torch.empty_like(A)
    numel = A.numel()
    is_fp64 = A.dtype == torch.float64
    if decimals == 0:
        if numel > 0:
            _launch_round0(A, out, numel, is_fp64)
    else:
        factor64 = torch.tensor(10.0**decimals, dtype=torch.float64, device=A.device)
        grid = lambda meta: (triton.cdiv(numel, meta["BLOCK_SIZE"]),)
        _round_scaled_kernel[grid](
            A, out, factor64, numel, IS_FP64=is_fp64, BLOCK_SIZE=1024, num_warps=4
        )
    return out
