# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

_MAX_NDIM = 8
_CONSTEXPR_N_LIMIT = 2048

logger = logging.getLogger(__name__)


@triton.jit
def _leg_p_cx(
    x_ptr,
    out_ptr,
    total,
    N: tl.constexpr,
    BLOCK: tl.constexpr,
    USE_F64: tl.constexpr,
):
    # Fast path: scalar integer degree N (constexpr), x contiguous, out contiguous.
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < total
    xv = tl.load(
        x_ptr + offs,
        mask=mask,
        other=0.0,
        cache_modifier=".cg",
        eviction_policy="evict_first",
    )
    if USE_F64:
        xf = xv.to(tl.float64)
    else:
        xf = xv

    if N < 0:
        # torch returns 0 for negative degree
        res = tl.zeros([BLOCK], dtype=xf.dtype)
    elif N == 0:
        res = tl.full([BLOCK], 1.0, dtype=xf.dtype)
    elif N == 1:
        res = xf
    else:
        p0 = tl.full([BLOCK], 1.0, dtype=xf.dtype)  # P_0
        p1 = xf  # P_1
        # P_k = ((2k-1) x P_{k-1} - (k-1) P_{k-2}) / k
        for k in tl.static_range(2, N + 1):
            p2 = ((2 * k - 1) * xf * p1 - (k - 1) * p0) / k
            p0 = p1
            p1 = p2
        res = p1

    tl.store(
        out_ptr + offs,
        res.to(out_ptr.dtype.element_ty),
        mask=mask,
        eviction_policy="evict_first",
    )


@triton.jit
def _leg_p_nm(
    x_ptr,
    out_ptr,
    N: tl.constexpr,
    BLOCK: tl.constexpr,
    USE_F64: tl.constexpr,
):
    # Mask-free fast path for small contiguous workloads with total % BLOCK == 0.
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    xv = tl.load(x_ptr + offs, cache_modifier=".cg", eviction_policy="evict_first")
    if USE_F64:
        xf = xv.to(tl.float64)
    else:
        xf = xv

    if N < 0:
        res = tl.zeros([BLOCK], dtype=xf.dtype)
    elif N == 0:
        res = tl.full([BLOCK], 1.0, dtype=xf.dtype)
    elif N == 1:
        res = xf
    else:
        p0 = tl.full([BLOCK], 1.0, dtype=xf.dtype)  # P_0
        p1 = xf  # P_1
        # P_k = ((2k-1) x P_{k-1} - (k-1) P_{k-2}) / k
        for k in tl.static_range(2, N + 1):
            p2 = ((2 * k - 1) * xf * p1 - (k - 1) * p0) / k
            p0 = p1
            p1 = p2
        res = p1

    tl.store(
        out_ptr + offs, res.to(out_ptr.dtype.element_ty), eviction_policy="evict_first"
    )


@triton.jit
def _leg_p_gs(
    x_ptr,
    out_ptr,
    total,
    N: tl.constexpr,
    BLOCK: tl.constexpr,
    NPROG: tl.constexpr,
    USE_F64: tl.constexpr,
):
    # Grid-stride variant for very large contiguous workloads: NPROG programs,
    # each streams multiple blocks with a strided loop.
    pid = tl.program_id(0)
    step = NPROG * BLOCK
    for base in tl.range(pid * BLOCK, total, step):
        offs = base + tl.arange(0, BLOCK)
        mask = offs < total
        xv = tl.load(
            x_ptr + offs,
            mask=mask,
            other=0.0,
            cache_modifier=".cg",
            eviction_policy="evict_first",
        )
        if USE_F64:
            xf = xv.to(tl.float64)
        else:
            xf = xv

        if N < 0:
            res = tl.zeros([BLOCK], dtype=xf.dtype)
        elif N == 0:
            res = tl.full([BLOCK], 1.0, dtype=xf.dtype)
        elif N == 1:
            res = xf
        else:
            p0 = tl.full([BLOCK], 1.0, dtype=xf.dtype)
            p1 = xf
            for k in tl.static_range(2, N + 1):
                p2 = ((2 * k - 1) * xf * p1 - (k - 1) * p0) / k
                p0 = p1
                p1 = p2
            res = p1

        tl.store(
            out_ptr + offs,
            res.to(out_ptr.dtype.element_ty),
            mask=mask,
            eviction_policy="evict_first",
        )


@triton.jit
def _leg_p_kernel(
    x_ptr,
    n_ptr,
    out_ptr,
    total,
    D0,
    D1,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    XS0,
    XS1,
    XS2,
    XS3,
    XS4,
    XS5,
    XS6,
    XS7,
    NS0,
    NS1,
    NS2,
    NS3,
    NS4,
    NS5,
    NS6,
    NS7,
    NDIM: tl.constexpr,
    X_SIMPLE: tl.constexpr,
    N_SIMPLE: tl.constexpr,
    N_SCALAR: tl.constexpr,
    BLOCK: tl.constexpr,
    USE_F64: tl.constexpr,
):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < total

    # ---- x offset (row-major linear index -> element offset) ----
    if X_SIMPLE:
        x_off = offs
    else:
        idx = offs
        x_off = tl.zeros([BLOCK], dtype=tl.int32)
        if NDIM >= 1:
            c = idx % D0
            idx = idx // D0
            x_off += c * XS0
        if NDIM >= 2:
            c = idx % D1
            idx = idx // D1
            x_off += c * XS1
        if NDIM >= 3:
            c = idx % D2
            idx = idx // D2
            x_off += c * XS2
        if NDIM >= 4:
            c = idx % D3
            idx = idx // D3
            x_off += c * XS3
        if NDIM >= 5:
            c = idx % D4
            idx = idx // D4
            x_off += c * XS4
        if NDIM >= 6:
            c = idx % D5
            idx = idx // D5
            x_off += c * XS5
        if NDIM >= 7:
            c = idx % D6
            idx = idx // D6
            x_off += c * XS6
        if NDIM >= 8:
            c = idx % D7
            idx = idx // D7
            x_off += c * XS7

    # ---- n value ----
    if N_SCALAR:
        nv = tl.load(n_ptr)
    else:
        if N_SIMPLE:
            n_off = offs
        else:
            idx = offs
            n_off = tl.zeros([BLOCK], dtype=tl.int32)
            if NDIM >= 1:
                c = idx % D0
                idx = idx // D0
                n_off += c * NS0
            if NDIM >= 2:
                c = idx % D1
                idx = idx // D1
                n_off += c * NS1
            if NDIM >= 3:
                c = idx % D2
                idx = idx // D2
                n_off += c * NS2
            if NDIM >= 4:
                c = idx % D3
                idx = idx // D3
                n_off += c * NS3
            if NDIM >= 5:
                c = idx % D4
                idx = idx // D4
                n_off += c * NS4
            if NDIM >= 6:
                c = idx % D5
                idx = idx // D5
                n_off += c * NS5
            if NDIM >= 7:
                c = idx % D6
                idx = idx // D6
                n_off += c * NS6
            if NDIM >= 8:
                c = idx % D7
                idx = idx // D7
                n_off += c * NS7
        nv = tl.load(n_ptr + n_off, mask=mask, other=0)

    xv = tl.load(
        x_ptr + x_off,
        mask=mask,
        other=0.0,
        cache_modifier=".cg",
        eviction_policy="evict_first",
    )
    if USE_F64:
        xf = xv.to(tl.float64)
    else:
        xf = xv

    # torch truncates n toward zero (int cast); negative n -> 0
    ni = nv.to(tl.int32)
    neg = ni < 0
    deg = tl.where(neg, 0, ni)

    p0 = tl.full([BLOCK], 1.0, dtype=xf.dtype)  # P_0
    p1 = xf  # P_1

    if N_SCALAR:
        # deg is a scalar; runtime-bounded loop
        for k in range(2, deg + 1):
            kf = k.to(xf.dtype)
            p2 = ((2.0 * kf - 1.0) * xf * p1 - (kf - 1.0) * p0) / kf
            p0 = p1
            p1 = p2
        res = tl.where(deg == 0, p0, p1)
    else:
        nmax = tl.max(deg)
        for k in range(2, nmax + 1):
            active = k <= deg
            kf = k.to(xf.dtype)
            p2 = ((2.0 * kf - 1.0) * xf * p1 - (kf - 1.0) * p0) / kf
            p0 = tl.where(active, p1, p0)
            p1 = tl.where(active, p2, p1)
        res = tl.where(deg == 0, p0, p1)

    res = tl.where(neg, 0.0, res)
    tl.store(
        out_ptr + offs,
        res.to(out_ptr.dtype.element_ty),
        mask=mask,
        eviction_policy="evict_first",
    )


def special_legendre_polynomial_p(x, n):
    logger.debug("GEMS_THEAD SPECIAL_LEGENDRE_POLYNOMIAL_P")
    if isinstance(n, torch.Tensor):
        out_shape = torch.broadcast_shapes(x.shape, n.shape)
        n_is_scalar = n.numel() == 1
    else:
        out_shape = tuple(x.shape)
        n_is_scalar = True

    out = torch.empty(out_shape, dtype=x.dtype, device=x.device)
    total = out.numel()
    if total == 0:
        return out

    ndim = len(out_shape)
    assert ndim <= _MAX_NDIM, f"ndim {ndim} unsupported"

    x_simple = (x.shape == out_shape) and x.is_contiguous()

    use_f64 = x.dtype == torch.float64

    # Fastest path: scalar python int/float degree with contiguous x
    if (
        x_simple
        and n_is_scalar
        and not isinstance(n, torch.Tensor)
        and abs(int(n)) <= _CONSTEXPR_N_LIMIT
    ):
        N = int(n)
        if total > 67108864:
            # Grid-stride: fewer programs streaming multiple blocks beats the
            # 4M-program single-block launch on the 1G-element workloads.
            _leg_p_gs[(32768,)](
                x,
                out,
                total,
                N=N,
                BLOCK=512,
                NPROG=32768,
                USE_F64=use_f64,
                num_warps=4,
                num_stages=1,
            )
        elif total < 262144:
            if total % 64 == 0:
                _leg_p_nm[(total // 64,)](
                    x, out, N=N, BLOCK=64, USE_F64=use_f64, num_warps=1
                )
            else:
                _leg_p_cx[(triton.cdiv(total, 256),)](
                    x, out, total, N=N, BLOCK=256, USE_F64=use_f64, num_warps=8
                )
        else:
            _leg_p_cx[(triton.cdiv(total, 2048),)](
                x, out, total, N=N, BLOCK=2048, USE_F64=use_f64, num_warps=2
            )
        return out

    if total < 262144:
        BLOCK, NW = 256, 8
    elif total <= 67108864:
        BLOCK, NW = 2048, 2
    else:
        BLOCK, NW = 256, 4
    grid = (triton.cdiv(total, BLOCK),)

    xb = x if x_simple else torch.broadcast_to(x, out_shape)

    if n_is_scalar:
        if isinstance(n, torch.Tensor):
            n_ptr = n.reshape(-1)
        else:
            n_ptr = torch.tensor(int(n), dtype=torch.int32, device=x.device)
        n_simple = True
        nst_rev = [0] * _MAX_NDIM
    else:
        nb = torch.broadcast_to(n, out_shape)
        n_ptr = nb
        n_simple = (n.shape == out_shape) and n.is_contiguous()
        nst_rev = list(reversed(nb.stride())) + [0] * (_MAX_NDIM - ndim)

    dims_rev = list(reversed(out_shape)) + [1] * (_MAX_NDIM - ndim)
    xst_rev = list(reversed(xb.stride())) + [0] * (_MAX_NDIM - ndim)

    _leg_p_kernel[grid](
        x,
        n_ptr,
        out,
        total,
        *dims_rev,
        *xst_rev,
        *nst_rev,
        NDIM=ndim,
        X_SIMPLE=x_simple,
        N_SIMPLE=n_simple,
        N_SCALAR=n_is_scalar,
        BLOCK=BLOCK,
        USE_F64=(x.dtype == torch.float64),
        num_warps=NW,
    )
    return out
