# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils.shape_utils import volume

logger = logging.getLogger(__name__)

# Physicist's Hermite polynomial recurrence:
#   H_0(x) = 1, H_1(x) = 2*x,
#   H_{k+1}(x) = 2*x*H_k(x) - 2*k*H_{k-1}(x).
# Evaluated in float32 for numerical stability, matching the general layer.


@libentry()
@triton.jit
def hermite_polynomial_h_tensor_kernel(
    x_ptr,
    n_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    # Tensor-n path: every element carries its own degree, so all of H_2..H_9
    # must be produced and the right one selected per lane. The general layer
    # instead expands the closed form of every degree (each needs the full power
    # series x^2..x^9), which is ~6x more FLOPs than this 8-step recurrence. On
    # PPU that extra compute shows up on mid/tiny shapes; the huge shapes stay
    # memory-bound and break even.
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    n = tl.load(n_ptr + offsets, mask=mask, other=0.0)
    n_int = n.to(tl.int32)

    xf = x.to(tl.float32)
    two_x = 2.0 * xf

    h_km1 = tl.full([BLOCK_SIZE], 1.0, tl.float32)  # H_0(x) = 1
    h_k = two_x  # H_1(x) = 2x

    result = tl.where(n_int == 0, h_km1, h_k)

    # Unroll the recurrence to degree 9: H_{k+1} = 2x*H_k - 2k*H_{k-1}.
    for k in tl.static_range(1, 9):
        h_kp1 = tl.fma(two_x, h_k, (-2.0 * k) * h_km1)
        h_km1 = h_k
        h_k = h_kp1
        result = tl.where(n_int == (k + 1), h_k, result)

    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


@libentry()
@triton.jit
def hermite_polynomial_h_scalar_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    N: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    # Scalar-n path: the degree is a compile-time constant, so the recurrence is
    # unrolled exactly to H_N with no per-lane selection. This is strictly cheaper
    # than both the general layer (which still computes all 10 closed forms) and
    # the tensor path above.
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    xf = x.to(tl.float32)
    two_x = 2.0 * xf

    h_km1 = tl.full([BLOCK_SIZE], 1.0, tl.float32)  # H_0(x) = 1
    h_k = two_x  # H_1(x) = 2x

    # H_0 / H_1 fall out of the (empty) loop below via the constexpr branches.
    if N == 0:
        result = h_km1
    elif N == 1:
        result = h_k
    else:
        for k in tl.static_range(1, N):
            h_kp1 = tl.fma(two_x, h_k, (-2.0 * k) * h_km1)
            h_km1 = h_k
            h_k = h_kp1
        result = h_k

    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


def _hermite_block_and_warps(n_elements):
    # PPU elementwise sweet spot: BLOCK=1024 keeps enough warps in flight to hide
    # the 8-deep recurrence latency on mid shapes; tiny shapes shrink the block
    # to avoid a mostly-masked tail and a wasted tail program.
    if n_elements <= 4096:
        return 256, 4
    return 1024, 8


def _validate_dtype(x):
    if x.dtype not in (torch.float32, torch.float64):
        raise ValueError(f"Unsupported dtype {x.dtype}")


def _validate_n_range_tensor(n):
    # One fused reduction (torch.aminmax) replaces the general layer's
    # n.to(int32) + .min().item() + .max().item() — an int32 allocation plus two
    # separate reductions. The host sync this forces dominates small-shape
    # latency, so fusing the min/max into a single pass roughly halves the GPU
    # work there. The error message keeps the general layer's int formatting.
    n_min, n_max = torch.aminmax(n)
    n_min = int(n_min.item())
    n_max = int(n_max.item())
    if n_min < 0 or n_max > 9:
        raise ValueError(
            f"special_hermite_polynomial_h only supports n in [0, 9], "
            f"got n in [{n_min}, {n_max}]"
        )


def _validate_n_range_scalar(n):
    if int(n) < 0 or int(n) > 9:
        raise ValueError(
            f"special_hermite_polynomial_h only supports n in [0, 9], got n={n}"
        )


def special_hermite_polynomial_h_tensor_tensor(x, n):
    logger.debug("GEMS_THEAD SPECIAL_HERMITE_POLYNOMIAL_H")
    _validate_dtype(x)
    _validate_n_range_tensor(n)

    x_b, n_b = torch.broadcast_tensors(x, n)
    x_c = x_b.contiguous()
    n_c = n_b.contiguous()
    out = torch.empty_like(x_c)

    n_elements = volume(x_c.shape)
    if n_elements == 0:
        return out

    block, warps = _hermite_block_and_warps(n_elements)
    grid = (triton.cdiv(n_elements, block),)
    with torch_device_fn.device(x_c.device):
        hermite_polynomial_h_tensor_kernel[grid](
            x_c, n_c, out, n_elements, BLOCK_SIZE=block, num_warps=warps
        )
    return out


def special_hermite_polynomial_h(x, n):
    logger.debug("GEMS_THEAD SPECIAL_HERMITE_POLYNOMIAL_H")
    if not isinstance(x, torch.Tensor):
        raise ValueError("First argument must be a tensor")
    _validate_dtype(x)

    if isinstance(n, torch.Tensor):
        return special_hermite_polynomial_h_tensor_tensor(x, n)
    elif isinstance(n, (int, float)):
        _validate_n_range_scalar(n)
        n_int = int(n)

        x_c = x.contiguous()
        out = torch.empty_like(x_c)
        n_elements = volume(x_c.shape)
        if n_elements == 0:
            return out

        block, warps = _hermite_block_and_warps(n_elements)
        grid = (triton.cdiv(n_elements, block),)
        with torch_device_fn.device(x_c.device):
            hermite_polynomial_h_scalar_kernel[grid](
                x_c,
                out,
                n_elements,
                N=n_int,
                BLOCK_SIZE=block,
                num_warps=warps,
            )
        return out
    else:
        raise ValueError("n must be a Tensor, int, or float")
