# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def _greater_equal_fused(x, y):
    """Fused greater-equal that avoids uitofp i1→bf16 on Metax backend.

    Uses tl.where to produce 1.0/0.0 float values directly from the
    boolean comparison, avoiding arith.uitofp i1→bf16 which is
    unsupported on the Metax LLVM-level lowering.
    """
    cmp = x.to(tl.float32) >= y
    return tl.where(cmp, 1.0, 0.0)


def greater_equal_(A, B):
    logger.debug("GEMS_METAX GREATER_EQUAL_")
    if A.device != B.device:
        B = B.to(A.device)
    return _greater_equal_fused(A, B, out0=A)
