# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import triton
import triton.language as tl
from triton.language.extra import libdevice

_U1_FLOOR = tl.constexpr(3.731547881843398e-06)  # exp(-12.5): keeps |z| <= 5.0
_TWO_PI = tl.constexpr(6.283185307179586)
_LOG2E = tl.constexpr(1.4426950408889634)
_UNIF_SCALE = tl.constexpr(5.960464477539063e-08)  # 2^-24
_U2_OFFSET = tl.constexpr(
    1367138743
)  # int32-safe prime offset, decorrelates the u2 stream


@triton.jit
def _box_muller_pair(u_a, u_b):
    # One (r, angle) pair -> two independent standard normals (Box-Muller).
    u_a = tl.maximum(u_a, _U1_FLOOR)
    r = tl.sqrt(-2.0 * libdevice.fast_logf(u_a))
    th = _TWO_PI * u_b
    return r * libdevice.fast_cosf(th), r * libdevice.fast_sinf(th)


@triton.jit
def _log_normal_small_kernel(
    out_ptr,
    n_elements,
    mean,
    std,
    BLOCK: tl.constexpr,
    HALF: tl.constexpr,
    SEED: tl.constexpr,
    EVEN: tl.constexpr,
):
    # Launch/latency-bound small path: 2 tl.rand streams per (BLOCK/2) lane,
    # one Box-Muller normal, antithetic pair, single interleaved store.
    pid = tl.program_id(0)
    pair_offs = pid * HALF + tl.arange(0, HALF)
    u1 = tl.maximum(tl.rand(SEED, pair_offs), _U1_FLOOR)
    u2 = tl.rand(SEED, pair_offs + _U2_OFFSET)

    z = tl.sqrt(-2.0 * libdevice.fast_logf(u1)) * libdevice.fast_cosf(_TWO_PI * u2)
    s = std * z
    vals = tl.interleave(
        tl.exp2((mean + s) * _LOG2E),
        tl.exp2((mean - s) * _LOG2E),
    ).to(out_ptr.dtype.element_ty)

    offs = pid * BLOCK + tl.arange(0, BLOCK)
    if EVEN:
        tl.store(out_ptr + offs, vals)
    else:
        tl.store(out_ptr + offs, vals, mask=offs < n_elements)


@triton.jit
def _log_normal_big_kernel(
    out_ptr,
    n_elements,
    mean,
    std,
    BLOCK: tl.constexpr,
    EIGHTH: tl.constexpr,
    N_ROUNDS: tl.constexpr,
    SEED: tl.constexpr,
    EVEN: tl.constexpr,
):
    pid = tl.program_id(0)
    eoffs = pid * EIGHTH + tl.arange(0, EIGHTH)

    # One Philox state -> 4 uniforms -> 2 (r, angle) pairs -> 4 normals;
    # with antithetic mirrors that is 8 log-normal outputs per state.
    i1, i2, i3, i4 = tl.randint4x(SEED, eoffs, N_ROUNDS)
    u1 = (i1 >> 8).to(tl.float32) * _UNIF_SCALE
    u2 = (i2 >> 8).to(tl.float32) * _UNIF_SCALE
    u3 = (i3 >> 8).to(tl.float32) * _UNIF_SCALE
    u4 = (i4 >> 8).to(tl.float32) * _UNIF_SCALE

    za, zb = _box_muller_pair(u1, u2)
    zc, zd = _box_muller_pair(u3, u4)

    sa = std * za
    sb = std * zb
    sc = std * zc
    sd = std * zd

    dt = out_ptr.dtype.element_ty
    base = pid * BLOCK + tl.arange(0, EIGHTH)
    if EVEN:
        # n is a multiple of BLOCK: every store is in bounds, no mask needed.
        tl.store(out_ptr + base, tl.exp2((mean + sa) * _LOG2E).to(dt))
        tl.store(out_ptr + base + EIGHTH, tl.exp2((mean - sa) * _LOG2E).to(dt))
        tl.store(out_ptr + base + 2 * EIGHTH, tl.exp2((mean + sb) * _LOG2E).to(dt))
        tl.store(out_ptr + base + 3 * EIGHTH, tl.exp2((mean - sb) * _LOG2E).to(dt))
        tl.store(out_ptr + base + 4 * EIGHTH, tl.exp2((mean + sc) * _LOG2E).to(dt))
        tl.store(out_ptr + base + 5 * EIGHTH, tl.exp2((mean - sc) * _LOG2E).to(dt))
        tl.store(out_ptr + base + 6 * EIGHTH, tl.exp2((mean + sd) * _LOG2E).to(dt))
        tl.store(out_ptr + base + 7 * EIGHTH, tl.exp2((mean - sd) * _LOG2E).to(dt))
    else:
        tl.store(
            out_ptr + base, tl.exp2((mean + sa) * _LOG2E).to(dt), mask=base < n_elements
        )
        tl.store(
            out_ptr + base + EIGHTH,
            tl.exp2((mean - sa) * _LOG2E).to(dt),
            mask=base + EIGHTH < n_elements,
        )
        tl.store(
            out_ptr + base + 2 * EIGHTH,
            tl.exp2((mean + sb) * _LOG2E).to(dt),
            mask=base + 2 * EIGHTH < n_elements,
        )
        tl.store(
            out_ptr + base + 3 * EIGHTH,
            tl.exp2((mean - sb) * _LOG2E).to(dt),
            mask=base + 3 * EIGHTH < n_elements,
        )
        tl.store(
            out_ptr + base + 4 * EIGHTH,
            tl.exp2((mean + sc) * _LOG2E).to(dt),
            mask=base + 4 * EIGHTH < n_elements,
        )
        tl.store(
            out_ptr + base + 5 * EIGHTH,
            tl.exp2((mean - sc) * _LOG2E).to(dt),
            mask=base + 5 * EIGHTH < n_elements,
        )
        tl.store(
            out_ptr + base + 6 * EIGHTH,
            tl.exp2((mean + sd) * _LOG2E).to(dt),
            mask=base + 6 * EIGHTH < n_elements,
        )
        tl.store(
            out_ptr + base + 7 * EIGHTH,
            tl.exp2((mean - sd) * _LOG2E).to(dt),
            mask=base + 7 * EIGHTH < n_elements,
        )


def log_normal_(x, mean=1, std=2):
    n = x.numel()
    if n <= 262144:
        BLOCK = 1024
        grid = (triton.cdiv(n, BLOCK),)
        _log_normal_small_kernel[grid](
            x,
            n,
            float(mean),
            float(std),
            BLOCK=BLOCK,
            HALF=BLOCK // 2,
            SEED=0,
            EVEN=(n % BLOCK == 0),
        )
    else:
        BLOCK = 2048
        grid = (triton.cdiv(n, BLOCK),)
        _log_normal_big_kernel[grid](
            x,
            n,
            float(mean),
            float(std),
            BLOCK=BLOCK,
            EIGHTH=BLOCK // 8,
            N_ROUNDS=4,
            SEED=0,
            EVEN=(n % BLOCK == 0),
            num_warps=2,
        )
    return x
