# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)


def _prune_renorm_configs(configs, named_args, **kwargs):
    """Discard configurations that cannot cover a complete reduction row."""
    n = named_args["N"]
    return [config for config in configs if config.kwargs["BLOCK_SIZE"] >= n]


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("renorm_"),
    key=["N"],
    prune_configs_by={"early_config_prune": _prune_renorm_configs},
    restore_value=["X"],
)
@triton.jit(do_not_specialize=["p", "maxnorm"])
def renorm_kernel(X, N, p, maxnorm, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(0).to(tl.int64)

    offset = tl.arange(0, BLOCK_SIZE)
    mask = offset < N

    x = tl.load(X + pid * N + offset, mask=mask, other=0.0).to(tl.float32)
    _sum = tl.sum(tl_extra_shim.pow(tl.abs(x), p))

    norm = tl_extra_shim.pow(_sum, 1.0 / p)
    scale = tl.where(norm > maxnorm, maxnorm / norm, 1.0)

    x = x * scale
    tl.store(X + pid * N + offset, x, mask=mask)


def renorm_(x, p, dim, maxnorm):
    logger.debug("GEMS_SUNRISE RENORM")
    dim = dim % x.ndim

    perm = [dim] + [i for i in range(x.ndim) if i != dim]
    x_perm = x.permute(perm).contiguous()
    M = x_perm.shape[0]
    N = x_perm[0].numel()
    x_flat = x_perm.reshape(M, N)

    grid = (M,)
    with torch_device_fn.device(x.device):
        renorm_kernel[grid](x_flat, N, p, maxnorm)

    inv_perm = [0] * x.ndim
    for i, pi in enumerate(perm):
        inv_perm[pi] = i
    x.copy_(x_flat.reshape(x_perm.shape).permute(inv_perm))

    return x
