import logging

import torch
import triton
import triton.language as tl
from _kunlunxin.utils.codegen_config_utils import CodeGenConfig

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

from ..utils.pointwise_dynamic import pointwise_dynamic

_atan = tl_extra_shim.atan


logger = logging.getLogger(__name__)

# arctan is an alias of atan (out = atan(x)). Neither arctan nor arctan_ was
# overridden by kunlunxin, so both fell to the generic ops/arctan_.py bare
# `@pointwise_dynamic` (NO CodeGenConfig, default buffer_size_limit=2048, no
# XPU tuning) → discrete/launch-bound slow path. Baseline (IR
# ir-arctan-dev5.log / ir-arctan_-dev6.log): large shapes ~0.012-0.013
# ([1024,65536] gems ~155-158ms), all shapes 0.012-0.5.
# Fix: mirror the sibling unary op cos.py — same INT_TO_FLOAT promotion + tuned
# config_ (vec-OPEN + kunlunAutoGrid + unroll8) → contiguous block-DMA tiles.
config_ = CodeGenConfig(
    512,
    (65536, 65536, 65536),
    32,
    True,
    prefer_1d_tile=True,
    buffer_size_limit=4096,
    isCloseVectorization=False,
    kunlunAutoGrid=True,
    unroll_num=8,
)


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")], config=config_)
@triton.jit
def arctan_func(x):
    return _atan(x.to(tl.float32))


def arctan_(A):
    logger.debug("GEMS_KUNLUNXIN ARCTAN_")
    arctan_func(A, out0=A)
    return A


# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Generated by KernelGen: https://github.com/flagos-ai/KernelGen


@triton.jit
def _kg_arctan_kernel(A_ptr, Out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < n_elements
    x = tl.load(A_ptr + offs, mask=mask)
    xf = x.to(tl.float32)
    a = tl.abs(xf)
    # atan(a) = pi/4 + atan((a-1)/(a+1)), with (a-1)/(a+1) = 1 - 2/(a+1)
    t = 1.0 - 2.0 / (a + 1.0)
    u = t * t
    # y ~= atan(t) via odd Chebyshev polynomial t*P(t^2), max abs err ~2e-5 on [-1,1]
    p = 0.023286007733000002
    p = p * u + -0.09075201792469954
    p = p * u + 0.18446355750908477
    p = p * u + -0.3315446193087253
    p = p * u + 0.9999647984014695
    y = t * p + 0.7853981633974483
    y = tl.where(xf < 0.0, -y, y)
    tl.store(Out_ptr + offs, y.to(x.dtype), mask=mask)


_BLOCK = 8192
_NUM_WARPS = 8


def arctan(A):
    with torch_device_fn.device(A.device):
        A = A.contiguous()
        out = torch.empty_like(A)
        n = A.numel()
        if n > 0:
            grid = ((n + _BLOCK - 1) // _BLOCK,)
            _kg_arctan_kernel[grid](A, out, n, BLOCK=_BLOCK, num_warps=_NUM_WARPS)
        return out
