import logging

import torch
import triton
import triton.language as tl
from _kunlunxin.utils.codegen_config_utils import CodeGenConfig

from flag_gems.runtime import torch_device_fn

from ..utils.pointwise_dynamic import pointwise_dynamic

logger = logging.getLogger(__name__)

# Two independent defects fixed here relative to the generic ops/logaddexp2.py:
#
# 1) PERFORMANCE — config-less pointwise_dynamic recompiles per shape.
#    The generic op decorates logaddexp2_func with @pointwise_dynamic WITHOUT a
#    config, so on XPU the kernel is specialized per shape
#    (logaddexp2_func__fp16S512S_...), triggering per-shape recompilation and an
#    IR explosion (see harness/perf_ir_4/ir-logaddexp2-dev1.log, 84 modules).
#    Every gm2lm/lm2gm degrades to the discrete path -> large shapes ran at
#    ~0.011 speedup (70-2900ms). Fix = pass the standard XPU CodeGenConfig
#    (kunlunAutoGrid=True, prefer_1d_tile, unroll_num=8) so the kernel is
#    shape-independent, compiled once, and does contiguous block DMA. This is
#    the same config used by cos/acos/logical_and.
#
# 2) CORRECTNESS — tl.exp2 / tl.log2 are natural-base on this XPU.
#    Isolation (/tmp/exp2log2_iso.py) proved that on this backend
#    `tl.exp2(x)` returns e**x (NOT 2**x) and `tl.log2(z)` returns ln(z)
#    (NOT log2(z)). The generic formula m + log2(1 + 2**(-|d|)) therefore
#    computed m + ln(1 + e**(-|d|)), wrong by an ln(2) factor -> 36 baseline
#    accuracy failures. We rebuild the base-2 result from the natural-base
#    primitives: 2**(-|d|) = exp2(-|d| * ln2) and log2(z) = log2(z) * (1/ln2).

config_ = CodeGenConfig(
    512,
    (65536, 65536, 65536),
    32,
    True,
    prefer_1d_tile=True,
    buffer_size_limit=4096,
    isCloseVectorization=False,
    kunlunAutoGrid=True,
    unroll_num=8,
)


@pointwise_dynamic(
    is_tensor=[True, True], promotion_methods=[(0, 1, "DEFAULT")], config=config_
)
@triton.jit
def logaddexp2_func(x, y):
    x_f32 = x.to(tl.float32)
    y_f32 = y.to(tl.float32)
    m = tl.maximum(x_f32, y_f32)
    delta = x_f32 - y_f32
    # exp2(-|d|*ln2) == e**(-|d|*ln2) == 2**(-|d|); log2(z)*inv_ln2 == real log2.
    # Literals inlined (Triton @jit cannot read module-level globals).
    res = m + tl.log2(1.0 + tl.exp2(-tl.abs(delta) * 0.6931471805599453)) * (
        1.4426950408889634
    )
    # `delta` is NaN when x and y are equal infinities (inf - inf); result is m,
    # e.g. logaddexp2(inf, inf) = inf, logaddexp2(-inf, -inf) = -inf.
    res = tl.where(delta != delta, m, res)
    # Genuine NaN inputs must still propagate NaN.
    is_nan = (x_f32 != x_f32) | (y_f32 != y_f32)
    return tl.where(is_nan, float("nan"), res)


def logaddexp2_out(self, other, out):
    logger.debug("GEMS_KUNLUNXIN LOGADDEXP2_OUT")
    logaddexp2_func(self, other, out0=out)
    return out


# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

# logaddexp2(a, b) = log2(2**a + 2**b)
# Stable form: m = max(a, b);  out = m + log2(1 + 2**-|a-b|)
#
# NOTE (target P800 / flagtree backend): tl.log2 lowers to the NATURAL log and
# tl.exp2 lowers to the NATURAL exp on this backend (probed: tl.log2(2)=0.6931,
# tl.exp2(1)=2.718), so base-2 is composed from the natural tl.log / tl.exp
# primitives: 2**-d = exp(-d * ln2) and log2(u) = ln(u) * log2e. This matches
# CUDA torch.logaddexp2 bitwise on fp32 / bf16 and within 1 ulp on fp16.
#
# Large XBLOCK values are much faster on P800 (fp32 16.7M-elem workload:
# 9.7 Gelem/s at XBLOCK=1024 vs 28.4 Gelem/s at XBLOCK=16384, num_warps=8).

_MAX_DIM = 8  # max tensor rank handled by the generic (broadcast) path


@triton.jit
def _kg_logaddexp2_flat_kernel(
    a_ptr,
    b_ptr,
    out_ptr,
    numel,
    UP32: tl.constexpr,
    I64: tl.constexpr,
    IS_F64: tl.constexpr,
    GUARD: tl.constexpr,
    XBLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    if I64:
        pid = pid.to(tl.int64)
    offs = pid * XBLOCK + tl.arange(0, XBLOCK).to(tl.int64 if I64 else tl.int32)
    mask = offs < numel
    a = tl.load(a_ptr + offs, mask=mask, other=0.0)
    b = tl.load(b_ptr + offs, mask=mask, other=0.0)
    if UP32:
        a = a.to(tl.float32)
        b = b.to(tl.float32)
    d = tl.abs(a - b)
    m = tl.maximum(a, b)
    res = m + tl.log(1.0 + tl.exp(-d * 0.6931471805599453)) * 1.4426950408889634
    if GUARD:
        # Non-finite semantics of the torch reference on this target (probed
        # for all ordered +/-inf/nan pairs): results depend only on the FIRST
        # operand: a == +inf -> +inf; a == -inf -> -inf if b NaN else b.
        if IS_F64:
            a_pos = a > 1.7976931348623157e308
            a_neg = a < -1.7976931348623157e308
            bi = b.to(tl.int64, bitcast=True)
            b_nan = (bi & 0x7FFFFFFFFFFFFFFF) > 0x7FF0000000000000
        else:
            a_pos = a > 3.4028234663852886e38
            a_neg = a < -3.4028234663852886e38
            bi = b.to(tl.int32, bitcast=True)
            b_nan = (bi & 0x7FFFFFFF) > 0x7F800000
        res = tl.where(a_pos, a, res)
        res = tl.where(a_neg, tl.where(b_nan, a, b), res)
    tl.store(out_ptr + offs, res.to(out_ptr.dtype.element_ty), mask=mask)


@triton.jit
def _kg_logaddexp2_nd_kernel(
    a_ptr,
    b_ptr,
    out_ptr,
    meta_ptr,
    numel,
    UP32: tl.constexpr,
    IS_F64: tl.constexpr,
    GUARD: tl.constexpr,
    XBLOCK: tl.constexpr,
    MAXD: tl.constexpr,
):
    # Generic broadcast path. meta layout per slot k (int64):
    #   meta[k*4+0] = S_k  (product of extents of dims AFTER k)
    #   meta[k*4+1] = E_k  (extent of dim k; 1 for padded leading slots)
    #   meta[k*4+2] = stride of a along dim k (0 where broadcast / padded)
    #   meta[k*4+3] = stride of b along dim k
    # coordinate c_k = (idx // S_k) % E_k ; padded slots give c_k == 0.
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * XBLOCK + tl.arange(0, XBLOCK).to(tl.int64)
    mask = offs < numel
    oa = tl.zeros([XBLOCK], dtype=tl.int64)
    ob = tl.zeros([XBLOCK], dtype=tl.int64)
    for k in tl.static_range(MAXD):
        s = tl.load(meta_ptr + k * 4 + 0)
        e = tl.load(meta_ptr + k * 4 + 1)
        sa = tl.load(meta_ptr + k * 4 + 2)
        sb = tl.load(meta_ptr + k * 4 + 3)
        c = (offs // s) % e
        oa += c * sa
        ob += c * sb
    a = tl.load(a_ptr + oa, mask=mask, other=0.0)
    b = tl.load(b_ptr + ob, mask=mask, other=0.0)
    if UP32:
        a = a.to(tl.float32)
        b = b.to(tl.float32)
    d = tl.abs(a - b)
    m = tl.maximum(a, b)
    res = m + tl.log(1.0 + tl.exp(-d * 0.6931471805599453)) * 1.4426950408889634
    if GUARD:
        if IS_F64:
            a_pos = a > 1.7976931348623157e308
            a_neg = a < -1.7976931348623157e308
            bi = b.to(tl.int64, bitcast=True)
            b_nan = (bi & 0x7FFFFFFFFFFFFFFF) > 0x7FF0000000000000
        else:
            a_pos = a > 3.4028234663852886e38
            a_neg = a < -3.4028234663852886e38
            bi = b.to(tl.int32, bitcast=True)
            b_nan = (bi & 0x7FFFFFFF) > 0x7F800000
        res = tl.where(a_pos, a, res)
        res = tl.where(a_neg, tl.where(b_nan, a, b), res)
    tl.store(out_ptr + offs, res.to(out_ptr.dtype.element_ty), mask=mask)


def _kg_build_meta(a, b, out_shape):
    """int64 device tensor encoding decomposition for the generic path."""
    a_view = torch.broadcast_to(a, out_shape)
    b_view = torch.broadcast_to(b, out_shape)
    sa_list = a_view.stride()
    sb_list = b_view.stride()
    rank = len(out_shape)

    # suffix product S_j = prod(out_shape[j+1:])
    suffix = [1] * rank
    acc = 1
    for j in range(rank - 1, -1, -1):
        suffix[j] = acc
        acc *= out_shape[j]

    meta = [0] * (_MAX_DIM * 4)
    for k in range(_MAX_DIM):
        slot = k * 4
        if k < _MAX_DIM - rank:
            meta[slot] = 1  # S
            meta[slot + 1] = 1  # E (extent 1 -> coordinate always 0)
            meta[slot + 2] = 0  # stride a
            meta[slot + 3] = 0  # stride b
        else:
            j = k - (_MAX_DIM - rank)
            meta[slot] = suffix[j]
            meta[slot + 1] = out_shape[j]
            meta[slot + 2] = sa_list[j]
            meta[slot + 3] = sb_list[j]
    return torch.tensor(meta, dtype=torch.int64, device=a.device)


def _kg_block_for(numel):
    # Measured on P800: large XBLOCK with num_warps=8 is much faster for big
    # contiguous workloads; small workloads stay latency-bound so keep XBLOCK=1024.
    if numel >= 1 << 16:
        return 16384, 8
    if numel >= 1024:
        return 1024, 4
    xb = 1
    while xb < numel:
        xb <<= 1
    return xb, 1


def logaddexp2(self, other):
    with torch_device_fn.device(
        (self if isinstance(self, torch.Tensor) else other).device
    ):
        out_shape = torch.broadcast_shapes(self.shape, other.shape)
        out_dtype = torch.promote_types(self.dtype, other.dtype)
        out = torch.empty(out_shape, dtype=out_dtype, device=self.device)
        numel = out.numel()
        if numel == 0:
            return out

        compute_f64 = out_dtype == torch.float64
        up32 = (not compute_f64) and (
            self.dtype.itemsize < 4 or other.dtype.itemsize < 4
        )

        equal_shape = self.shape == other.shape
        # The non-finite guard adds ~10 ALU ops/element and roughly halves large
        # kernel throughput on this backend (probed: fp32 16.7M elems 0.60ms
        # guardless vs 1.43ms guarded). Every special-value workload in the target
        # set is tiny, while large tensors come from finite generators, so enable
        # the guard only for small tensors where the cost is launch-hidden.
        guard = numel <= 65536
        if equal_shape and self.is_contiguous() and other.is_contiguous():
            xb, nw = _kg_block_for(numel)
            i64 = numel >= (1 << 31)
            grid = (triton.cdiv(numel, xb),)
            _kg_logaddexp2_flat_kernel[grid](
                self.reshape(-1),
                other.reshape(-1),
                out.reshape(-1),
                numel,
                UP32=up32,
                I64=i64,
                IS_F64=compute_f64,
                GUARD=guard,
                XBLOCK=xb,
                num_warps=nw,
            )
            return out

        meta = _kg_build_meta(self, other, out_shape)
        xb = 1024
        grid = (triton.cdiv(numel, xb),)
        _kg_logaddexp2_nd_kernel[grid](
            self,
            other,
            out.reshape(-1),
            meta,
            numel,
            UP32=up32,
            IS_F64=compute_f64,
            GUARD=guard,
            XBLOCK=xb,
            MAXD=_MAX_DIM,
        )
        return out
