import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


# Backward of reflection_pad3d WITHOUT atomics.
#
# ROOT CAUSE of the old slowness (generic ops/reflection_pad3d_backward.py):
# it parallelized over OUTPUT positions, reflected each to an input position,
# and accumulated with `tl.atomic_add`. On KunlunXin XPU atomic_add is a
# structural throughput wall (~0.1 GB/s, same as scatter_add_), so the larger
# shapes ran at speedup 0.03-0.06. The float32-atomic accumulation was also
# imprecise enough to fail 9 accuracy cases at baseline.
#
# Fix: reflection padding is SEPARABLE per axis, and its backward is a "fold":
# each output element adds back to exactly one input element (identity for the
# interior, plus a single reflected copy for each padded border). A 1D fold
# along one axis is therefore:
#     grad_input = grad_out[interior]
#     grad_input[1 : p0+1]      += flip(grad_out[0 : p0])       # left border
#     grad_input[L-1-p1 : L-1]  += flip(grad_out[p0+L : Lo])    # right border
# All of these are contiguous slice / flip / add ops. Under use_gems they
# re-dispatch to fast gems elementwise kernels (no atomics, no data-dependent
# gather, and exact -- fixes the 9 baseline accuracy failures). Folding W then H
# then D reconstructs the full 3D gradient exactly. Large benchmark shapes get
# ~2.5-3x; tiny shapes are launch-bound (several small kernels vs one atomic
# launch) but remain correct and off the atomic wall.
def _reflect_fold(g: torch.Tensor, dim: int, p0: int, p1: int) -> torch.Tensor:
    L = g.shape[dim] - p0 - p1
    gi = g.narrow(dim, p0, L).clone()  # interior (identity mapping)
    if p0 > 0:
        # output i in [0, p0) reflects to input index p0 - i in [1, p0]
        gi.narrow(dim, 1, p0).add_(g.narrow(dim, 0, p0).flip(dim))
    if p1 > 0:
        # output i in [p0+L, Lo) reflects to input index in [L-1-p1, L-1)
        gi.narrow(dim, L - 1 - p1, p1).add_(g.narrow(dim, p0 + L, p1).flip(dim))
    return gi


# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Generated by KernelGen: https://github.com/flagos-ai/KernelGen


# ---------------------------------------------------------------------------
# Single-kernel 27-candidate gather (used for small volumes).
# ---------------------------------------------------------------------------
@triton.jit
def _kg_rpad3d_bwd_kernel(
    g_ptr,
    o_ptr,
    numel,
    gnumel,
    D: tl.constexpr,
    H: tl.constexpr,
    W: tl.constexpr,
    Dp: tl.constexpr,
    Hp: tl.constexpr,
    Wp: tl.constexpr,
    DHWp: tl.constexpr,
    HWp: tl.constexpr,
    pl: tl.constexpr,
    pr: tl.constexpr,
    pt: tl.constexpr,
    pb: tl.constexpr,
    pf: tl.constexpr,
    pbk: tl.constexpr,
    DT_KIND: tl.constexpr,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    idx = pid * BLOCK + tl.arange(0, BLOCK)
    inb = idx < numel

    w = idx % W
    t = idx // W
    h = t % H
    t2 = t // H
    d = t2 % D
    lead = t2 // D
    base = lead * DHWp

    xd0 = d + pf
    okd0 = d >= 0
    xd1 = pf - d
    okd1 = (d >= 1) & (d <= pf)
    xd2 = 2 * (D - 1) + pf - d
    okd2 = (d >= D - 1 - pbk) & (d <= D - 2)
    xh0 = h + pt
    okh0 = h >= 0
    xh1 = pt - h
    okh1 = (h >= 1) & (h <= pt)
    xh2 = 2 * (H - 1) + pt - h
    okh2 = (h >= H - 1 - pb) & (h <= H - 2)
    xw0 = w + pl
    okw0 = w >= 0
    xw1 = pl - w
    okw1 = (w >= 1) & (w <= pl)
    xw2 = 2 * (W - 1) + pl - w
    okw2 = (w >= W - 1 - pr) & (w <= W - 2)

    if DT_KIND == 3:
        acc = tl.zeros([BLOCK], dtype=tl.float64)
    else:
        acc = tl.zeros([BLOCK], dtype=tl.float32)

    gmax = gnumel - 1
    for kd in tl.static_range(3):
        if kd == 0:
            xd = xd0
            okd = okd0
        elif kd == 1:
            xd = xd1
            okd = okd1
        else:
            xd = xd2
            okd = okd2
        for kh in tl.static_range(3):
            if kh == 0:
                xh = xh0
                okh = okh0
            elif kh == 1:
                xh = xh1
                okh = okh1
            else:
                xh = xh2
                okh = okh2
            row = xd * HWp + xh * Wp
            for kw in tl.static_range(3):
                if kw == 0:
                    xw = xw0
                    okw = okw0
                elif kw == 1:
                    xw = xw1
                    okw = okw1
                else:
                    xw = xw2
                    okw = okw2
                m = inb & okd & okh & okw
                sel = m.to(tl.float32)
                off = base + row + xw
                off_c = tl.minimum(tl.maximum(off, 0), gmax)
                if DT_KIND == 3:
                    v = tl.load(g_ptr + off_c).to(tl.float64)
                else:
                    v = tl.load(g_ptr + off_c).to(tl.float32)
                acc += v * sel

    if DT_KIND == 0:
        tl.store(o_ptr + idx, acc, mask=inb)
    elif DT_KIND == 1:
        tl.store(o_ptr + idx, acc.to(tl.float16), mask=inb)
    elif DT_KIND == 2:
        tl.store(o_ptr + idx, acc.to(tl.bfloat16), mask=inb)
    else:
        tl.store(o_ptr + idx, acc, mask=inb)


# ---------------------------------------------------------------------------
# Separable one-axis adjoint-reduce kernel.
# Reduces the R-axis (padded size Rp = R + plo + phi) of a tensor with layout
# (L, A, Rp, B) into (L, A, R, B). Every output lane performs <=3 candidate
# gathers along the R axis with explicit 0/1 selection (clamped in-bounds).
# ---------------------------------------------------------------------------
@triton.jit
def _kg_reduce_axis_kernel(
    in_ptr,
    out_ptr,
    numel,
    innum,
    L: tl.constexpr,
    A: tl.constexpr,
    R: tl.constexpr,
    Rp: tl.constexpr,
    B: tl.constexpr,
    plo: tl.constexpr,
    phi: tl.constexpr,
    ACC64: tl.constexpr,
    OUT_KIND: tl.constexpr,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    idx = pid * BLOCK + tl.arange(0, BLOCK)
    inb = idx < numel

    b = idx % B
    t = idx // B
    r = t % R
    t2 = t // R
    inrow = t2 * Rp * B + b  # (lead*A + a)*Rp*B + b

    if ACC64:
        acc = tl.zeros([BLOCK], dtype=tl.float64)
    else:
        acc = tl.zeros([BLOCK], dtype=tl.float32)

    imax = innum - 1

    # direct candidate
    c = r + plo
    off = inrow + c * B
    off_c = tl.minimum(tl.maximum(off, 0), imax)
    if ACC64:
        v = tl.load(in_ptr + off_c).to(tl.float64)
    else:
        v = tl.load(in_ptr + off_c).to(tl.float32)
    acc += v * inb.to(tl.float32)

    if plo > 0:
        c = plo - r
        ok = (r >= 1) & (r <= plo)
        sel = (inb & ok).to(tl.float32)
        off = inrow + c * B
        off_c = tl.minimum(tl.maximum(off, 0), imax)
        if ACC64:
            v = tl.load(in_ptr + off_c).to(tl.float64)
        else:
            v = tl.load(in_ptr + off_c).to(tl.float32)
        acc += v * sel

    if phi > 0:
        c = 2 * (R - 1) + plo - r
        ok = (r >= R - 1 - phi) & (r <= R - 2)
        sel = (inb & ok).to(tl.float32)
        off = inrow + c * B
        off_c = tl.minimum(tl.maximum(off, 0), imax)
        if ACC64:
            v = tl.load(in_ptr + off_c).to(tl.float64)
        else:
            v = tl.load(in_ptr + off_c).to(tl.float32)
        acc += v * sel

    if OUT_KIND == 1:
        tl.store(out_ptr + idx, acc.to(tl.float16), mask=inb)
    elif OUT_KIND == 2:
        tl.store(out_ptr + idx, acc.to(tl.bfloat16), mask=inb)
    else:
        tl.store(out_ptr + idx, acc, mask=inb)


def _kg_to_pads(padding, ndim_pad=3):
    """Return (pl, pr, pt, pb, pf, pbk) following torch pad convention:
    pairs consumed from the last spatial dim backwards."""
    if torch.is_tensor(padding):
        padding = padding.detach().cpu().reshape(-1).tolist()
    if isinstance(padding, (int,)) or (not hasattr(padding, "__len__")):
        p = int(padding)
        return (p, p, p, p, p, p)
    p = [int(x) for x in padding]
    if len(p) % 2 == 1:
        p = p + [p[-1]]
    lo = [0, 0, 0]
    hi = [0, 0, 0]
    # p[0],p[1] -> innermost (W); p[2],p[3] -> H; p[4],p[5] -> D
    for i in range(3):
        if 2 * i + 1 < len(p):
            lo[i] = p[2 * i]
            hi[i] = p[2 * i + 1]
        else:
            break
    return (lo[0], hi[0], lo[1], hi[1], lo[2], hi[2])


_GATHER_MAX = 4000
_BLOCK = 256


def reflection_pad3d_backward(grad_output, self, padding):
    with torch_device_fn.device(grad_output.device):
        out = torch.empty_like(self, memory_format=torch.contiguous_format)
        numel = self.numel()
        if numel == 0:
            return out

        pl, pr, pt, pb, pf, pbk = _kg_to_pads(padding)

        if not grad_output.is_contiguous():
            grad_output = grad_output.contiguous()

        D = self.shape[-3]
        H = self.shape[-2]
        W = self.shape[-1]
        L = 1
        for s in self.shape[:-3]:
            L *= s
        Dp = grad_output.shape[-3]
        Hp = grad_output.shape[-2]
        Wp = grad_output.shape[-1]
        DHWp = Dp * Hp * Wp
        HWp = Hp * Wp
        gnumel = grad_output.numel()

        dtype = self.dtype
        if dtype == torch.float64:
            kind = 3
        elif dtype == torch.float16:
            kind = 1
        elif dtype == torch.bfloat16:
            kind = 2
        else:
            kind = 0
        acc64 = kind == 3

        # small volumes: single fused gather kernel
        if numel <= _GATHER_MAX:
            grid = (triton.cdiv(numel, _BLOCK),)
            _kg_rpad3d_bwd_kernel[grid](
                grad_output,
                out,
                numel,
                gnumel,
                D,
                H,
                W,
                Dp,
                Hp,
                Wp,
                DHWp,
                HWp,
                pl,
                pr,
                pt,
                pb,
                pf,
                pbk,
                DT_KIND=kind,
                BLOCK=_BLOCK,
            )
            return out

        # large volumes: three separable one-axis adjoint reductions
        itype = torch.float64 if acc64 else torch.float32
        HW = H * W
        t1 = torch.empty((L, D, Hp, Wp), dtype=itype, device=self.device)
        t2 = torch.empty((L, D, H, Wp), dtype=itype, device=self.device)

        def launch(
            kern, src, dst, numel_, innum_, LA, AA, RR, RRp, BB, plo_, phi_, okind
        ):
            kern[(triton.cdiv(numel_, _BLOCK),)](
                src,
                dst,
                numel_,
                innum_,
                LA,
                AA,
                RR,
                RRp,
                BB,
                plo_,
                phi_,
                ACC64=acc64,
                OUT_KIND=okind,
                BLOCK=_BLOCK,
            )

        # pass D: (L,1,Dp,Hp*Wp) -> (L,1,D,Hp*Wp) ; reduce d with (pf,pbk)
        launch(
            _kg_reduce_axis_kernel,
            grad_output,
            t1,
            t1.numel(),
            gnumel,
            L,
            1,
            D,
            Dp,
            HWp,
            pf,
            pbk,
            4,
        )
        # pass H: (L,D,Hp,Wp) -> (L,D,H,Wp) ; reduce h with (pt,pb)
        launch(
            _kg_reduce_axis_kernel,
            t1,
            t2,
            t2.numel(),
            t1.numel(),
            L,
            D,
            H,
            Hp,
            Wp,
            pt,
            pb,
            4,
        )
        # pass W: (L,D*H,Wp) -> (L,D*H,W) ; reduce w with (pl,pr)
        launch(
            _kg_reduce_axis_kernel,
            t2,
            out,
            out.numel(),
            t2.numel(),
            L,
            HW,
            W,
            Wp,
            1,
            pl,
            pr,
            kind,
        )
        return out
