# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import torch
import triton
import triton.language as tl

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
from flag_gems.runtime import torch_device_fn

# ---------------------------------------------------------------
# erfc(x):  a = |x|,  erfc(a) = exp(-a^2) * H(a)   for all a >= 0
# where H(a) = exp(a^2)*erfc(a) is smooth on [0,6] (H(0)=1, H(6)~0.0925,
# and beyond a=6 we clamp the Chebyshev variable, which makes H ~ H(6),
# an error far below fp32 resolution because exp(-a^2) is < 2.3e-16).
# H is evaluated as a degree-20 polynomial in t = (a-3)/3 in [-1,1]
# (power basis in t is well conditioned: max |coef| ~ 0.18).
# For x < 0: erfc(x) = 2 - erfc(|x|).
# ---------------------------------------------------------------

# power-in-t coefficients (ascending) of H on a in [0,6], t = a/3 - 1
_H20 = tl.constexpr(
    (
        0.1790011516691247,
        -0.16311676439598335,
        0.142959234233621,
        -0.12094576392652408,
        0.09907000615225842,
        -0.07873867784489968,
        0.060856570726695564,
        -0.04613396611269287,
        0.03416091722982865,
        -0.023064567379271463,
        0.015410210816184815,
        -0.015572842429004398,
        0.012335451010999914,
        0.002060941501742229,
        -0.003821600393456328,
        -0.010922514418088867,
        0.00894274506524725,
        0.005136085543813087,
        -0.004085977936425198,
        -0.0023136457126464874,
        0.0015595753249897683,
    )
)


@triton.jit
def _erfc_core(x):
    a = tl.abs(x)
    y = a * a
    e = tl.exp(-y)
    t = a * (1.0 / 3.0) - 1.0
    t = tl.minimum(t, 1.0)
    h = 0.0
    for j in tl.static_range(0, 21):
        h = h * t + _H20[20 - j]
    r = e * h
    return tl.where(x < 0.0, 2.0 - r, r)


@triton.jit
def _erfc_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    BLOCK: tl.constexpr,
    IS_F16: tl.constexpr,
    IS_BF16: tl.constexpr,
):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < n_elements
    x = tl.load(x_ptr + offs, mask=mask)
    if IS_F16 or IS_BF16:
        x = x.to(tl.float32)
    res = _erfc_core(x)
    if IS_F16:
        res = res.to(tl.float16)
    elif IS_BF16:
        res = res.to(tl.bfloat16)
    tl.store(out_ptr + offs, res, mask=mask)


@triton.jit
def _erfc_kernel_f64(x_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < n_elements
    x = tl.load(x_ptr + offs, mask=mask)
    res = _erfc_core(x)
    tl.store(out_ptr + offs, res, mask=mask)


def special_erfc(x):
    with torch_device_fn.device(x.device):
        if not x.is_contiguous():
            x = x.contiguous()
        out = torch.empty_like(x)
        n = x.numel()
        if n == 0:
            return out
        dt = x.dtype
        if n < 65536:
            if dt == torch.float16:
                BLOCK, WARPS = 2048, 4
            else:
                BLOCK, WARPS = 1024, 4
        elif dt in (torch.float16, torch.bfloat16):
            BLOCK, WARPS = 16384, 8
        else:
            BLOCK, WARPS = 8192, 8
        grid = (triton.cdiv(n, BLOCK),)
        if dt == torch.float64:
            _erfc_kernel_f64[grid](x, out, n, BLOCK=BLOCK, num_warps=WARPS)
        elif dt == torch.float16:
            _erfc_kernel[grid](
                x, out, n, BLOCK=BLOCK, IS_F16=True, IS_BF16=False, num_warps=WARPS
            )
        elif dt == torch.bfloat16:
            _erfc_kernel[grid](
                x, out, n, BLOCK=BLOCK, IS_F16=False, IS_BF16=True, num_warps=WARPS
            )
        else:
            _erfc_kernel[grid](
                x, out, n, BLOCK=BLOCK, IS_F16=False, IS_BF16=False, num_warps=WARPS
            )
        return out
