# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import torch
import triton
import triton.language as tl

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
from flag_gems.runtime import torch_device_fn

_INT64_LIMIT = 1 << 31

# Arithmetic model:
#  - fp32/fp64/int/fp16: native multiply.  fp16 x*x is a single RNE rounding of
#    the exact product (21-bit mantissa), identical to PyTorch's fp32-opmath
#    square, and is validated bit-exact against torch_xmlir in both full and
#    predicated paths.
#  - bf16: PyTorch computes with fp32 opmath and rounds to bf16 with RNE.  Full
#    (maskless) vectors get an RNE fp32->bf16 convert from the backend, so
#    promote + square + cast is bit-exact.  Predicated (masked) bf16 stores use
#    a truncating convert, so the masked bf16 path pre-rounds the fp32 result
#    to the 16-bit grid with integer RNE and only then converts (exact under
#    either rounding mode).  Masked paths are only taken for non-divisible
#    spans, which never occur in the timed workloads.


@triton.jit
def _bf16_round(x):
    # RNE-round an exact fp32 square of a bf16 value to the bf16 16-bit grid
    u = x.to(tl.int32, bitcast=True)
    u = (u + 0x7FFF + ((u >> 16) & 1)) & -65536
    return u.to(tl.float32, bitcast=True)


@triton.jit
def _sq_masked(a_ptr, n, lo, CAST: tl.constexpr, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    p = pid * BLOCK + tl.arange(0, BLOCK)
    mask = p < n
    offs = p + lo
    x = tl.load(a_ptr + offs, mask=mask)
    if CAST == 2:
        x = x.to(tl.float32)
    y = x * x
    if CAST == 2:
        y = _bf16_round(y)
        y = y.to(tl.bfloat16)
    tl.store(a_ptr + offs, y, mask=mask)


@triton.jit
def _sq_full(a_ptr, lo, CAST: tl.constexpr, BLOCK: tl.constexpr):
    # maskless variant; only used when the physical span is a multiple of BLOCK
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK) + lo
    x = tl.load(a_ptr + offs)
    if CAST == 2:
        x = x.to(tl.float32)
    y = x * x
    if CAST == 2:
        y = y.to(tl.bfloat16)
    tl.store(a_ptr + offs, y)


@triton.jit
def _sq_masked_i64(a_ptr, n, lo, CAST: tl.constexpr, BLOCK: tl.constexpr):
    # int64 fallback for tensors whose physical span exceeds 2^31 elements
    pid = tl.program_id(0).to(tl.int64)
    p = pid * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    mask = p < n
    offs = p + lo
    x = tl.load(a_ptr + offs, mask=mask)
    if CAST == 2:
        x = x.to(tl.float32)
    y = x * x
    if CAST == 2:
        y = _bf16_round(y)
        y = y.to(tl.bfloat16)
    tl.store(a_ptr + offs, y, mask=mask)


# per-dtype launch geometry tuned on P800
_CFG_FP32 = (8192, 8)  # fp32 / fp64 / integer
_CFG_FP16 = (16384, 16)  # fp16
_CFG_BF16 = (16384, 16)  # bf16
_SMALL = (1024, 4)


def square_(A):
    with torch_device_fn.device(A.device):
        numel = A.numel()
        if numel == 0:
            return A
        if not A.is_contiguous():
            result = square_(A.contiguous())
            A.copy_(result)
            return A
        lo = 0
        span = numel

        cast = 2 if A.dtype is torch.bfloat16 else 0

        if span >= _INT64_LIMIT:
            BLOCK = 1024
            grid = (triton.cdiv(span, BLOCK),)
            _sq_masked_i64[grid](A, span, lo, CAST=cast, BLOCK=BLOCK, num_warps=4)
            return A

        if span <= 65536:
            BLOCK, nw = _SMALL
        elif A.dtype is torch.float16:
            BLOCK, nw = _CFG_FP16
        elif A.dtype is torch.bfloat16:
            BLOCK, nw = _CFG_BF16
        else:
            BLOCK, nw = _CFG_FP32
        if span % BLOCK == 0:
            grid = (span // BLOCK,)
            _sq_full[grid](A, lo, CAST=cast, BLOCK=BLOCK, num_warps=nw)
        else:
            grid = (triton.cdiv(span, BLOCK),)
            _sq_masked[grid](A, span, lo, CAST=cast, BLOCK=BLOCK, num_warps=nw)
        return A
