# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import torch
import triton
import triton.language as tl

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
from flag_gems.runtime import torch_device_fn

_INT32_MAX = 2**31 - 1
_B8 = 65536  # int64 lanes per program (8 bytes each => 512 KiB/program)
_BE = 1024  # elementwise fallback block


@triton.jit
def _copy_i64_exact(x_ptr, y_ptr, BLOCK: tl.constexpr, I64: tl.constexpr):
    pid = tl.program_id(0)
    if I64:
        pid = pid.to(tl.int64)
        ar = tl.arange(0, BLOCK).to(tl.int64)
    else:
        ar = tl.arange(0, BLOCK)
    offs = pid * BLOCK + ar
    v = tl.load(x_ptr + offs)
    tl.store(y_ptr + offs, v)


@triton.jit
def _copy_i64_masked(x_ptr, y_ptr, n, BLOCK: tl.constexpr, I64: tl.constexpr):
    pid = tl.program_id(0)
    if I64:
        pid = pid.to(tl.int64)
        ar = tl.arange(0, BLOCK).to(tl.int64)
    else:
        ar = tl.arange(0, BLOCK)
    offs = pid * BLOCK + ar
    mask = offs < n
    v = tl.load(x_ptr + offs, mask=mask)
    tl.store(y_ptr + offs, v, mask=mask)


@triton.jit
def _copy_elem(x_ptr, y_ptr, n, BLOCK: tl.constexpr):
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    mask = offs < n
    v = tl.load(x_ptr + offs, mask=mask)
    tl.store(y_ptr + offs, v, mask=mask)


@triton.jit
def _squeeze_copy_strided(
    x_ptr,
    out_ptr,
    n_elements,
    sizes_ptr,
    strides_ptr,
    rank: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Generic fallback for non-contiguous inputs: out is contiguous over the
    kept dims; map each output flat index to the matching offset in the strided
    input. sizes/strides hold kept-dim sizes and the input strides of the
    corresponding kept input dims, in output-dim order."""
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE).to(tl.int64)
    mask = offs < n_elements
    rem = offs
    acc = tl.zeros([BLOCK_SIZE], dtype=tl.int64)
    for d in tl.static_range(rank):
        d_rev = rank - 1 - d
        k = tl.load(sizes_ptr + d_rev)
        s = tl.load(strides_ptr + d_rev)
        c = rem % k
        acc += c * s
        rem = rem // k
    vals = tl.load(x_ptr + acc, mask=mask)
    tl.store(out_ptr + offs, vals, mask=mask)


def squeeze_copy(x):
    with torch_device_fn.device(x.device):
        out_shape = tuple(d for d in x.shape if d != 1)
        n = x.numel()
        out = torch.empty(out_shape, dtype=x.dtype, device=x.device)
        if n == 0:
            return out
        if x.is_contiguous():
            e = x.element_size()
            nbytes = n * e
            # Fast path: reinterpret as int64 (8-byte) lanes. Only for element
            # sizes 2/4 where this is a widening bitcast supported on the target.
            if (e == 2 or e == 4) and nbytes % 8 == 0 and x.data_ptr() % 8 == 0:
                lanes = nbytes // 8
                xw = x.reshape(-1).view(torch.int64)
                ow = out.reshape(-1).view(torch.int64)
                i64 = lanes > _INT32_MAX
                if lanes % _B8 == 0:
                    _copy_i64_exact[(lanes // _B8,)](
                        xw, ow, BLOCK=_B8, I64=i64, num_warps=4
                    )
                else:
                    _copy_i64_masked[(triton.cdiv(lanes, _B8),)](
                        xw, ow, lanes, BLOCK=_B8, I64=i64, num_warps=4
                    )
                return out
            # Generic elementwise copy in the original dtype.
            _copy_elem[(triton.cdiv(n, _BE),)](x, out, n, BLOCK=_BE, num_warps=4)
            return out
        # Strided (non-contiguous) input: full logical mapping in a Triton kernel.
        kept_indices = [i for i, d in enumerate(x.shape) if d != 1]
        sizes = torch.tensor(
            [x.shape[i] for i in kept_indices], dtype=torch.int64, device=x.device
        )
        strides = torch.tensor(
            [x.stride(i) for i in kept_indices], dtype=torch.int64, device=x.device
        )
        rank = len(kept_indices)
        _squeeze_copy_strided[(triton.cdiv(n, _BE),)](
            x, out, n, sizes, strides, rank=rank, BLOCK_SIZE=_BE, num_warps=4
        )
        return out
