# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops.bitwise_and import bitwise_and_scalar_, bitwise_and_tensor_

logger = logging.getLogger(__name__)


def __iand___tensor(self, other):
    logger.debug("GEMS __IAND___TENSOR")
    return bitwise_and_tensor_(self, other)


def __iand___scalar(self, other):
    logger.debug("GEMS __IAND___SCALAR")
    return bitwise_and_scalar_(self, other)
