# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def xor_func(x, y):
    return x ^ y


def xor(A, B):
    logger.debug("GEMS XOR")
    return xor_func(A, B)


def xor_(A, B):
    logger.debug("GEMS XOR_")
    return xor_func(A, B, out0=A)


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def xor_func_scalar(x, y):
    return x ^ y


def xor_scalar(A, B):
    logger.debug("GEMS XOR_SCALAR")
    return xor_func_scalar(A, B)


def xor_scalar_(A, B):
    logger.debug("GEMS XOR_SCALAR_")
    return xor_func_scalar(A, B, out0=A)


def xor_scalar_tensor(A, B):
    logger.debug("GEMS XOR_SCALAR_TENSOR")
    return xor_func_scalar(B, A)
