# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _slogdet_kernel(
    A_input,
    sign_out,
    logabsdet_out,
    LU_out,
    n,
    M,
    stride_a,
    stride_sign,
    stride_logabsdet,
    stride_lu,
    BLOCK_SIZE: tl.constexpr,
):
    """LU with partial pivoting for one square matrix, held in registers.

    One program per matrix. The whole ``BLOCK_SIZE x BLOCK_SIZE`` tile lives in
    registers, so the elimination inner loop is vectorized instead of issuing
    one load/store per element. ``A_input`` is a scratch copy and is overwritten
    with the factorization.
    """
    pid = tle.program_id(0)

    rows = tl.arange(0, BLOCK_SIZE)
    cols = tl.arange(0, BLOCK_SIZE)
    offsets = rows[:, None] * stride_a + cols[None, :]
    load_mask = (rows[:, None] < n) & (cols[None, :] < n)
    work = tl.load(A_input + pid * M * stride_a + offsets, mask=load_mask, other=0.0)

    swap_count = tl.zeros((), dtype=tl.int32)

    for k in range(0, n):
        # pivot: index of the largest |value| in column k at or below the
        # diagonal. Rows above k (already eliminated) are excluded.
        col_k = tl.sum(tl.where(cols[None, :] == k, work, 0.0), axis=1)
        abs_col = tl.abs(col_k)
        abs_col = tl.where((rows < k) | (rows >= n), -1.0, abs_col)
        pivot_val = tl.max(abs_col, axis=0)
        pivot_row = tl.min(tl.where(abs_col == pivot_val, rows, BLOCK_SIZE), axis=0)

        # swap row k with the pivot row
        row_k = tl.sum(tl.where(rows[:, None] == k, work, 0.0), axis=0)
        row_p = tl.sum(tl.where(rows[:, None] == pivot_row, work, 0.0), axis=0)
        work = tl.where(rows[:, None] == k, row_p[None, :], work)
        work = tl.where(rows[:, None] == pivot_row, row_k[None, :], work)
        swap_count = tl.where(pivot_row != k, swap_count + 1, swap_count)

        # eliminate below the pivot. A zero pivot leaves the trailing submatrix
        # untouched; the zero diagonal is detected after the loop.
        col_k = tl.sum(tl.where(cols[None, :] == k, work, 0.0), axis=1)
        pivot = tl.sum(tl.where(rows == k, col_k, 0.0), axis=0)
        safe_pivot = tl.where(pivot == 0.0, 1.0, pivot)
        multipliers = tl.where(rows > k, col_k / safe_pivot, 0.0)
        u_row = row_p
        update_mask = (rows[:, None] > k) & (cols[None, :] > k)
        work = tl.where(update_mask, work - multipliers[:, None] * u_row[None, :], work)

    # store the factorization in the caller's LU buffer
    store_mask = (rows[:, None] < n) & (cols[None, :] < n)
    tl.store(LU_out + pid * M * stride_lu + offsets, work, mask=store_mask)

    # sign / logabsdet from the diagonal. Only an exactly zero diagonal entry
    # means a singular matrix: comparing against a fixed epsilon would call
    # diag([1e-11, 1]) singular while ATen returns a finite logabsdet for it.
    diag = tl.sum(tl.where(rows[:, None] == cols[None, :], work, 0.0), axis=0)
    diag = tl.where(cols < n, diag, 1.0)

    any_zero = tl.max(tl.where(diag == 0.0, 1, 0), axis=0)
    safe_diag = tl.where(diag == 0.0, 1.0, diag)

    logabsdet = tl.sum(tl.log(tl.abs(safe_diag)), axis=0)
    neg_count = tl.sum(tl.where(safe_diag < 0.0, 1, 0), axis=0)
    nan_count = tl.sum(tl.where(safe_diag != safe_diag, 1, 0), axis=0)

    sign = tl.where((neg_count + swap_count) % 2 == 0, 1.0, -1.0)
    # NaN anywhere on the diagonal: ATen reports sign 0 and a NaN logabsdet.
    sign = tl.where(nan_count > 0, 0.0, sign)
    sign = tl.where(any_zero > 0, 0.0, sign)
    logabsdet = tl.where(any_zero > 0, -float("inf"), logabsdet)

    sign_out_mat = sign_out + pid * stride_sign
    logabsdet_out_mat = logabsdet_out + pid * stride_logabsdet
    tl.store(sign_out_mat, sign.to(sign_out.dtype.element_ty))
    tl.store(logabsdet_out_mat, logabsdet.to(logabsdet_out.dtype.element_ty))


def _linalg_slogdet(A):
    """FlagGems implementation of aten::_linalg_slogdet.

    Computes the sign and natural logarithm of the absolute value of the
    determinant of a square matrix using LU decomposition with partial
    pivoting, and returns the intermediate LU factorization and pivot buffer.

    Args:
        A: tensor of shape (*, n, n) where * is zero or more batch dimensions.

    Returns:
        A tuple (sign, logabsdet, LU, pivots) where:
        - sign has the same dtype as A
        - logabsdet is real-valued
        - LU is the in-place LU factorization produced by the kernel
        - pivots is the int32 pivot buffer (kept for schema parity)
    """
    logger.debug("GEMS _LINALG_SLOGDET")
    assert A.dim() >= 2, "Input must be at least 2D"
    assert A.shape[-1] == A.shape[-2], "Input must be square"
    # The generated slogdet kernel uses float32 arithmetic; reject unsupported dtypes explicitly.
    assert (
        A.dtype == torch.float32
    ), f"_linalg_slogdet: unsupported dtype {A.dtype}, expected float32"

    batch_shape = A.shape[:-2]
    n = A.shape[-1]
    batch_size = 1
    for dim in batch_shape:
        batch_size *= dim

    # Output tensors
    sign = torch.empty(batch_shape, dtype=A.dtype, device=A.device)
    logabsdet = torch.empty(batch_shape, dtype=A.dtype, device=A.device)
    LU = torch.empty(A.shape, dtype=A.dtype, device=A.device)
    # pivots follows the aten schema shape (*, n); the LU pivots are not needed
    # to recover (sign, logabsdet), so a zero-initialized buffer is returned.
    pivots = torch.zeros(batch_shape + (n,), dtype=torch.int32, device=A.device)

    # Handle empty batch
    if batch_size == 0:
        return (
            torch.zeros_like(sign),
            torch.full_like(logabsdet, float("-inf")),
            torch.empty_like(LU),
            torch.zeros_like(pivots),
        )

    # Make a copy of input to avoid modifying the original
    A_copy = A.clone()

    # Get stride for batch
    stride_a = A_copy.stride(-2)
    stride_sign = sign.stride(-1) if sign.dim() > 0 else 0
    stride_logabsdet = logabsdet.stride(-1) if logabsdet.dim() > 0 else 0
    stride_lu = LU.stride(-2)

    # Launch kernel
    grid = (batch_size,)

    # The whole matrix is held in registers as one (BLOCK_SIZE, BLOCK_SIZE)
    # tile, so the block must cover n. 128x128 is the largest fp32 tile that
    # still fits the register budget; beyond it this single-program formulation
    # is not viable (the previous scalar loop did run, but at 26 ms for a
    # 128x128 matrix, so refusing is both faster and clearer than silently
    # degrading).
    block_size = max(16, triton.next_power_of_2(n))
    if block_size > 128:
        raise NotImplementedError(
            f"_linalg_slogdet: matrices larger than 128x128 are not supported yet, "
            f"got {n}x{n}"
        )

    with torch_device_fn.device(A.device):
        _slogdet_kernel[grid](
            A_copy,
            sign,
            logabsdet,
            LU,
            n,
            A_copy.shape[-2],
            stride_a,
            stride_sign,
            stride_logabsdet,
            stride_lu,
            block_size,
        )

    return sign, logabsdet, LU, pivots
