# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry, libtuner, tl_extra_shim

logger = logging.getLogger(__name__)

# Elementary functions used by the fused activation epilogue. ``erf`` mirrors
# ``torch.nn.functional.gelu(approximate="none")``; the gelu branch here uses the
# exact (erf) form to match the default behaviour exercised by the tests.
erf = tl_extra_shim.erf


@libentry()
@libtuner(
    configs=[
        triton.Config(
            {"BLOCK_M": 16, "BLOCK_N": 16, "BLOCK_K": 16}, num_warps=4, num_stages=3
        ),
        triton.Config(
            {"BLOCK_M": 32, "BLOCK_N": 32, "BLOCK_K": 16}, num_warps=4, num_stages=3
        ),
        triton.Config(
            {"BLOCK_M": 32, "BLOCK_N": 32, "BLOCK_K": 32}, num_warps=4, num_stages=2
        ),
        triton.Config(
            {"BLOCK_M": 64, "BLOCK_N": 32, "BLOCK_K": 32}, num_warps=8, num_stages=2
        ),
        triton.Config(
            {"BLOCK_M": 64, "BLOCK_N": 64, "BLOCK_K": 16}, num_warps=8, num_stages=2
        ),
    ],
    key=["M", "N", "K4"],
    strategy=["log", "log", "log"],
    flagtune_op_name="sparse_semi_structured_linear",
)
@triton.jit
def _sparse_linear_kernel(
    input_ptr,
    weight_ptr,
    meta_ptr,
    bias_ptr,
    output_ptr,
    M,
    N,
    K4,
    stride_im,
    stride_ik,
    stride_wn,
    stride_wk,
    stride_mm,
    stride_mn,
    stride_om,
    stride_on,
    HAS_BIAS: tl.constexpr,
    ACT_RELU: tl.constexpr,
    ACT_GELU: tl.constexpr,
    ACT_SILU: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    """
    Kernel for sparse semi-structured (2:4) linear layer.

    Computes ``output = input @ weight.T (+ bias)`` where ``weight`` follows a
    2:4 sparsity pattern along its K dimension: out of every 4 contiguous K
    elements exactly 2 are non-zero. ``meta`` selects, per group of 4, which two
    are kept:

        meta[n, k] != 0  ->  keep weight[n, 4k]     and weight[n, 4k + 1]
        meta[n, k] == 0  ->  keep weight[n, 4k + 2] and weight[n, 4k + 3]

    ``meta`` has shape ``(N, K // 4)`` and is indexed by both N and K4, so each
    weight row carries its own independent 2:4 pattern.

    The kernel fuses bias, output-dtype cast, and an optional activation into a
    single epilogue (no extra kernel launch). The order matches the legacy
    wrapper and the pure-PyTorch reference: accumulate in fp32 -> add bias
    (fp32) -> cast to the output pointer's element type -> apply activation.
    ``relu`` runs at the output precision; ``gelu``/``silu`` re-promote to
    fp32 for the erf/exp computation and cast back to the output precision,
    matching the float32 reference path. ``HAS_BIAS`` / ``ACT_*`` are
    compile-time switches so unsupported combinations are never emitted.
    """
    pid = tl.program_id(0)
    pid_m = pid // tl.cdiv(N, BLOCK_N)
    pid_n = pid % tl.cdiv(N, BLOCK_N)

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    K = K4 * 4
    accumulator = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)

    num_iters = tl.cdiv(K4, BLOCK_K)
    for k in range(num_iters):
        k_offset = k * BLOCK_K

        # --- meta block: shape (BLOCK_N, BLOCK_K), indexed by BOTH N and K4 ---
        meta_ptrs = meta_ptr + (
            offs_n[:, None] * stride_mm + (offs_k + k_offset)[None, :] * stride_mn
        )
        meta_mask = (offs_n[:, None] < N) & ((offs_k + k_offset)[None, :] < K4)
        meta = tl.load(meta_ptrs, mask=meta_mask, other=0)
        meta_f = meta.to(tl.float32)

        # --- input block (dense): a[m, 4k + p] -> shape (BLOCK_M, BLOCK_K, 4) ---
        in_k_off = (offs_k * 4 + k_offset * 4) * stride_ik
        in_base = offs_m[:, None] * stride_im + in_k_off[None, :]
        a0 = tl.load(
            input_ptr + in_base + 0 * stride_ik,
            mask=(offs_m[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 0)[None, :] < K),
            other=0.0,
        )
        a1 = tl.load(
            input_ptr + in_base + 1 * stride_ik,
            mask=(offs_m[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 1)[None, :] < K),
            other=0.0,
        )
        a2 = tl.load(
            input_ptr + in_base + 2 * stride_ik,
            mask=(offs_m[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 2)[None, :] < K),
            other=0.0,
        )
        a3 = tl.load(
            input_ptr + in_base + 3 * stride_ik,
            mask=(offs_m[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 3)[None, :] < K),
            other=0.0,
        )

        # --- weight block (sparse): w[n, 4k + p] -> shape (BLOCK_N, BLOCK_K) ---
        # weight is (N, K); we need it transposed as (K, N) for the matmul, so we
        # index with offs_n along the row dim and the K group along the col dim.
        # Offset for the group start, scaled by the K stride so it honors the
        # weight's actual layout (including non-contiguous strides).
        k_group_off = (offs_k * 4 + k_offset * 4) * stride_wk
        w_base = offs_n[:, None] * stride_wn + k_group_off[None, :]
        w0 = tl.load(
            weight_ptr + w_base + 0 * stride_wk,
            mask=(offs_n[:, None] < N) & ((offs_k * 4 + k_offset * 4 + 0)[None, :] < K),
            other=0.0,
        )
        w1 = tl.load(
            weight_ptr + w_base + 1 * stride_wk,
            mask=(offs_n[:, None] < N) & ((offs_k * 4 + k_offset * 4 + 1)[None, :] < K),
            other=0.0,
        )
        w2 = tl.load(
            weight_ptr + w_base + 2 * stride_wk,
            mask=(offs_n[:, None] < N) & ((offs_k * 4 + k_offset * 4 + 2)[None, :] < K),
            other=0.0,
        )
        w3 = tl.load(
            weight_ptr + w_base + 3 * stride_wk,
            mask=(offs_n[:, None] < N) & ((offs_k * 4 + k_offset * 4 + 3)[None, :] < K),
            other=0.0,
        )

        # --- select-position accumulate ---
        # For each (m, n, k):
        #   meta!=0 -> a0*w0 + a1*w1   (kept positions 0,1)
        #   meta==0 -> a2*w2 + a3*w3   (kept positions 2,3)
        # Shapes: a_p (BM, BK), w_p (BN, BK). Broadcast to (BM, BN, BK) via the
        # element-wise scheme.
        meta_exp = meta_f[None, :, :]  # (1, BN, BK)
        prod01 = a0[:, None, :] * w0[None, :, :] + a1[:, None, :] * w1[None, :, :]
        prod23 = a2[:, None, :] * w2[None, :, :] + a3[:, None, :] * w3[None, :, :]
        selected = prod01 * meta_exp + prod23 * (1.0 - meta_exp)
        accumulator += tl.sum(selected, axis=2)

    # --- fused epilogue: bias -> cast -> activation, all in-kernel ---
    acc = accumulator
    if HAS_BIAS:
        bias = tl.load(bias_ptr + offs_n, mask=offs_n < N, other=0.0).to(tl.float32)
        acc += bias[None, :]

    # Cast to the output dtype, then apply the activation. relu stays at the
    # output precision; gelu/silu re-promote to fp32 for the erf/exp step and
    # cast back, matching the float32 reference path. The target type is read
    # from the output pointer's element type, mirroring the convention in
    # ``mm``/``_fused_rms_norm`` (no dtype constexpr needed).
    out_dtype = output_ptr.dtype.element_ty
    out = acc.to(out_dtype)

    if ACT_RELU:
        out = tl.where(out > 0, out, 0.0)
    elif ACT_GELU:
        # erf-form gelu, equivalent to F.gelu(approximate="none"); the fp32
        # re-promotion matches the float32 reference and the cast-back keeps
        # the result at the requested output precision.
        x = out.to(tl.float32)
        scale: tl.constexpr = 0.7071067811  # 1 / sqrt(2)
        out = (0.5 * x * (1.0 + erf(x * scale))).to(out_dtype)
    elif ACT_SILU:
        x = out.to(tl.float32)
        out = (x / (1.0 + tl.exp(-x))).to(out_dtype)

    output_mask = (offs_m < M)[:, None] & (offs_n < N)[None, :]
    output_ptrs = output_ptr + (
        offs_m[:, None] * stride_om + offs_n[None, :] * stride_on
    )
    tl.store(output_ptrs, out, mask=output_mask)


def _sparse_semi_structured_linear(
    input: torch.Tensor,
    weight: torch.Tensor,
    meta: torch.Tensor,
    bias: torch.Tensor = None,
    activation: str = None,
    out_dtype: torch.dtype = None,
):
    """
    Sparse semi-structured (2:4) linear layer: ``output = input @ weight.T (+ bias)``.

    ``weight`` has shape ``(N, K)`` and obeys a 2:4 sparsity pattern along K: in
    every group of 4 contiguous K elements exactly 2 are non-zero. ``meta`` has
    shape ``(N, K // 4)``; for each group ``k`` of weight row ``n``:

        meta[n, k] != 0  ->  keep weight[n, 4k], weight[n, 4k + 1]
        meta[n, k] == 0  ->  keep weight[n, 4k + 2], weight[n, 4k + 3]

    K must be a multiple of 4. Each weight row carries its own independent 2:4
    pattern, expressed per-row via the N dimension of ``meta``.
    """
    logger.debug("GEMS SPARSE_SEMI_STRUCTURED_LINEAR")

    M, K = input.shape
    N, K_w = weight.shape
    K4 = K // 4

    assert K == K_w, f"Incompatible dimensions: input K={K}, weight K={K_w}"
    assert K % 4 == 0, f"K must be a multiple of 4 for 2:4 sparsity, got K={K}"
    assert meta.shape == (N, K4), f"Expected meta shape ({N}, {K4}), got {meta.shape}"
    assert input.dtype in (
        torch.float16,
        torch.bfloat16,
        torch.float32,
    ), f"Unsupported dtype: {input.dtype}"

    # Output dtype: explicit out_dtype, else same as input.
    if out_dtype is not None:
        output_dtype = out_dtype
    else:
        output_dtype = input.dtype

    # Resolve the activation to compile-time switches for the fused epilogue.
    act = activation.lower() if activation is not None else None
    act_relu = act == "relu"
    act_gelu = act == "gelu"
    act_silu = act in ("silu", "swish")
    if activation is not None and not (act_relu or act_gelu or act_silu):
        raise ValueError(
            f"Unsupported activation: {activation!r}. "
            "Expected one of: 'relu', 'gelu', 'silu' (or 'swish'), or None."
        )

    # Allocate the output at the target dtype; the kernel casts the fp32
    # accumulator to the output dtype inside the fused epilogue before storing.
    output = torch.empty((M, N), device=input.device, dtype=output_dtype)

    # Triton expects a pointer for the optional bias; pass a dummy null tensor
    # when there is none so the kernel's HAS_BIAS=False path never dereferences.
    if bias is not None:
        bias_arg = bias
    else:
        bias_arg = input  # placeholder, never loaded when HAS_BIAS is False

    # Launch kernel with autotuned block sizes
    grid = lambda META: (
        triton.cdiv(M, META["BLOCK_M"]) * triton.cdiv(N, META["BLOCK_N"]),
    )

    _sparse_linear_kernel[grid](
        input,
        weight,
        meta,
        bias_arg,
        output,
        M,
        N,
        K4,
        input.stride(0),
        input.stride(1),
        weight.stride(0),
        weight.stride(1),
        meta.stride(0),
        meta.stride(1),
        output.stride(0),
        output.stride(1),
        bias is not None,
        act_relu,
        act_gelu,
        act_silu,
    )

    return output
