# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import flag_gems

logger = logging.getLogger(__name__)


def _transformer_encoder_layer_fwd(
    src,
    embed_dim,
    num_heads,
    qkv_weight,
    qkv_bias,
    proj_weight,
    proj_bias,
    use_gelu,
    norm_first,
    eps,
    norm_weight_1,
    norm_bias_1,
    norm_weight_2,
    norm_bias_2,
    ffn_weight_1,
    ffn_bias_1,
    ffn_weight_2,
    ffn_bias_2,
):
    """
    Transformer encoder layer forward pass.

    Implements: Self-Attention + LayerNorm + FFN + LayerNorm with residual connections.
    Optimized with FlagGems kernels for better performance.
    """
    logger.debug("GEMS _TRANSFORMER_ENCODER_LAYER_FWD")

    batch_size, seq_len, _ = src.shape
    head_dim = embed_dim // num_heads

    x = src

    # Optionally apply layer norm first (pre-norm architecture)
    if norm_first:
        x, _, _ = flag_gems.layer_norm(x, (embed_dim,), norm_weight_1, norm_bias_1, eps)

    # Multi-head self-attention
    # 1. QKV projection using FlagGems linear
    qkv = flag_gems.linear(x, qkv_weight, qkv_bias)
    qkv = qkv.reshape(batch_size, seq_len, 3, num_heads, head_dim)
    qkv = qkv.permute(2, 0, 3, 1, 4)  # [3, batch, num_heads, seq_len, head_dim]
    q, k, v = qkv[0], qkv[1], qkv[2]

    # 2. Scaled dot-product attention
    # Reshape to 3D for bmm: [batch*num_heads, seq_len, head_dim]
    scale = 1.0 / math.sqrt(head_dim)
    batch_heads = batch_size * num_heads

    q_3d = q.reshape(batch_heads, seq_len, head_dim)
    k_3d = k.reshape(batch_heads, seq_len, head_dim)
    v_3d = v.reshape(batch_heads, seq_len, head_dim)

    # Attention: Q @ K^T
    attn_scores = flag_gems.bmm(q_3d, k_3d.transpose(-2, -1)) * scale
    attn_probs = flag_gems.softmax(attn_scores, dim=-1)
    # Attention output: attn_probs @ V
    attn_output = flag_gems.bmm(attn_probs, v_3d)

    # Reshape back to [batch, num_heads, seq_len, head_dim]
    attn_output = attn_output.reshape(batch_size, num_heads, seq_len, head_dim)

    # 3. Reshape and project output
    attn_output = attn_output.transpose(1, 2).reshape(batch_size, seq_len, embed_dim)
    attn_output = flag_gems.linear(attn_output, proj_weight, proj_bias)

    # 4. First residual connection
    x = src + attn_output

    # 5. First layer norm (post-norm) if not norm_first
    if not norm_first:
        x, _, _ = flag_gems.layer_norm(x, (embed_dim,), norm_weight_1, norm_bias_1, eps)

    # Store for second residual
    residual = x

    # Optionally apply second layer norm first
    if norm_first:
        x, _, _ = flag_gems.layer_norm(x, (embed_dim,), norm_weight_2, norm_bias_2, eps)

    # Feedforward network
    # 1. First linear layer
    x = flag_gems.linear(x, ffn_weight_1, ffn_bias_1)

    # 2. Activation (GELU or ReLU)
    if use_gelu:
        x = flag_gems.gelu(x, approximate="tanh")
    else:
        x = flag_gems.relu(x)

    # 3. Second linear layer
    x = flag_gems.linear(x, ffn_weight_2, ffn_bias_2)

    # 4. Second residual connection
    x = residual + x

    # 5. Second layer norm (post-norm) if not norm_first
    if not norm_first:
        x, _, _ = flag_gems.layer_norm(x, (embed_dim,), norm_weight_2, norm_bias_2, eps)

    return x
