# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
import math
from collections import OrderedDict

import torch
import triton
import triton.language as tl

from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)

_WEIGHT_CACHE_MAX_ENTRIES = 128
sinpi = tl_extra_shim.sinpi


@triton.jit
def _lanczos_aa_filter(x):
    """Lanczos-3 filter used by PyTorch's antialiased implementation."""
    pix = math.pi * x
    sinc = tl.where(x == 0.0, 1.0, sinpi(x) / pix)
    sinc_three = tl.where(x == 0.0, 1.0, sinpi(x / 3.0) / (pix / 3.0))
    return tl.where(x < 3.0, sinc * sinc_three, 0.0)


@triton.jit
def _f2i(x):
    """float -> int32 with clamping to avoid undefined overflow."""
    _LO: tl.constexpr = -2147483648.0
    _HI: tl.constexpr = 2147483520.0
    return tl.minimum(tl.maximum(x, _LO), _HI).to(tl.int32)


@triton.jit
def _fused_precomputed_backward_kernel(
    grad_out_ptr,
    grad_in_ptr,
    wx_ptr,
    wx_start_ptr,
    wy_ptr,
    wy_start_ptr,
    H_in,
    H_out,
    W_in,
    W_out,
    support_h,
    support_w,
    inv_h_scale,
    inv_w_scale,
    stride_go_nc,
    BLOCK_IW: tl.constexpr,
    MAX_OH: tl.constexpr,
    MAX_OW: tl.constexpr,
    MAX_KSIZE_H: tl.constexpr,
    MAX_KSIZE_W: tl.constexpr,
):
    """Single-pass input gather using separately precomputed Lanczos weights."""
    pid_row = tl.program_id(0)
    pid_col = tl.program_id(1)
    nc = pid_row // H_in
    ih = pid_row % H_in
    iws = pid_col * BLOCK_IW + tl.arange(0, BLOCK_IW)
    iw_mask = iws < W_in

    oh_start = tl.maximum(
        _f2i((ih.to(tl.float32) + 0.5 - support_h) * inv_h_scale - 0.5), 0
    )
    ow_starts = tl.maximum(
        _f2i((iws.to(tl.float32) + 0.5 - support_w) * inv_w_scale - 0.5), 0
    )
    accum = tl.zeros((BLOCK_IW,), dtype=tl.float32)
    go_nc_base = nc.to(tl.int64) * stride_go_nc

    for d_ow in tl.static_range(MAX_OW):
        ow = ow_starts + d_ow
        ow_valid = iw_mask & (ow < W_out)
        ow_safe = tl.minimum(ow, W_out - 1)
        xmin = tl.load(wx_start_ptr + ow_safe, mask=ow_valid, other=0)
        kx = iws - xmin
        x_valid = ow_valid & (kx >= 0) & (kx < MAX_KSIZE_W)
        kx_safe = tl.minimum(tl.maximum(kx, 0), MAX_KSIZE_W - 1)
        wx = tl.load(
            wx_ptr + ow_safe.to(tl.int64) * MAX_KSIZE_W + kx_safe.to(tl.int64),
            mask=x_valid,
            other=0.0,
        )

        for d_oh in tl.static_range(MAX_OH):
            oh = oh_start + d_oh
            oh_valid = oh < H_out
            oh_safe = tl.minimum(oh, H_out - 1)
            ymin = tl.load(wy_start_ptr + oh_safe, mask=oh_valid, other=0)
            ky = ih - ymin
            y_valid = oh_valid & (ky >= 0) & (ky < MAX_KSIZE_H)
            ky_safe = tl.minimum(tl.maximum(ky, 0), MAX_KSIZE_H - 1)
            wy = tl.load(
                wy_ptr + oh_safe.to(tl.int64) * MAX_KSIZE_H + ky_safe.to(tl.int64),
                mask=y_valid,
                other=0.0,
            )
            valid = x_valid & y_valid
            grad = tl.load(
                grad_out_ptr
                + go_nc_base
                + oh_safe.to(tl.int64) * W_out
                + ow_safe.to(tl.int64),
                mask=valid,
                other=0.0,
            )
            accum += wx * wy * grad

    grad_in_offset = pid_row.to(tl.int64) * W_in + iws.to(tl.int64)
    tl.store(
        grad_in_ptr + grad_in_offset,
        accum.to(grad_in_ptr.dtype.element_ty),
        mask=iw_mask,
    )


@triton.jit
def _precompute_weights_kernel(
    weight_ptr,
    start_ptr,
    output_size,
    input_size,
    scale,
    support,
    invscale,
    MAX_KSIZE: tl.constexpr,
    BLOCK_KSIZE: tl.constexpr,
):
    oi = tl.program_id(0)
    if oi >= output_size:
        return

    offs = tl.arange(0, BLOCK_KSIZE)
    offs_mask = offs < MAX_KSIZE
    center = scale * (oi + 0.5)
    xmin = tl.maximum(_f2i(center - support + 0.5), 0)
    xsize = tl.minimum(_f2i(center + support + 0.5), input_size) - xmin
    xsize = tl.minimum(tl.maximum(xsize, 0), MAX_KSIZE)
    xmin_f = xmin.to(tl.float32)

    arg = tl.abs((offs.to(tl.float32) + xmin_f - center + 0.5) * invscale)
    raw_w = tl.where((offs < xsize) & offs_mask, _lanczos_aa_filter(arg), 0.0)
    total = tl.sum(raw_w, axis=0)
    weights = tl.where(total != 0.0, raw_w / total, 0.0)

    tl.store(weight_ptr + oi.to(tl.int64) * MAX_KSIZE + offs, weights, mask=offs_mask)
    tl.store(start_ptr + oi, xmin)


@triton.jit
def _pass1_w_gather_nchw_kernel(
    grad_out_ptr,  # [NC, H_out, W_out] flat
    buf_ptr,  # [NC, H_out, W_in]  flat (output)
    wx_ptr,  # [W_out, MAX_KSIZE_W]
    wx_start_ptr,  # [W_out]
    W_in,
    W_out,
    support_w,
    inv_w_scale,
    BLOCK_IW: tl.constexpr,
    MAX_OW: tl.constexpr,
    MAX_KSIZE_W: tl.constexpr,
):
    pid_row = tl.program_id(0)
    pid_col = tl.program_id(1)

    iw_base = pid_col * BLOCK_IW
    iws = iw_base + tl.arange(0, BLOCK_IW)
    iw_mask = iws < W_in
    iw_f = iws.to(tl.float32)

    go_base = pid_row.to(tl.int64) * W_out
    buf_base = pid_row.to(tl.int64) * W_in

    ow_starts = tl.maximum(_f2i((iw_f + 0.5 - support_w) * inv_w_scale - 0.5), 0)

    accum = tl.zeros([BLOCK_IW], dtype=tl.float32)

    for d_ow in tl.static_range(MAX_OW):
        ow = ow_starts + d_ow
        ow_valid = iw_mask & (ow >= 0) & (ow < W_out)
        ow_safe = tl.maximum(tl.minimum(ow, W_out - 1), 0)

        xmin = tl.load(wx_start_ptr + ow_safe)
        k = iws - xmin
        in_range = ow_valid & (k >= 0) & (k < MAX_KSIZE_W)
        k_safe = tl.minimum(tl.maximum(k, 0), MAX_KSIZE_W - 1)
        wx_raw = tl.load(
            wx_ptr + ow_safe.to(tl.int64) * MAX_KSIZE_W + k_safe.to(tl.int64)
        )
        wx = tl.where(in_range, wx_raw, 0.0)

        g = tl.load(
            grad_out_ptr + go_base + ow_safe.to(tl.int64), mask=in_range, other=0.0
        )
        accum += wx * g

    tl.store(buf_ptr + buf_base + iws.to(tl.int64), accum, mask=iw_mask)


@triton.jit
def _pass2_h_gather_nchw_kernel(
    buf_ptr,  # [NC, H_out, W_in] flat (input)
    grad_in_ptr,  # [NC, H_in,  W_in] flat (output)
    wy_ptr,  # [H_out, MAX_KSIZE_H]
    wy_start_ptr,  # [H_out]
    H_in,
    W_in,
    H_out,
    support_h,
    inv_h_scale,
    stride_buf_hw,  # = H_out * W_in
    BLOCK_IW: tl.constexpr,
    MAX_OH: tl.constexpr,
    MAX_KSIZE_H: tl.constexpr,
):
    pid_row = tl.program_id(0)
    pid_col = tl.program_id(1)

    nc = pid_row // H_in
    ih = pid_row % H_in
    ih_f = ih.to(tl.float32)

    iw_base = pid_col * BLOCK_IW
    iws = iw_base + tl.arange(0, BLOCK_IW)
    iw_mask = iws < W_in

    oh_start = tl.maximum(_f2i((ih_f + 0.5 - support_h) * inv_h_scale - 0.5), 0)

    buf_nc_base = nc.to(tl.int64) * stride_buf_hw

    accum = tl.zeros([BLOCK_IW], dtype=tl.float32)

    for d_oh in tl.static_range(MAX_OH):
        oh = oh_start + d_oh
        oh_valid = (oh >= 0) & (oh < H_out)
        oh_safe = tl.maximum(tl.minimum(oh, H_out - 1), 0)

        ymin = tl.load(wy_start_ptr + oh_safe)
        k = ih - ymin
        ih_in_range = oh_valid & (k >= 0) & (k < MAX_KSIZE_H)
        k_safe = tl.minimum(tl.maximum(k, 0), MAX_KSIZE_H - 1)
        wy_raw = tl.load(
            wy_ptr + oh_safe.to(tl.int64) * MAX_KSIZE_H + k_safe.to(tl.int64)
        )
        wy = tl.where(ih_in_range, wy_raw, 0.0)

        buf_off = buf_nc_base + oh_safe.to(tl.int64) * W_in + iws.to(tl.int64)
        b = tl.load(buf_ptr + buf_off, mask=iw_mask & ih_in_range, other=0.0)

        accum += wy * b

    gi_off = pid_row.to(tl.int64) * W_in + iws.to(tl.int64)
    tl.store(
        grad_in_ptr + gi_off,
        accum.to(grad_in_ptr.dtype.element_ty),
        mask=iw_mask,
    )


def _compute_scale(input_size, output_size, align_corners, scale=None):
    if align_corners:
        return float(input_size - 1) / (output_size - 1) if output_size > 1 else 0.0
    else:
        return (
            (1.0 / scale)
            if (scale is not None and scale > 0)
            else float(input_size) / output_size
        )


def _lanczos_aa_filter_scalar(x):
    x = abs(float(x))
    if x == 0.0:
        return 1.0
    if x >= 3.0:
        return 0.0
    pix = math.pi * x
    return (math.sin(pix) / pix) * (math.sin(pix / 3.0) / (pix / 3.0))


def _weight_matrix_cache_key(
    input_size,
    output_size,
    align_corners,
    scale,
    dtype,
    device,
    transpose,
):
    return (
        int(input_size),
        int(output_size),
        bool(align_corners),
        None if scale is None else float(scale),
        dtype,
        str(device),
        bool(transpose),
    )


def _get_weight_matrix(
    input_size,
    output_size,
    align_corners,
    scale_arg,
    dtype,
    device,
    transpose=False,
):
    cache = getattr(_get_weight_matrix, "_cache", None)
    if cache is None:
        cache = OrderedDict()
        _get_weight_matrix._cache = cache
    key = _weight_matrix_cache_key(
        input_size,
        output_size,
        align_corners,
        scale_arg,
        dtype,
        device,
        transpose,
    )
    cached = cache.get(key)
    if cached is not None:
        cache.move_to_end(key)
        return cached

    scale = _compute_scale(input_size, output_size, align_corners, scale_arg)
    # Lanczos-3 has support radius 3 at unit scale (INTERP_SIZE == 6).
    support = 3.0 * scale if scale >= 1.0 else 3.0
    invscale = 1.0 / scale if scale >= 1.0 else 1.0

    weight_cpu = torch.zeros((output_size, input_size), dtype=dtype)
    for oi in range(output_size):
        center = scale * (oi + 0.5)
        xmin = max(math.floor(center - support + 0.5), 0)
        xmax = min(math.floor(center + support + 0.5), input_size)
        values = [
            _lanczos_aa_filter_scalar((ii - center + 0.5) * invscale)
            for ii in range(xmin, xmax)
        ]
        total = sum(values)
        if total != 0.0:
            for ii, value in zip(range(xmin, xmax), values):
                weight_cpu[oi, ii] = value / total

    if transpose:
        weight_cpu = weight_cpu.t().contiguous()
    weight = weight_cpu.to(device=device, dtype=dtype)
    if len(cache) >= _WEIGHT_CACHE_MAX_ENTRIES:
        cache.popitem(last=False)
    cache[key] = weight
    return weight


def _gemm_backward_path(
    grad_output,
    output_size,
    input_size,
    align_corners,
    scales_h,
    scales_w,
):
    N, C, H_in, W_in = input_size
    H_out, W_out = output_size
    NC = N * C

    compute_dtype = (
        torch.float64 if grad_output.dtype == torch.float64 else torch.float32
    )
    wx = _get_weight_matrix(
        W_in,
        W_out,
        align_corners,
        scales_w,
        compute_dtype,
        grad_output.device,
    )
    if NC == 1:
        wy_t = _get_weight_matrix(
            H_in,
            H_out,
            align_corners,
            scales_h,
            compute_dtype,
            grad_output.device,
            transpose=True,
        )

        grad_w = grad_output.contiguous().reshape(H_out, W_out).to(compute_dtype)
        tmp = torch.mm(grad_w, wx)
        out = torch.mm(wy_t, tmp)
        return out.reshape(N, C, H_in, W_in).to(grad_output.dtype)

    wy = _get_weight_matrix(
        H_in,
        H_out,
        align_corners,
        scales_h,
        compute_dtype,
        grad_output.device,
    )

    grad_w = grad_output.contiguous().reshape(NC * H_out, W_out).to(compute_dtype)
    tmp = torch.mm(grad_w, wx).reshape(NC, H_out, W_in)
    tmp_h = tmp.transpose(1, 2).contiguous().reshape(NC * W_in, H_out)
    out = torch.mm(tmp_h, wy).reshape(NC, W_in, H_in).transpose(1, 2).contiguous()
    return out.reshape(N, C, H_in, W_in).to(grad_output.dtype)


def _should_use_gemm_path(device_type, NC, H_in, W_in, H_out, W_out, align_corners):
    if align_corners and (H_out == 1 or W_out == 1):
        return False
    if device_type == "npu":
        return True
    if device_type == "cuda":
        # Tiny tensors cannot amortize three Triton launches (two weight
        # precomputes plus gather). Channel-heavy downsampling is also faster as
        # two dense products on H20; other shapes retain the sparse Triton path.
        tiny = NC * max(H_in * W_in, H_out * W_out) < 8192
        channel_heavy_downsample = NC >= 128 and H_out < H_in and W_out < W_in
        very_large_upsample = NC >= (1 << 17) and H_out >= H_in and W_out >= W_in
        return tiny or channel_heavy_downsample or very_large_upsample
    return False


# CUDA keeps the previous total-element threshold until H20 benchmarks say the
# extra 2-pass launches are profitable for small tensors.
_FUSE_THRESHOLD = 1 << 20  # 1M elements

# Ascend pays a high scalar cost in the fused nested output loop. Keep the
# single data-pass path only for very small work items such as 4x4 -> 1x1.
_ASCEND_FUSE_MAX_PROGRAM_ITERATIONS = 512
_ASCEND_FUSE_ALWAYS_FILTER_AREA = 1


def _should_use_fused_path(
    device_type,
    total_elems,
    NC,
    H_in,
    W_in,
    BLOCK_IW,
    MAX_OH,
    MAX_OW,
):
    filter_area = MAX_OH * MAX_OW
    if device_type == "npu":
        if filter_area <= _ASCEND_FUSE_ALWAYS_FILTER_AREA:
            return True
        w_tiles = triton.cdiv(W_in, BLOCK_IW)
        fused_program_iterations = NC * H_in * w_tiles * filter_area
        return fused_program_iterations <= _ASCEND_FUSE_MAX_PROGRAM_ITERATIONS
    return total_elems <= _FUSE_THRESHOLD


def upsample_lanczos2d_aa_backward(
    grad_output: torch.Tensor,
    output_size,  # [H_out, W_out]
    input_size,  # [N, C, H_in, W_in]
    align_corners: bool,
    scales_h=None,
    scales_w=None,
) -> torch.Tensor:
    logger.debug("GEMS UPSAMPLE_LANCZOS2D_AA_BACKWARD")
    if grad_output.ndim != 4:
        raise RuntimeError(
            "Expected grad_output to be a tensor of dimension 4 but got: "
            f"dimension {grad_output.ndim}"
        )
    if len(output_size) != 2 or len(input_size) != 4:
        raise RuntimeError("Expected output_size[2] and input_size[4]")
    if not grad_output.is_floating_point():
        raise RuntimeError(
            f'"upsample_lanczos2d_aa_backward" not implemented for {grad_output.dtype}'
        )

    N, C, H_in, W_in = map(int, input_size)
    H_out, W_out = output_size

    if tuple(grad_output.shape) != (N, C, H_out, W_out):
        raise RuntimeError(
            f"Expected grad_output shape ({N}, {C}, {H_out}, {W_out}), "
            f"but got {tuple(grad_output.shape)}"
        )

    NC = N * C
    if NC == 0 or H_in == 0 or W_in == 0 or H_out == 0 or W_out == 0:
        return grad_output.new_zeros(input_size)

    if grad_output.dtype == torch.float64 or _should_use_gemm_path(
        grad_output.device.type, NC, H_in, W_in, H_out, W_out, align_corners
    ):
        return _gemm_backward_path(
            grad_output,
            output_size,
            input_size,
            align_corners,
            scales_h,
            scales_w,
        )

    # ---- Work in NCHW — zero-copy reshape to [NC, H, W] ----
    grad_out_flat = grad_output.contiguous().reshape(NC, H_out, W_out)

    # ---- Scales & filter parameters ----
    h_scale = _compute_scale(H_in, H_out, align_corners, scales_h)
    w_scale = _compute_scale(W_in, W_out, align_corners, scales_w)

    # Lanczos-3 has diameter six; downsampling widens it by the inverse scale.
    INTERP_SIZE = 6
    support_h = (INTERP_SIZE * 0.5) * h_scale if h_scale >= 1.0 else INTERP_SIZE * 0.5
    support_w = (INTERP_SIZE * 0.5) * w_scale if w_scale >= 1.0 else INTERP_SIZE * 0.5
    invscale_h = 1.0 / h_scale if h_scale >= 1.0 else 1.0
    invscale_w = 1.0 / w_scale if w_scale >= 1.0 else 1.0

    MAX_KSIZE_H = math.ceil(support_h) * 2 + 1
    MAX_KSIZE_W = math.ceil(support_w) * 2 + 1

    _EPS = 1e-10
    inv_h_scale = 1.0 / max(h_scale, _EPS)
    inv_w_scale = 1.0 / max(w_scale, _EPS)

    MAX_OH = min(math.ceil(2 * support_h * inv_h_scale) + 2, max(H_out, 1))
    MAX_OW = min(math.ceil(2 * support_w * inv_w_scale) + 2, max(W_out, 1))

    # ---- BLOCK_IW & num_warps ----
    BLOCK_IW = min(triton.next_power_of_2(max(W_in, 1)), 256)
    if BLOCK_IW < 32:
        BLOCK_IW = 32
    nw = 1 if BLOCK_IW <= 32 else (2 if BLOCK_IW <= 64 else 4)

    # ---- Choose fused vs 2-pass ----
    total_elems = NC * max(H_in * W_in, H_out * W_out)
    use_fused = _should_use_fused_path(
        grad_output.device.type,
        total_elems,
        NC,
        H_in,
        W_in,
        BLOCK_IW,
        MAX_OH,
        MAX_OW,
    )

    if use_fused:
        # ============================================================
        # FUSED PATH — precompute 1-D weights, then gather without a buffer
        # ============================================================
        wy = torch.empty(
            max(H_out, 1),
            MAX_KSIZE_H,
            dtype=torch.float32,
            device=grad_output.device,
        )
        wx = torch.empty(
            max(W_out, 1),
            MAX_KSIZE_W,
            dtype=torch.float32,
            device=grad_output.device,
        )
        wy_start = torch.empty(
            max(H_out, 1), dtype=torch.int32, device=grad_output.device
        )
        wx_start = torch.empty(
            max(W_out, 1), dtype=torch.int32, device=grad_output.device
        )
        _precompute_weights_kernel[(H_out,)](
            wy,
            wy_start,
            H_out,
            H_in,
            h_scale,
            support_h,
            invscale_h,
            MAX_KSIZE=MAX_KSIZE_H,
            BLOCK_KSIZE=triton.next_power_of_2(MAX_KSIZE_H),
        )
        _precompute_weights_kernel[(W_out,)](
            wx,
            wx_start,
            W_out,
            W_in,
            w_scale,
            support_w,
            invscale_w,
            MAX_KSIZE=MAX_KSIZE_W,
            BLOCK_KSIZE=triton.next_power_of_2(MAX_KSIZE_W),
        )
        grad_in_flat = torch.empty(
            NC, H_in, W_in, dtype=grad_output.dtype, device=grad_output.device
        )
        grid = (NC * H_in, triton.cdiv(W_in, BLOCK_IW))
        _fused_precomputed_backward_kernel[grid](
            grad_out_flat,
            grad_in_flat,
            wx,
            wx_start,
            wy,
            wy_start,
            H_in,
            H_out,
            W_in,
            W_out,
            support_h,
            support_w,
            inv_h_scale,
            inv_w_scale,
            H_out * W_out,  # stride_go_nc
            BLOCK_IW=BLOCK_IW,
            MAX_OH=MAX_OH,
            MAX_OW=MAX_OW,
            MAX_KSIZE_H=MAX_KSIZE_H,
            MAX_KSIZE_W=MAX_KSIZE_W,
            num_warps=nw,
        )
        return grad_in_flat.reshape(N, C, H_in, W_in)
    else:
        # ============================================================
        # 2-PASS PATH — separable, memory-bandwidth efficient for big tensors
        # ============================================================

        # Phase 0: precompute normalized weights and input starts.
        wy = torch.empty(
            max(H_out, 1),
            MAX_KSIZE_H,
            dtype=torch.float32,
            device=grad_output.device,
        )
        wx = torch.empty(
            max(W_out, 1),
            MAX_KSIZE_W,
            dtype=torch.float32,
            device=grad_output.device,
        )
        wy_start = torch.empty(
            max(H_out, 1), dtype=torch.int32, device=grad_output.device
        )
        wx_start = torch.empty(
            max(W_out, 1), dtype=torch.int32, device=grad_output.device
        )
        BLOCK_KSIZE_H = triton.next_power_of_2(MAX_KSIZE_H)
        BLOCK_KSIZE_W = triton.next_power_of_2(MAX_KSIZE_W)
        if H_out > 0:
            _precompute_weights_kernel[(H_out,)](
                wy,
                wy_start,
                H_out,
                H_in,
                h_scale,
                support_h,
                invscale_h,
                MAX_KSIZE=MAX_KSIZE_H,
                BLOCK_KSIZE=BLOCK_KSIZE_H,
            )
        if W_out > 0:
            _precompute_weights_kernel[(W_out,)](
                wx,
                wx_start,
                W_out,
                W_in,
                w_scale,
                support_w,
                invscale_w,
                MAX_KSIZE=MAX_KSIZE_W,
                BLOCK_KSIZE=BLOCK_KSIZE_W,
            )

        # Phase 1: W-gather -> buf [NC, H_out, W_in]
        buf = torch.empty(
            NC, H_out, W_in, dtype=torch.float32, device=grad_output.device
        )
        grid1 = (NC * H_out, triton.cdiv(W_in, BLOCK_IW))
        _pass1_w_gather_nchw_kernel[grid1](
            grad_out_flat,
            buf,
            wx,
            wx_start,
            W_in,
            W_out,
            support_w,
            inv_w_scale,
            BLOCK_IW=BLOCK_IW,
            MAX_OW=MAX_OW,
            MAX_KSIZE_W=MAX_KSIZE_W,
            num_warps=nw,
        )

        # Phase 2: H-gather -> grad_in [NC, H_in, W_in]
        grad_in_flat = torch.empty(
            NC, H_in, W_in, dtype=grad_output.dtype, device=grad_output.device
        )
        grid2 = (NC * H_in, triton.cdiv(W_in, BLOCK_IW))
        _pass2_h_gather_nchw_kernel[grid2](
            buf,
            grad_in_flat,
            wy,
            wy_start,
            H_in,
            W_in,
            H_out,
            support_h,
            inv_h_scale,
            H_out * W_in,  # stride_buf_hw
            BLOCK_IW=BLOCK_IW,
            MAX_OH=MAX_OH,
            MAX_KSIZE_H=MAX_KSIZE_H,
            num_warps=nw,
        )

        return grad_in_flat.reshape(N, C, H_in, W_in)


def upsample_lanczos2d_aa_backward_grad_input(
    grad_output: torch.Tensor,
    output_size,
    input_size,
    align_corners: bool,
    scales_h=None,
    scales_w=None,
    *,
    grad_input: torch.Tensor,
) -> torch.Tensor:
    logger.debug("GEMS UPSAMPLE_LANCZOS2D_AA_BACKWARD_GRAD_INPUT")
    if grad_input.device != grad_output.device:
        raise RuntimeError(
            f"Expected grad_input on {grad_output.device}, but got {grad_input.device}"
        )
    if grad_input.dtype != grad_output.dtype:
        raise RuntimeError(
            f"Expected grad_input dtype {grad_output.dtype}, but got {grad_input.dtype}"
        )
    result = upsample_lanczos2d_aa_backward(
        grad_output,
        output_size,
        input_size,
        align_corners,
        scales_h,
        scales_w,
    )
    grad_input.resize_(result.shape)
    grad_input.copy_(result)
    return grad_input
