# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.bitwise_and import bitwise_and_tensor

logger = logging.getLogger(__name__)

_INT32_MAX = torch.iinfo(torch.int32).max


@triton.jit
def and_tensor_kernel(x_ptr, y_ptr, out_ptr, numel, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offset = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offset < numel
    x = tl.load(x_ptr + offset, mask=mask, other=0).to(x_ptr.dtype.element_ty)
    y = tl.load(y_ptr + offset, mask=mask, other=0).to(y_ptr.dtype.element_ty)
    tl.store(out_ptr + offset, x & y, mask=mask)


def _use_fast_path(x, y):
    # Fast path covers the common case: same-shape, same-dtype, contiguous
    # CUDA tensors that fit the kernel's int32 indexing. Everything else
    # (broadcasting, mixed dtypes, strided inputs, huge tensors) falls back
    # to the generic pointwise_dynamic kernel.
    return (
        isinstance(x, torch.Tensor)
        and isinstance(y, torch.Tensor)
        and x.dtype == y.dtype
        and x.is_contiguous()
        and y.is_contiguous()
        and x.shape == y.shape
        and x.device == y.device
        and x.is_cuda
        and not x.dtype.is_floating_point
        and x.numel() <= _INT32_MAX
    )


def and_tensor(self, other):
    """Bitwise AND through the tensor dunder method with tensor operands.

    ``__and__.Tensor`` and ``bitwise_and.Tensor`` are the same operation's two
    entry points in ATen (verified numerically and by schema).

    Same-shape contiguous tensor pairs take a flat 1-D launch that skips the
    generic rank/stride analysis in ``pointwise_dynamic`` — its Python-side
    preparation dominates latency for small and mid-size inputs.
    """
    logger.debug("GEMS AND")
    if _use_fast_path(self, other):
        numel = self.numel()
        if numel == 0:
            return torch.empty_like(self)
        out = torch.empty_like(self)
        grid = (triton.cdiv(numel, 2048),)
        and_tensor_kernel[grid](self, other, out, numel, BLOCK=2048, num_warps=4)
        return out
    return bitwise_and_tensor(self, other)
