# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

from flag_gems.ops.linalg_cross import _linalg_cross_impl, _validate_inputs

logger = logging.getLogger(__name__)

# ``aten::cross`` shares its arithmetic with ``aten::linalg_cross``; the only
# difference is the treatment of ``dim``. ``torch.cross`` is the deprecated API
# whose ``dim=None`` default scans for the first axis of length 3, whereas
# ``torch.linalg.cross`` defaults to ``dim=-1``. We resolve that default here
# and then defer to the already-optimised ``linalg_cross`` kernel, so both aten
# ops route through a single, tuned implementation instead of duplicating it.

_FALLBACK_KEYSET = torch._C.DispatchKeySet(
    torch._C.DispatchKey.CompositeExplicitAutograd
)


def _default_dim(input, other):
    # ``torch.cross`` with ``dim=None`` picks the first dimension of size 3,
    # inspecting the broadcast shape so a length-3 axis contributed by either
    # operand is honoured (mirrors ATen's ``_default_dim`` in Cross.cpp).
    broadcast_shape = torch.broadcast_shapes(input.shape, other.shape)
    for axis, size in enumerate(broadcast_shape):
        if size == 3:
            return axis
    raise RuntimeError(
        "no dimension of size 3 in input; " "cross requires a dimension of length 3"
    )


def cross(input, other, dim=None):
    """NVIDIA Triton implementation of ``torch.cross`` (aten::cross)."""
    logger.debug("GEMS CROSS")
    resolved_dim = _default_dim(input, other) if dim is None else dim
    return _linalg_cross_impl(input, other, resolved_dim)


def cross_out(input, other, dim=None, *, out):
    logger.debug("GEMS CROSS_OUT")
    resolved_dim = _default_dim(input, other) if dim is None else dim
    _, output_shape = _validate_inputs(input, other, resolved_dim)
    if out.dtype != input.dtype:
        raise RuntimeError(
            f"cross: expected out dtype {input.dtype}, but got {out.dtype}"
        )
    if out.device != input.device:
        raise RuntimeError("cross: out must be on the same device as input")
    if tuple(out.shape) != tuple(output_shape):
        out.resize_(output_shape)
    return _linalg_cross_impl(input, other, resolved_dim, output=out)
