# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils.limits import get_dtype_min

logger = logging.getLogger(__name__)


FORWARD_CONFIGS = [
    triton.Config({"BLOCK_H": 4, "BLOCK_W": 4}, num_warps=4),
    triton.Config({"BLOCK_H": 4, "BLOCK_W": 8}, num_warps=4),
    triton.Config({"BLOCK_H": 8, "BLOCK_W": 8}, num_warps=4),
    triton.Config({"BLOCK_H": 4, "BLOCK_W": 16}, num_warps=4),
    triton.Config({"BLOCK_H": 8, "BLOCK_W": 16}, num_warps=8),
    triton.Config({"BLOCK_H": 16, "BLOCK_W": 16}, num_warps=8),
]


@libentry()
@triton.autotune(
    configs=FORWARD_CONFIGS,
    key=["out_d", "out_h", "out_w", "kernel_d", "kernel_h", "kernel_w"],
)
@triton.jit
def fractional_max_pool3d_forward_kernel(
    input_ptr,
    output_ptr,
    indices_ptr,
    random_samples_ptr,
    # Input tensor strides
    in_stride_n,
    in_stride_c,
    in_stride_d,
    in_stride_h,
    in_stride_w,
    # Input/Output shapes
    in_c,
    in_d,
    in_h,
    in_w,
    out_d,
    out_h,
    out_w,
    # Precomputed alpha values for interval generation
    alpha_d,
    alpha_h,
    alpha_w,
    # Pooling parameters
    kernel_d: tl.constexpr,
    kernel_h: tl.constexpr,
    kernel_w: tl.constexpr,
    # Tiling meta-parameters
    BLOCK_H: tl.constexpr,
    BLOCK_W: tl.constexpr,
):
    """Forward kernel for fractional max pool 3d.

    Each program handles one (n, c) plane at a specific (d, h_tile, w_tile).
    Grid: (N*C, out_d * cdiv(out_h, BLOCK_H) * cdiv(out_w, BLOCK_W))
    """
    pid_nc = tl.program_id(0)
    pid_dhw = tl.program_id(1)

    num_h_blocks = tl.cdiv(out_h, BLOCK_H)
    num_w_blocks = tl.cdiv(out_w, BLOCK_W)
    num_hw_blocks = num_h_blocks * num_w_blocks

    d_idx = pid_dhw // num_hw_blocks
    hw_remainder = pid_dhw % num_hw_blocks
    h_block_idx = hw_remainder // num_w_blocks
    w_block_idx = hw_remainder % num_w_blocks

    n_idx = pid_nc // in_c
    c_idx = pid_nc % in_c

    h_out_offsets = h_block_idx * BLOCK_H + tl.arange(0, BLOCK_H)
    w_out_offsets = w_block_idx * BLOCK_W + tl.arange(0, BLOCK_W)

    dtype = input_ptr.type.element_ty
    min_val = get_dtype_min(dtype)

    input_base_ptr = input_ptr + n_idx * in_stride_n + c_idx * in_stride_c

    # Load random samples for this (n, c) plane
    # random_samples layout: [N*C, 3] contiguous
    sample_d = tl.load(random_samples_ptr + pid_nc * 3).to(tl.float32)
    sample_h = tl.load(random_samples_ptr + pid_nc * 3 + 1).to(tl.float32)
    sample_w = tl.load(random_samples_ptr + pid_nc * 3 + 2).to(tl.float32)

    h_mask = h_out_offsets < out_h
    w_mask = w_out_offsets < out_w

    # Compute start positions inline for H and W dimensions
    sample_alpha_h = (sample_h * alpha_h).to(tl.int32)
    sample_alpha_w = (sample_w * alpha_w).to(tl.int32)

    h_starts = ((h_out_offsets.to(tl.float32) + sample_h) * alpha_h).to(
        tl.int32
    ) - sample_alpha_h
    w_starts = ((w_out_offsets.to(tl.float32) + sample_w) * alpha_w).to(
        tl.int32
    ) - sample_alpha_w

    # Override last position: start[output_size - 1] = input_size - pool_size
    h_starts = tl.where(h_out_offsets == out_h - 1, in_h - kernel_h, h_starts)
    w_starts = tl.where(w_out_offsets == out_w - 1, in_w - kernel_w, w_starts)

    # Compute D start position for this d_idx
    sample_alpha_d = (sample_d * alpha_d).to(tl.int32)
    d_start = ((d_idx.to(tl.float32) + sample_d) * alpha_d).to(
        tl.int32
    ) - sample_alpha_d
    # Override last D position
    d_start = tl.where(d_idx == out_d - 1, in_d - kernel_d, d_start)

    max_val_acc = tl.full((BLOCK_H, BLOCK_W), min_val, dtype=dtype)
    max_idx_acc = tl.full((BLOCK_H, BLOCK_W), -1, dtype=tl.int64)

    h_base = h_starts[:, None]
    w_base = w_starts[None, :]

    for kd in range(kernel_d):
        d_in = d_start + kd
        for kh in range(kernel_h):
            for kw in range(kernel_w):
                h_in = h_base + kh
                w_in = w_base + kw

                in_mask = (
                    h_mask[:, None]
                    & w_mask[None, :]
                    & (d_in >= 0)
                    & (d_in < in_d)
                    & (h_in >= 0)
                    & (h_in < in_h)
                    & (w_in >= 0)
                    & (w_in < in_w)
                )

                input_offset = (
                    d_in * in_stride_d + h_in * in_stride_h + w_in * in_stride_w
                )
                current_val = tl.load(
                    input_base_ptr + input_offset, mask=in_mask, other=min_val
                )
                current_idx = d_in * in_h * in_w + h_in * in_w + w_in

                update_mask = current_val > max_val_acc
                max_val_acc = tl.where(update_mask, current_val, max_val_acc)
                max_idx_acc = tl.where(update_mask, current_idx, max_idx_acc)

    # Write output and indices
    out_nc_offset = pid_nc * out_d * out_h * out_w
    out_offsets = (
        out_nc_offset
        + d_idx * out_h * out_w
        + h_out_offsets[:, None] * out_w
        + w_out_offsets[None, :]
    )
    out_mask = h_mask[:, None] & w_mask[None, :]
    tl.store(output_ptr + out_offsets, max_val_acc, mask=out_mask)
    tl.store(indices_ptr + out_offsets, max_idx_acc, mask=out_mask)


def fractional_max_pool3d(
    input: torch.Tensor,
    kernel_size,
    output_size=None,
    output_ratio=None,
    return_indices: bool = True,
    _random_samples=None,
):
    """Fractional max pooling 3d operation.

    Applies fractional max pooling over a 3D input signal using stochastic
    pooling regions determined by random_samples.

    Args:
        input: Input tensor of shape (N, C, D, H, W).
        kernel_size: Size of the pooling kernel.
        output_size: Target output spatial size (D_out, H_out, W_out).
        output_ratio: Alternative to output_size, specifies output as ratio.
        return_indices: Whether to return the max indices.
        _random_samples: Optional tensor of shape (N, C, 3) with values in [0, 1).
    """
    logger.debug("GEMS FRACTIONAL_MAX_POOL3D")
    assert input.dim() == 5, f"Expected 5D input, got {input.dim()}D"

    in_n, in_c, in_d, in_h, in_w = input.shape
    input = input.contiguous()

    if isinstance(kernel_size, int):
        kernel_d = kernel_h = kernel_w = kernel_size
    else:
        kernel_d, kernel_h, kernel_w = kernel_size

    if output_size is not None:
        if isinstance(output_size, int):
            out_d = out_h = out_w = output_size
        else:
            out_d, out_h, out_w = output_size
    elif output_ratio is not None:
        if isinstance(output_ratio, float):
            out_d = int(in_d * output_ratio)
            out_h = int(in_h * output_ratio)
            out_w = int(in_w * output_ratio)
        else:
            out_d = int(in_d * output_ratio[0])
            out_h = int(in_h * output_ratio[1])
            out_w = int(in_w * output_ratio[2])
    else:
        raise ValueError("Either output_size or output_ratio must be specified")

    assert out_d + kernel_d - 1 <= in_d, (
        f"fractional_max_pool3d: kernel_d ({kernel_d}) + output_d ({out_d}) - 1 "
        f"exceeds input_d ({in_d})"
    )
    assert out_h + kernel_h - 1 <= in_h, (
        f"fractional_max_pool3d: kernel_h ({kernel_h}) + output_h ({out_h}) - 1 "
        f"exceeds input_h ({in_h})"
    )
    assert out_w + kernel_w - 1 <= in_w, (
        f"fractional_max_pool3d: kernel_w ({kernel_w}) + output_w ({out_w}) - 1 "
        f"exceeds input_w ({in_w})"
    )

    # Generate or validate random samples
    if _random_samples is None:
        _random_samples = torch.rand(in_n, in_c, 3, device=input.device)
    else:
        assert _random_samples.shape == (in_n, in_c, 3), (
            f"_random_samples must have shape ({in_n}, {in_c}, 3), "
            f"got {_random_samples.shape}"
        )

    # Reshape to [N*C, 3] contiguous for kernel access
    random_samples_flat = _random_samples.reshape(in_n * in_c, 3).contiguous()

    # Precompute alpha values for interval generation
    alpha_d = (in_d - kernel_d) / (out_d - 1) if out_d > 1 else 0.0
    alpha_h = (in_h - kernel_h) / (out_h - 1) if out_h > 1 else 0.0
    alpha_w = (in_w - kernel_w) / (out_w - 1) if out_w > 1 else 0.0

    output = torch.empty(
        in_n, in_c, out_d, out_h, out_w, dtype=input.dtype, device=input.device
    )
    indices = torch.empty(
        in_n, in_c, out_d, out_h, out_w, dtype=torch.int64, device=input.device
    )

    if output.numel() == 0:
        return (output, indices) if return_indices else output

    grid = lambda meta: (
        in_n * in_c,
        out_d
        * triton.cdiv(out_h, meta["BLOCK_H"])
        * triton.cdiv(out_w, meta["BLOCK_W"]),
    )

    fractional_max_pool3d_forward_kernel[grid](
        input,
        output,
        indices,
        random_samples_flat,
        input.stride(0),
        input.stride(1),
        input.stride(2),
        input.stride(3),
        input.stride(4),
        in_c,
        in_d,
        in_h,
        in_w,
        out_d,
        out_h,
        out_w,
        alpha_d,
        alpha_h,
        alpha_w,
        kernel_d,
        kernel_h,
        kernel_w,
    )

    if return_indices:
        return output, indices
    return output
