# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def hamming_window_kernel(
    out_ptr,
    window_length,
    scale,
    alpha,
    beta,
    LOW_PRECISION: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = ext.program_id(0)
    idx = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = idx < window_length

    dtype = out_ptr.dtype.element_ty

    if LOW_PRECISION:
        # Mirror torch's computation op-by-op. torch evaluates each elementary
        # op (arange, mul, cos, ...) in the output dtype, rounding the result of
        # every step. tl.cos requires fp32, so we compute in fp32 but round back
        # to the output dtype after each step to reproduce torch's results
        # bit-for-bit (observable for float16 / bfloat16).
        n = idx.to(dtype).to(tl.float32)  # arange in output dtype
        x = (n * scale).to(dtype).to(tl.float32)  # x = n * (pi / (N - 1))
        # hamming: alpha - beta * cos(2x)
        x2 = (x * 2.0).to(dtype).to(tl.float32)  # 2x
        c = tl.cos(x2.to(dtype).to(tl.float32)).to(dtype).to(tl.float32)  # cos(2x)
        term = (c * beta).to(dtype).to(tl.float32)  # beta * cos(2x)
        val = (alpha - term).to(dtype)  # alpha - term
    else:
        # fp32 / fp64: compute directly in the native dtype (tl.cos supports
        # both), keeping full precision.
        n = idx.to(dtype)
        x = n * scale
        val = (alpha - beta * tl.cos(2.0 * x)).to(dtype)

    tl.store(out_ptr + idx, val, mask=mask)


def hamming_window(
    window_length,
    periodic=True,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    pin_memory=None,
):
    logger.debug("GEMS HAMMING_WINDOW")
    assert window_length >= 0, "window_length must be non-negative"

    if dtype is None:
        dtype = torch.get_default_dtype()
    assert dtype.is_floating_point, "hamming_window only supports floating point dtype"

    if layout != torch.strided:
        raise ValueError("Only strided layout is supported for hamming_window.")

    if device is None:
        device = torch.device(runtime.device.name)
    else:
        device = torch.device(device)

    # CPU fallback: Triton kernels require CUDA device
    if device.type == "cpu":
        return torch.hamming_window(
            window_length,
            periodic=periodic,
            dtype=dtype,
            layout=layout,
            device=device,
            pin_memory=pin_memory,
        )

    out = torch.empty(
        (window_length,),
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )

    if window_length == 0:
        return out
    if window_length == 1:
        return torch.fill(out, 1.0)

    # Default Hamming window coefficients
    alpha = 0.54
    beta = 0.46

    # For periodic windows the effective full size N is window_length + 1.
    full_length = window_length + 1 if periodic else window_length
    scale = math.pi / (full_length - 1)

    low_precision = dtype in (torch.float16, torch.bfloat16)
    # 1024 elements per program: a standard 1D launch block that balances
    # occupancy and register pressure for this elementwise window fill.
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(window_length, BLOCK_SIZE),)
    hamming_window_kernel[grid](
        out, window_length, scale, alpha, beta, low_precision, BLOCK_SIZE=BLOCK_SIZE
    )
    return out


def hamming_window_periodic(
    window_length,
    periodic,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    pin_memory=None,
):
    return hamming_window(
        window_length,
        periodic,
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )


def hamming_window_periodic_alpha(
    window_length,
    periodic,
    alpha,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    pin_memory=None,
):
    logger.debug("GEMS HAMMING_WINDOW_PERIODIC_ALPHA")
    assert window_length >= 0, "window_length must be non-negative"

    if dtype is None:
        dtype = torch.get_default_dtype()
    assert dtype.is_floating_point, "hamming_window only supports floating point dtype"

    if layout != torch.strided:
        raise ValueError("Only strided layout is supported for hamming_window.")

    if device is None:
        device = torch.device(runtime.device.name)
    else:
        device = torch.device(device)

    # CPU fallback: Triton kernels require CUDA device
    if device.type == "cpu":
        return torch.hamming_window(
            window_length,
            periodic=periodic,
            alpha=alpha,
            dtype=dtype,
            layout=layout,
            device=device,
            pin_memory=pin_memory,
        )

    out = torch.empty(
        (window_length,),
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )

    if window_length == 0:
        return out
    if window_length == 1:
        return torch.fill(out, 1.0)

    # PyTorch uses a fixed beta of 0.46 regardless of the alpha argument.
    beta = 0.46

    full_length = window_length + 1 if periodic else window_length
    scale = math.pi / (full_length - 1)

    low_precision = dtype in (torch.float16, torch.bfloat16)
    # 1024 elements per program: a standard 1D launch block that balances
    # occupancy and register pressure for this elementwise window fill.
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(window_length, BLOCK_SIZE),)
    hamming_window_kernel[grid](
        out, window_length, scale, alpha, beta, low_precision, BLOCK_SIZE=BLOCK_SIZE
    )
    return out


def hamming_window_periodic_alpha_beta(
    window_length,
    periodic,
    alpha,
    beta,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    pin_memory=None,
):
    logger.debug("GEMS HAMMING_WINDOW_PERIODIC_ALPHA_BETA")
    assert window_length >= 0, "window_length must be non-negative"

    if dtype is None:
        dtype = torch.get_default_dtype()
    assert dtype.is_floating_point, "hamming_window only supports floating point dtype"

    if layout != torch.strided:
        raise ValueError("Only strided layout is supported for hamming_window.")

    if device is None:
        device = torch.device(runtime.device.name)
    else:
        device = torch.device(device)

    # CPU fallback: Triton kernels require CUDA device
    if device.type == "cpu":
        return torch.hamming_window(
            window_length,
            periodic=periodic,
            alpha=alpha,
            beta=beta,
            dtype=dtype,
            layout=layout,
            device=device,
            pin_memory=pin_memory,
        )

    out = torch.empty(
        (window_length,),
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )

    if window_length == 0:
        return out
    if window_length == 1:
        return torch.fill(out, 1.0)

    full_length = window_length + 1 if periodic else window_length
    scale = math.pi / (full_length - 1)

    low_precision = dtype in (torch.float16, torch.bfloat16)
    # 1024 elements per program: a standard 1D launch block that balances
    # occupancy and register pressure for this elementwise window fill.
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(window_length, BLOCK_SIZE),)
    hamming_window_kernel[grid](
        out, window_length, scale, alpha, beta, low_precision, BLOCK_SIZE=BLOCK_SIZE
    )
    return out
