# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import builtins
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def histogramdd_kernel(
    input_ptr,
    hist_ptr,
    edge_mins_ptr,  # Array of min values per dimension
    edge_maxs_ptr,  # Array of max values per dimension
    N,
    D,
    bins_ptr,  # Array of bin counts per dimension
    BLOCK_SIZE: tl.constexpr,
):
    """
    Compute D-dimensional histogram. Each thread processes one input point.

    For each (N, D) input point, compute its D-dimensional bin index and
    atomically increment the corresponding histogram cell.
    """
    pid = ext.program_id(0)

    # For each point, compute multi-dimensional bin index
    for i in range(BLOCK_SIZE):
        point_idx = pid * BLOCK_SIZE + i

        # Only process if within bounds
        if point_idx < N:
            linear_bin_idx = 0
            stride = 1
            in_range = True

            # Iterate dimensions in reverse order for row-major indexing
            for d in range(D - 1, -1, -1):
                # Load value for this dimension
                val = tl.load(input_ptr + point_idx * D + d)

                # Load bin count for this dimension
                num_bins = tl.load(bins_ptr + d).to(tl.int32)

                # Load edge boundaries for this dimension
                edge_min = tl.load(edge_mins_ptr + d)
                edge_max = tl.load(edge_maxs_ptr + d)

                # Check if value is in range (val != val checks for NaN)
                # Note: edge_max is inclusive (values exactly at edge_max are valid)
                is_nan = val != val
                in_range = in_range and not (val < edge_min or val > edge_max or is_nan)

                # Compute bin index using binary search approximation
                # For uniform bins: bin_idx = floor((val - min) / bin_width)
                bin_width = (edge_max - edge_min) / num_bins
                bin_idx = tl.floor((val - edge_min) / bin_width).to(tl.int32)

                # Clamp to valid range and handle right edge
                # Values exactly at edge_max should go into the last bin (num_bins - 1)
                bin_idx = tl.where(val >= edge_max, num_bins - 1, bin_idx)
                bin_idx = tl.maximum(0, tl.minimum(num_bins - 1, bin_idx))

                # Accumulate linear index (row-major order)
                linear_bin_idx += bin_idx * stride
                stride *= num_bins

            # Atomically increment histogram if point is in range
            if in_range:
                tl.atomic_add(hist_ptr + linear_bin_idx, 1.0, sem="relaxed")


def histogramdd(input, bins, range=None, weight=None, density=False):
    """
    Compute D-dimensional histogram of input tensor.

    Args:
        input: Input tensor of shape (N, D) where N is number of points, D is dimensions
        bins: List of int specifying number of bins per dimension
        range: Optional list of [min0, max0, min1, max1, ...] for D dimensions
        weight: Optional weight tensor of shape (N,)
        density: If True, normalize to probability density

    Returns:
        tuple: (hist, bin_edges) where hist has shape (bins[0], bins[1], ..., bins[D-1])
               and bin_edges is a list of D edge tensors
    """
    logger.debug("GEMS HISTOGRAMDD")

    if input.dtype not in [torch.float32, torch.float64]:
        raise NotImplementedError(
            f"histogramdd not implemented for dtype {input.dtype}. "
            "Only float32 and float64 are supported."
        )

    if input.dim() != 2:
        raise ValueError(
            f"histogramdd requires 2D input (N, D), got shape {input.shape}"
        )

    N, D = input.shape
    if D < 2:
        raise ValueError(f"histogramdd requires at least 2 dimensions, got D={D}")

    if len(bins) != D:
        raise ValueError(f"bins length {len(bins)} must match input dimensions {D}")

    if weight is not None:
        if weight.shape != (N,):
            raise ValueError(f"weight must have shape ({N},), got {weight.shape}")
        if weight.dtype != input.dtype:
            raise ValueError(
                f"weight dtype {weight.dtype} must match input dtype {input.dtype}"
            )
        raise NotImplementedError("weighted histogramdd not yet implemented")

    # Ensure input is contiguous
    input = input.contiguous()

    # Compute bin edges for each dimension
    # Store range parameter to avoid shadowing builtin range()
    range_vals = range
    bin_edges = []
    for d in builtins.range(D):
        dim_data = input[:, d]
        num_bins = bins[d]

        if range_vals is not None:
            dim_min = float(range_vals[2 * d])
            dim_max = float(range_vals[2 * d + 1])
        else:
            # For empty input, use default range [0, 1]
            if N == 0:
                dim_min = 0.0
                dim_max = 1.0
            else:
                dim_min = float(dim_data.min().item())
                dim_max = float(dim_data.max().item())

        # Handle degenerate range (all values equal)
        if dim_min == dim_max:
            edges = torch.linspace(
                dim_min - 0.5,
                dim_min + 0.5,
                num_bins + 1,
                dtype=input.dtype,
                device=input.device,
            )
        else:
            edges = torch.linspace(
                dim_min, dim_max, num_bins + 1, dtype=input.dtype, device=input.device
            )

        bin_edges.append(edges)

    # Create output histogram tensor
    hist_shape = tuple(bins)
    hist = torch.zeros(hist_shape, dtype=input.dtype, device=input.device)

    if N == 0:
        return hist, bin_edges

    # Prepare bins array and edge min/max for kernel
    bins_tensor = torch.tensor(bins, dtype=torch.int32, device=input.device)

    # Extract min and max values from each edge tensor
    edge_mins = torch.tensor(
        [edge[0].item() for edge in bin_edges], dtype=input.dtype, device=input.device
    )
    edge_maxs = torch.tensor(
        [edge[-1].item() for edge in bin_edges], dtype=input.dtype, device=input.device
    )

    # Launch kernel
    BLOCK_SIZE = 256
    grid = (triton.cdiv(N, BLOCK_SIZE),)

    with torch_device_fn.device(input.device):
        histogramdd_kernel[grid](
            input,
            hist,
            edge_mins,
            edge_maxs,
            N,
            D,
            bins_tensor,
            BLOCK_SIZE=BLOCK_SIZE,
        )

    # Apply density normalization if requested
    if density:
        # Compute bin volumes
        bin_volumes = torch.ones_like(hist)
        for d in builtins.range(D):
            widths = bin_edges[d][1:] - bin_edges[d][:-1]
            # Broadcast widths along dimension d
            shape = [1] * D
            shape[d] = bins[d]
            widths_shaped = widths.reshape(shape)
            bin_volumes = bin_volumes * widths_shaped

        total_count = hist.sum()
        if total_count > 0:
            hist = hist / total_count / bin_volumes
        else:
            # All points were out of range; density is undefined (NaN)
            hist = hist / bin_volumes  # 0/vol = 0, will be NaN if needed

    return hist, bin_edges
