# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import device

logger = logging.getLogger(__name__)

device = device.name


@triton.jit
def is_same_size_kernel(
    self_shape_ptr,
    other_shape_ptr,
    out_ptr,
    ndim,
    BLOCK_SIZE: tl.constexpr,
):
    """Compare two shape vectors elementwise and reduce to a single flag.

    Both shapes are already known to have the same length when this launches,
    so the comparison is a masked load of each shape vector followed by an
    ``and`` reduction. This is the actual work of ``is_same_size`` -- deciding
    whether every dimension matches -- evaluated on device rather than in
    host-side Python.
    """
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = offsets < ndim

    # Out-of-range lanes load 0 on both sides so they compare equal and stay
    # neutral under the `and` reduction below.
    self_dims = tl.load(self_shape_ptr + offsets, mask=mask, other=0)
    other_dims = tl.load(other_shape_ptr + offsets, mask=mask, other=0)

    same = tl.min((self_dims == other_dims).to(tl.int32), axis=0)
    tl.store(out_ptr, same)


def is_same_size(self: torch.Tensor, other: torch.Tensor) -> bool:
    """Implements ``aten::is_same_size(Tensor self, Tensor other) -> bool``.

    Returns whether the two tensors have identical shapes. Ranks are compared
    on the host because a rank mismatch already settles the answer and the two
    shape vectors would not be the same length; when the ranks agree, the
    per-dimension comparison is performed by a Triton kernel.
    """
    logger.debug("GEMS IS_SAME_SIZE")

    self_shape = tuple(self.shape)
    other_shape = tuple(other.shape)

    # Differing ranks are never the same size, and there is nothing for the
    # kernel to compare.
    if len(self_shape) != len(other_shape):
        return False

    ndim = len(self_shape)

    # Two 0-dim tensors both have an empty shape, so they are trivially equal.
    if ndim == 0:
        return True

    self_shape_t = torch.tensor(self_shape, dtype=torch.int64, device=device)
    other_shape_t = torch.tensor(other_shape, dtype=torch.int64, device=device)
    out = torch.empty((), dtype=torch.int32, device=device)

    # One block covers the whole shape vector: tensor ranks are small, and
    # PyTorch itself caps them well below this bound.
    BLOCK_SIZE = triton.next_power_of_2(ndim)

    is_same_size_kernel[(1,)](
        self_shape_t,
        other_shape_t,
        out,
        ndim,
        BLOCK_SIZE=BLOCK_SIZE,
    )

    return bool(out.item())
