# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.copy import copy_
from flag_gems.ops.neg import neg
from flag_gems.ops.zeros_like import zeros_like
from flag_gems.utils import pointwise_dynamic, tl_extra_shim
from flag_gems.utils.shape_utils import MemOverlap, has_internal_overlapping

_exp2 = tl_extra_shim.exp2


@triton.jit
def _ldexp_fallback(x, exponent):
    return x * tl.exp2(exponent.to(x.dtype))


_ldexp = getattr(tl_extra_shim, "ldexp", _ldexp_fallback)

logger = logging.getLogger(__name__)

_WRAP_INTEGER_EXPONENT = tuple(map(int, torch.__version__.split(".")[:2])) >= (2, 11)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def ldexp_inplace_func(x, other):
    return x.to(tl.float32) * _exp2(other.to(tl.float32))


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def ldexp_inplace_fp64_func(x, other):
    return x.to(tl.float64) * _exp2(other.to(tl.float64))


@pointwise_dynamic(is_tensor=[True, True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def ldexp_inplace_integral_func(x, other, wrap_exponent: tl.constexpr):
    exponent = other.to(tl.int32)
    if not wrap_exponent:
        exponent = tl.maximum(tl.minimum(other, 2147483647), -2147483648).to(tl.int32)
    return _ldexp(x.to(tl.float32), exponent)


@pointwise_dynamic(is_tensor=[True, True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def ldexp_inplace_integral_fp64_func(x, other, wrap_exponent: tl.constexpr):
    exponent = other.to(tl.int32)
    if not wrap_exponent:
        exponent = tl.maximum(tl.minimum(other, 2147483647), -2147483648).to(tl.int32)
    return _ldexp(x.to(tl.float64), exponent)


@pointwise_dynamic(
    is_tensor=[True, True, True, True],
    num_outputs=2,
    promotion_methods=[
        (0, 1, 2, 3, "INT_TO_FLOAT"),
        (0, 1, 2, 3, "INT_TO_FLOAT"),
    ],
)
@triton.jit
def ldexp_inplace_complex_func(xr, xi, yr, yi):
    xr = xr.to(tl.float32)
    xi = xi.to(tl.float32)
    yr = yr.to(tl.float32)
    yi = yi.to(tl.float32)
    scale = _exp2(yr)
    angle = yi * 0.6931471805599453
    cos_angle = tl.cos(angle)
    sin_angle = tl.sin(angle)
    pr = scale * cos_angle
    pi = tl.where(yi == 0, 0, scale * sin_angle)
    return xr * pr - xi * pi, xr * pi + xi * pr


@pointwise_dynamic(
    is_tensor=[True, True, True, True],
    num_outputs=2,
    promotion_methods=[
        (0, 1, 2, 3, "INT_TO_FLOAT"),
        (0, 1, 2, 3, "INT_TO_FLOAT"),
    ],
)
@triton.jit
def ldexp_inplace_complex_fp64_func(xr, xi, yr, yi):
    xr = xr.to(tl.float64)
    xi = xi.to(tl.float64)
    yr = yr.to(tl.float64)
    yi = yi.to(tl.float64)
    scale = _exp2(yr)
    angle = yi * 0.693147180559945309417232121458176568
    cos_angle = tl.cos(angle)
    sin_angle = tl.sin(angle)
    pr = scale * cos_angle
    pi = tl.where(yi == 0, 0, scale * sin_angle)
    return xr * pr - xi * pi, xr * pi + xi * pr


@pointwise_dynamic(
    is_tensor=[True, True, True],
    num_outputs=2,
    promotion_methods=[
        (0, 1, 2, "DEFAULT"),
        (0, 1, 2, "DEFAULT"),
    ],
)
@triton.jit
def ldexp_inplace_complex_integral_func(xr, xi, other):
    xr = xr.to(tl.float32)
    xi = xi.to(tl.float32)
    scale = _exp2(other.to(tl.float32))
    return xr * scale - xi * 0.0, xr * 0.0 + xi * scale


@pointwise_dynamic(
    is_tensor=[True, True, True],
    num_outputs=2,
    promotion_methods=[
        (0, 1, 2, "DEFAULT"),
        (0, 1, 2, "DEFAULT"),
    ],
)
@triton.jit
def ldexp_inplace_complex_integral_fp64_func(xr, xi, other):
    xr = xr.to(tl.float64)
    xi = xi.to(tl.float64)
    scale = _exp2(other.to(tl.float64))
    return xr * scale - xi * 0.0, xr * 0.0 + xi * scale


def _result_dtype(self, other):
    self_dtype = (
        torch.float32
        if self.dtype == torch.bool
        or (not self.is_floating_point() and not self.is_complex())
        else self.dtype
    )
    return torch.promote_types(self_dtype, other.dtype)


def _complex_parts(tensor, real_dtype):
    if tensor.is_complex():
        physical = tensor.conj() if tensor.is_conj() else tensor
        parts = torch.view_as_real(physical)
        real = torch.empty(tensor.shape, dtype=real_dtype, device=tensor.device)
        imag = torch.empty_like(real)
        copy_(real, parts[..., 0])
        copy_(imag, neg(parts[..., 1]) if tensor.is_conj() else parts[..., 1])
        return real, imag
    real = torch.empty(tensor.shape, dtype=real_dtype, device=tensor.device)
    copy_(real, tensor)
    return real, zeros_like(real)


def _write_complex(self, real, imag):
    physical = self.conj() if self.is_conj() else self
    output = torch.view_as_real(physical)
    copy_(output[..., 0], real)
    copy_(output[..., 1], neg(imag) if self.is_conj() else imag)


def _ldexp_complex_(self, other):
    promoted = _result_dtype(self, other)
    real_dtype = torch.float64 if promoted == torch.complex128 else torch.float32
    xr, xi = _complex_parts(self, real_dtype)
    yr, yi = _complex_parts(other, real_dtype)
    func = (
        ldexp_inplace_complex_fp64_func
        if promoted == torch.complex128
        else ldexp_inplace_complex_func
    )
    real, imag = func(xr, xi, yr, yi)
    _write_complex(self, real, imag)


def _ldexp_complex_integral_(self, other):
    real_dtype = torch.float64 if self.dtype == torch.complex128 else torch.float32
    xr, xi = _complex_parts(self, real_dtype)
    func = (
        ldexp_inplace_complex_integral_fp64_func
        if self.dtype == torch.complex128
        else ldexp_inplace_complex_integral_func
    )
    real, imag = func(xr, xi, other)
    _write_complex(self, real, imag)


def _is_exact_alias(left, right):
    return (
        left.data_ptr() == right.data_ptr()
        and left.storage_offset() == right.storage_offset()
        and left.shape == right.shape
        and left.stride() == right.stride()
    )


def ldexp_(self, other):
    logger.debug("GEMS LDEXP_")
    if has_internal_overlapping(self) == MemOverlap.Yes:
        raise RuntimeError(
            "unsupported operation: more than one element of the written-to tensor "
            "refers to a single memory location"
        )
    if (
        self.device == other.device
        and self.untyped_storage().nbytes() > 0
        and self.untyped_storage().data_ptr() == other.untyped_storage().data_ptr()
        and not _is_exact_alias(self, other)
    ):
        temporary = torch.empty_like(other)
        if other.is_complex():
            real, imag = _complex_parts(
                other,
                torch.float64 if other.dtype == torch.complex128 else torch.float32,
            )
            _write_complex(temporary, real, imag)
        else:
            copy_(temporary, other)
        other = temporary

    result_dtype = _result_dtype(self, other)
    if not torch.can_cast(result_dtype, self.dtype):
        raise RuntimeError(
            f"result type {result_dtype} can't be cast to the desired output "
            f"type {self.dtype}"
        )

    output_shape = torch.broadcast_shapes(self.shape, other.shape)
    if output_shape != self.shape:
        raise RuntimeError(
            f"output with shape {self.shape} doesn't match the broadcast shape "
            f"{output_shape}"
        )

    integral_exponent = not other.is_floating_point() and not other.is_complex()
    if self.is_complex():
        if integral_exponent:
            _ldexp_complex_integral_(self, other)
        else:
            _ldexp_complex_(self, other)
    else:
        if integral_exponent:
            func = (
                ldexp_inplace_integral_fp64_func
                if result_dtype == torch.float64
                else ldexp_inplace_integral_func
            )
        else:
            func = (
                ldexp_inplace_fp64_func
                if result_dtype == torch.float64
                else ldexp_inplace_func
            )
        if integral_exponent:
            func(self, other, _WRAP_INTEGER_EXPONENT, out0=self)
        else:
            func(self, other, out0=self)
    return self
