# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def ldl_factor_kernel(A, LD, N, batch_stride, row_stride, col_stride):
    # Each program processes one matrix
    pid = tl.program_id(0)

    # Compute the offset for this matrix in the batch
    A_ptr = A + pid * batch_stride
    LD_ptr = LD + pid * batch_stride

    # Sequential LDL Factorization

    # First pass: compute diagonal D elements (D[j,j])
    # and lower triangular L elements (L[i,j] for i > j)

    for j in range(N):
        # ===== Compute D[j,j] = A[j,j] - sum(L[j,k]^2 * D[k,k]) for k < j =====
        d_jj = tl.load(A_ptr + j * row_stride + j * col_stride).to(tl.float32)

        # Subtract contributions from previous columns
        for k in range(j):
            l_jk = tl.load(LD_ptr + j * row_stride + k * col_stride)
            d_kk = tl.load(LD_ptr + k * row_stride + k * col_stride)
            d_jj = d_jj - l_jk * l_jk * d_kk

        # Store D[j,j] at position (j,j)
        tl.store(LD_ptr + j * row_stride + j * col_stride, d_jj)

        # ===== Compute L[i,j] for all i > j =====
        # L[i,j] = (A[i,j] - sum(L[i,k] * D[k,k] * L[j,k])) / D[j,j]
        for i in range(j + 1, N):
            # Get A[i,j] - note A is symmetric so A[i,j] = A[j,i]
            a_ij = tl.load(A_ptr + i * row_stride + j * col_stride).to(tl.float32)

            # Compute sum over k < j
            sum_val = 0.0
            for k in range(j):
                l_i_k = tl.load(LD_ptr + i * row_stride + k * col_stride)
                d_kk = tl.load(LD_ptr + k * row_stride + k * col_stride)
                l_j_k = tl.load(LD_ptr + j * row_stride + k * col_stride)
                sum_val = sum_val + l_i_k * d_kk * l_j_k

            # Compute L[i,j]
            l_ij = (a_ij - sum_val) / d_jj
            tl.store(LD_ptr + i * row_stride + j * col_stride, l_ij)


@libentry()
@triton.jit
def ldl_init_pivots_kernel(pivots, N, stride):
    row = tl.program_id(0)
    matrix_idx = row // N
    col = row % N
    if col < N:
        # PyTorch uses 1-indexed pivots
        tl.store(pivots + matrix_idx * stride + col, col + 1)


@libentry()
@triton.jit
def ldl_init_info_kernel(info):
    # info = 0 means success
    tl.store(info, 0)


def ldl_factor_ex(A, hermitian=False, check_errors=False):
    """LDL factorization with extended info.

    Returns (LD, pivots, info) where:
    - LD: lower triangular matrix with diagonal elements
    - pivots: 1-indexed pivot indices
    - info: 0 if successful, positive integer if diagonal element of D is zero
    """
    logger.debug("GEMS LINALG_LDL_FACTOR_EX")

    LD = torch.empty_like(A)
    pivots = torch.empty(*A.shape[:-1], dtype=torch.int32, device=A.device)
    info = torch.empty(A.shape[:-2], dtype=torch.int32, device=A.device)
    return torch.ops.aten.linalg_ldl_factor_ex.out(
        A,
        hermitian=hermitian,
        check_errors=check_errors,
        LD=LD,
        pivots=pivots,
        info=info,
    )
