# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

from .contiguous import contiguous

logger = logging.getLogger(__name__)

_REGISTER_TILE_LIMIT = 32


@libentry()
@triton.jit
def _logdet_register_kernel(
    inp,
    out,
    n: tl.constexpr,
    block_n: tl.constexpr,
):
    pid = tle.program_id(0)
    rows = tl.arange(0, block_n)
    cols = tl.arange(0, block_n)
    mask = (rows[:, None] < n) & (cols[None, :] < n)
    offsets = pid * n * n + rows[:, None] * n + cols[None, :]
    work = tl.load(inp + offsets, mask=mask, other=0.0)

    swap_count = tl.zeros((), dtype=tl.int32)
    singular = tl.zeros((), dtype=tl.int1)

    for k in range(n):
        column = tl.sum(tl.where(cols[None, :] == k, work, 0.0), axis=1)
        abs_column = tl.where((rows >= k) & (rows < n), tl.abs(column), -float("inf"))
        pivot_abs = tl.max(abs_column, axis=0)
        pivot_row = tl.min(tl.where(abs_column == pivot_abs, rows, block_n), axis=0)
        singular |= pivot_abs == 0.0

        row_k = tl.sum(tl.where(rows[:, None] == k, work, 0.0), axis=0)
        row_p = tl.sum(tl.where(rows[:, None] == pivot_row, work, 0.0), axis=0)
        work = tl.where(rows[:, None] == k, row_p[None, :], work)
        work = tl.where(rows[:, None] == pivot_row, row_k[None, :], work)
        swap_count += pivot_row != k

        column = tl.sum(tl.where(cols[None, :] == k, work, 0.0), axis=1)
        pivot = tl.sum(tl.where(rows == k, column, 0.0), axis=0)
        safe_pivot = tl.where(pivot == 0.0, 1.0, pivot)
        multiplier = tl.where(rows > k, column / safe_pivot, 0.0)
        pivot_row_values = row_p
        update_mask = (rows[:, None] > k) & (cols[None, :] > k)
        update = tl.where(
            multiplier[:, None] == 0.0,
            0.0,
            multiplier[:, None] * pivot_row_values[None, :],
        )
        work = tl.where(
            update_mask,
            work - update,
            work,
        )

    diagonal = tl.sum(tl.where(rows[:, None] == cols[None, :], work, 0.0), axis=0)
    valid_diagonal = cols < n
    singular |= tl.sum(tl.where(valid_diagonal & (diagonal == 0.0), 1, 0), axis=0) > 0
    negative_count = tl.sum(tl.where(valid_diagonal & (diagonal < 0.0), 1, 0), axis=0)
    negative = (negative_count + swap_count) % 2 != 0
    logabsdet = tl.sum(tl.where(valid_diagonal, tl.log(tl.abs(diagonal)), 0.0), axis=0)

    result = tl.where(negative, float("nan"), logabsdet)
    result = tl.where(singular, -float("inf"), result)
    tl.store(out + pid, result)


def logdet(inp):
    logger.debug("GEMS LOGDET")

    if inp.dim() < 2 or inp.shape[-1] != inp.shape[-2]:
        raise RuntimeError("logdet: input must be batches of square matrices")
    if inp.is_complex():
        raise RuntimeError("logdet: complex inputs are not supported by this kernel")
    if inp.requires_grad:
        raise RuntimeError("logdet: autograd is not supported by this kernel")
    if inp.dtype not in (torch.float32, torch.float64):
        raise RuntimeError(f"logdet: unsupported dtype {inp.dtype}")

    n = inp.shape[-1]
    batch_shape = inp.shape[:-2]
    batch_count = math.prod(batch_shape)

    if n == 0:
        return torch.zeros(batch_shape, dtype=inp.dtype, device=inp.device)
    if batch_count == 0:
        return torch.empty(batch_shape, dtype=inp.dtype, device=inp.device)
    fp64_unsupported = inp.dtype == torch.float64 and n > 16
    if n > _REGISTER_TILE_LIMIT or fp64_unsupported:
        raise RuntimeError(
            f"logdet: {inp.dtype} matrices of size {n} are not supported by "
            "the Triton kernel"
        )

    inp_contiguous = contiguous(inp).reshape(batch_count, n, n)
    out = torch.empty(batch_count, dtype=inp.dtype, device=inp.device)
    block_n = max(2, triton.next_power_of_2(n))
    num_warps = min(8, max(1, (block_n * block_n * inp.element_size()) // 4096))

    with torch_device_fn.device(inp.device):
        _logdet_register_kernel[(batch_count,)](
            inp_contiguous,
            out,
            n=n,
            block_n=block_n,
            num_warps=num_warps,
        )
    return out.reshape(batch_shape)
