# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

# activation string -> integer code consumed by the kernel
_ACT_MAP = {"none": 0, None: 0, "relu": 1, "silu": 2}


@triton.jit
def _mixed_dtypes_linear_kernel(
    x_ptr,
    w_ptr,
    scale_ptr,
    bias_ptr,
    out_ptr,
    M,
    N,
    K,
    ncols,
    stride_xm,
    stride_wn,
    stride_om,
    INT4: tl.constexpr,
    HAS_BIAS: tl.constexpr,
    ACT: tl.constexpr,  # 0: none, 1: relu, 2: silu
    EPI_SCALE: tl.constexpr,
    BM: tl.constexpr,
    BN: tl.constexpr,
    BK: tl.constexpr,
    GROUP_M: tl.constexpr,
):
    pid = tl.program_id(0)
    num_pid_m = tl.cdiv(M, BM)
    num_pid_n = tl.cdiv(N, BN)
    num_pid_in_group = GROUP_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_M
    group_size_m = tl.minimum(num_pid_m - first_pid_m, GROUP_M)
    pid_m = first_pid_m + ((pid % num_pid_in_group) % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    offs_m = pid_m * BM + tl.arange(0, BM)
    offs_n = pid_n * BN + tl.arange(0, BN)
    offs_k = tl.arange(0, BK)
    offs_am = tl.max_contiguous(tl.multiple_of(offs_m, BM), BM)

    m_mask = offs_m < M
    n_mask = offs_n < N

    x_ptrs = x_ptr + offs_am[:, None] * stride_xm + offs_k[None, :]
    if INT4:
        # Two 4-bit weights are packed per byte: low nibble -> even output
        # column, high nibble -> odd output column.
        offs_nb = pid_n * (BN // 2) + tl.arange(0, BN // 2)
        w_ptrs = w_ptr + offs_k[:, None] * stride_wn + offs_nb[None, :]
        w_mask_n = (offs_nb < ncols)[None, :]
    else:
        w_ptrs = w_ptr + offs_k[:, None] * stride_wn + offs_n[None, :]
        w_mask_n = n_mask[None, :]

    acc = tl.zeros((BM, BN), dtype=tl.float32)
    for _ in range(0, tl.cdiv(K, BK)):
        k_mask = offs_k < K
        a = tl.load(x_ptrs, mask=m_mask[:, None] & k_mask[None, :], other=0.0)
        w_mask = (offs_k[:, None] < K) & w_mask_n
        wb = tl.load(w_ptrs, mask=w_mask, other=0)
        wb32 = wb.to(tl.int32)
        if INT4:
            # FasterTransformer biased int4 converter: subtract 8.
            lo = (wb32 & 0xF) - 8
            hi = ((wb32 >> 4) & 0xF) - 8
            wi = tl.interleave(lo, hi)  # [BK, BN]
        else:
            # FasterTransformer biased int8 converter: subtract 128.
            wi = wb32 - 128
        if EPI_SCALE:
            # fp16: fold the per-column scale into the epilogue (fewer in-loop
            # ops); algebraically identical and within fp16 tolerance.
            wf = wi.to(a.dtype)
        else:
            # bf16: keep the per-tile scale multiply to match the reference
            # rounding boundary under strict bf16 tolerance.
            s = tl.load(scale_ptr + offs_n, mask=n_mask, other=0.0)
            wf = (wi.to(tl.float32) * s.to(tl.float32)[None, :]).to(a.dtype)
        acc = tl.dot(a, wf, acc)
        x_ptrs += BK
        w_ptrs += BK * stride_wn
        offs_k += BK

    if EPI_SCALE:
        s_epi = tl.load(scale_ptr + offs_n, mask=n_mask, other=0.0)
        acc = acc * s_epi.to(tl.float32)[None, :]

    if HAS_BIAS:
        b = tl.load(bias_ptr + offs_n, mask=n_mask, other=0.0)
        acc = acc + b.to(tl.float32)[None, :]
    if ACT == 1:
        acc = tl.maximum(acc, 0.0)
    elif ACT == 2:
        acc = acc * tl.sigmoid(acc)

    out_ptrs = out_ptr + offs_m[:, None] * stride_om + offs_n[None, :]
    tl.store(
        out_ptrs,
        acc.to(out_ptr.dtype.element_ty),
        mask=m_mask[:, None] & n_mask[None, :],
    )


def mixed_dtypes_linear(input, weight, scale, bias=None, activation=None):
    logger.debug("GEMS _MIXED_DTYPES_LINEAR")

    assert input.dtype in (
        torch.float16,
        torch.bfloat16,
    ), f"input must be float16 or bfloat16, got {input.dtype}"
    assert weight.dtype == torch.uint8, f"weight must be uint8, got {weight.dtype}"
    assert (
        scale.dtype == input.dtype
    ), f"scale dtype {scale.dtype} must match input dtype {input.dtype}"
    act = activation if activation is not None else "none"
    assert act in _ACT_MAP, f"unsupported activation: {activation}"

    orig = input.shape
    K = orig[-1]
    M = input.numel() // K
    N = scale.shape[0]
    ncols = weight.shape[1]
    # int8 mode: one byte per output column; int4-packed mode: two per byte.
    assert ncols == N or 2 * ncols == N, (
        f"weight columns {ncols} must equal scale size {N} (int8) "
        f"or half of it (packed int4)"
    )
    int4 = ncols != N

    out = torch.empty((*orig[:-1], N), dtype=input.dtype, device=input.device)

    epi_scale = input.dtype == torch.float16
    if (not epi_scale) and M >= 1024:
        # Large bf16 GEMM: amortize the per-tile dequant multiply over more rows.
        BM, BN, BK, GROUP_M, nstages = 256, 128, 64, 8, 3
    else:
        BM, BN, BK, GROUP_M, nstages = 128, 128, 64, 8, 4
    grid = (triton.cdiv(M, BM) * triton.cdiv(N, BN),)

    with torch_device_fn.device(input.device):
        _mixed_dtypes_linear_kernel[grid](
            input,
            weight,
            scale,
            bias if bias is not None else input,
            out,
            M,
            N,
            K,
            ncols,
            K,
            ncols,
            N,
            INT4=int4,
            HAS_BIAS=(bias is not None),
            ACT=_ACT_MAP[act],
            EPI_SCALE=epi_scale,
            BM=BM,
            BN=BN,
            BK=BK,
            GROUP_M=GROUP_M,
            num_warps=8,
            num_stages=nstages,
        )
    return out
