# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl
from torch import Tensor

from flag_gems.ops.contiguous import contiguous
from flag_gems.ops.copy import copy_
from flag_gems.ops.sort import sort_stable
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)

INTERPOLATION_METHODS = ("linear", "lower", "higher", "nearest", "midpoint")
INTERPOLATION_CODES = {name: code for code, name in enumerate(INTERPOLATION_METHODS)}
MAX_BITONIC_SIZE = 2048
MAX_REDUCTION_SIZE = 1 << 24


@libentry()
@triton.jit
def _sort_keys_kernel(inp, keys, n_elements, BLOCK_SIZE: tl.constexpr):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    values = tl.load(inp + offsets, mask=mask)
    tl.store(
        keys + offsets, tl.where(values == values, values, float("nan")), mask=mask
    )


@libentry()
@triton.jit
def _nanquantile_bitonic_kernel(
    inp,
    q,
    out,
    reduction_size,
    q_size,
    BLOCK_M: tl.constexpr,
    BLOCK_Q: tl.constexpr,
    interpolation: tl.constexpr,
):
    row = ext.program_id(0)
    compute_type = inp.dtype.element_ty
    cols = tl.arange(0, BLOCK_M)
    valid_col = cols < reduction_size
    values = tl.load(inp + row * reduction_size + cols, mask=valid_col, other=0.0)
    valid_value = valid_col & (values == values)
    sortable = tl.where(valid_value, values, float("inf"))
    if BLOCK_M == 1:
        sorted_values = sortable
    else:
        sorted_values = tl.sort(sortable, descending=False)
    valid_count = tl.sum(valid_value.to(tl.int32), axis=0)

    q_offsets = ext.program_id(1) * BLOCK_Q + tl.arange(0, BLOCK_Q)
    valid_q = q_offsets < q_size
    q_values = tl.load(q + q_offsets, mask=valid_q, other=0.0).to(compute_type)
    last_valid = tl.maximum(valid_count - 1, 0).to(compute_type)
    ranks = q_values * last_valid
    lower = tl.floor(ranks).to(tl.int32)
    upper = tl.ceil(ranks).to(tl.int32)
    value_offsets = tl.arange(0, BLOCK_M)[:, None]
    lower_values = tl.max(
        tl.where(
            value_offsets == lower[None, :], sorted_values[:, None], float("-inf")
        ),
        axis=0,
    )
    upper_values = tl.max(
        tl.where(
            value_offsets == upper[None, :], sorted_values[:, None], float("-inf")
        ),
        axis=0,
    )

    if interpolation == 0:
        result = lower_values + (upper_values - lower_values) * (ranks - lower)
    elif interpolation == 1:
        result = lower_values
    elif interpolation == 2:
        result = upper_values
    elif interpolation == 3:
        rounded = tl_extra_shim.rint(ranks).to(tl.int32)
        result = tl.where(rounded == upper, upper_values, lower_values)
    else:
        result = lower_values + (upper_values - lower_values) * 0.5

    result = tl.where(valid_count == 0, float("nan"), result)
    tl.store(out + row * q_size + q_offsets, result, mask=valid_q)


@libentry()
@triton.jit
def _validate_q_kernel(q, q_size, BLOCK_SIZE: tl.constexpr):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < q_size
    values = tl.load(q + offsets, mask=mask, other=0.0)
    valid = (~mask) | ((values >= 0.0) & (values <= 1.0))
    tl.device_assert(valid, "quantile() q values must be in the range [0, 1]")


def _heur_block_q(args):
    return triton.next_power_of_2(min(triton.cdiv(args["q_size"], 8), 16))


def _heur_block_n(args):
    n_rows = args["n_rows"]
    if n_rows >= 65536:
        return triton.next_power_of_2(triton.cdiv(n_rows, 512))
    if n_rows >= 4096:
        return triton.next_power_of_2(triton.cdiv(n_rows, 128))
    if n_rows >= 64:
        return 32
    if n_rows >= 32:
        return 4
    return 1


@libentry()
@triton.heuristics(values={"BLOCK_Q": _heur_block_q, "BLOCK_N": _heur_block_n})
@triton.jit
def _nanquantile_gather_kernel(
    sorted_inp,
    q,
    out,
    n_rows,
    reduction_size,
    q_size,
    BLOCK_Q: tl.constexpr,
    BLOCK_N: tl.constexpr,
    interpolation: tl.constexpr,
):
    q_offsets = ext.program_id(0) * BLOCK_Q + tl.arange(0, BLOCK_Q)
    compute_type = sorted_inp.dtype.element_ty
    row_offsets = ext.program_id(1) * BLOCK_N + tl.arange(0, BLOCK_N)
    valid_q = q_offsets < q_size
    valid_row = row_offsets < n_rows

    # CUDA sort places NaNs after all numeric values. Locate the first NaN in
    # each row without materializing a full-size mask or count tensor.
    low = tl.zeros((BLOCK_N,), dtype=tl.int64)
    high = tl.full((BLOCK_N,), reduction_size, dtype=tl.int64)
    # Searching an inclusive [0, 2**24] interval needs up to 25 steps.
    for _ in tl.static_range(25):
        middle = (low + high) // 2
        probe = tl.load(
            sorted_inp + row_offsets * reduction_size + middle,
            mask=valid_row & (middle < high),
            other=float("nan"),
        )
        probe_valid = probe == probe
        low = tl.where(probe_valid, middle + 1, low)
        high = tl.where(probe_valid, high, middle)
    counts_value = low
    all_nan = counts_value == 0
    last_valid = tl.maximum(counts_value - 1, 0).to(compute_type)
    q_values = tl.load(q + q_offsets, mask=valid_q, other=0.0).to(compute_type)
    ranks = last_valid[:, None] * q_values[None, :]
    lower = tl.floor(ranks).to(tl.int64)
    upper = tl.ceil(ranks).to(tl.int64)
    row_starts = row_offsets[:, None] * reduction_size
    lower_values = tl.load(
        sorted_inp + row_starts + lower,
        mask=valid_row[:, None] & valid_q[None, :],
        other=0.0,
    )
    upper_values = tl.load(
        sorted_inp + row_starts + upper,
        mask=valid_row[:, None] & valid_q[None, :],
        other=0.0,
    )

    if interpolation == 0:
        result = lower_values + (upper_values - lower_values) * (ranks - lower)
    elif interpolation == 1:
        result = lower_values
    elif interpolation == 2:
        result = upper_values
    elif interpolation == 3:
        rounded = tl_extra_shim.rint(ranks).to(tl.int64)
        result = tl.where(rounded == upper, upper_values, lower_values)
    else:
        result = lower_values + (upper_values - lower_values) * 0.5

    result = tl.where(all_nan[:, None], float("nan"), result)
    out_offsets = row_offsets[:, None] * q_size + q_offsets[None, :]
    tl.store(
        out + out_offsets,
        result,
        mask=valid_row[:, None] & valid_q[None, :],
    )


def _validate_args(inp, q, dim, interpolation, out):
    if inp.dtype not in (torch.float32, torch.float64):
        raise RuntimeError(
            "quantile() input tensor must be either float or double dtype"
        )
    if inp.numel() == 0:
        raise RuntimeError("quantile() input tensor must be non-empty")
    if interpolation not in INTERPOLATION_METHODS:
        raise RuntimeError(
            "quantile() interpolation must be one of linear, lower, higher, "
            f"midpoint or nearest, but got {interpolation}"
        )
    if dim is not None and not isinstance(dim, int):
        raise TypeError("quantile() dim must be an integer or None")
    if isinstance(q, torch.Tensor):
        if q.dim() > 1:
            raise RuntimeError("quantile() q must be a scalar or 1D tensor")
        if q.dtype != inp.dtype:
            raise RuntimeError(
                "quantile() q tensor must be same dtype as the input tensor"
            )
        if q.device != inp.device:
            raise RuntimeError(
                "quantile() q tensor must be on the same device as the input"
            )
    if out is not None:
        if out.dtype != inp.dtype:
            raise RuntimeError(
                "quantile() out tensor must be same dtype as the input tensor"
            )
        if out.device != inp.device:
            raise RuntimeError(
                "quantile() out tensor must be on the same device as the input"
            )


def _nanquantile_impl(
    inp, q, dim=None, keepdim=False, interpolation="linear", out=None
) -> Tensor:
    logger.debug("GEMS NANQUANTILE")
    _validate_args(inp, q, dim, interpolation, out)

    original_ndim = inp.ndim
    dim_was_none = dim is None
    if dim_was_none:
        reduced = contiguous(inp).view(-1)
        dim = 0
    else:
        if inp.ndim == 0:
            if dim not in (-1, 0):
                raise IndexError("Dimension out of range")
            dim = 0
            reduced = inp.reshape(1)
        else:
            reduced = torch.movedim(inp, dim, -1)
            dim %= inp.ndim
            reduced = contiguous(reduced)

    q_is_tensor = isinstance(q, torch.Tensor)
    q_is_scalar = not q_is_tensor or q.dim() == 0
    if not q_is_tensor:
        q_value = float(q)
        if not 0.0 <= q_value <= 1.0:
            raise RuntimeError(
                f"quantile() q must be in the range [0, 1] but got {q_value}"
            )
        q = torch.tensor(q_value, dtype=inp.dtype, device=inp.device)
    q_contiguous = contiguous(q).reshape(-1)
    if q_is_tensor and q_contiguous.numel():
        block_size = 256
        with torch_device_fn.device(inp.device):
            _validate_q_kernel[(triton.cdiv(q_contiguous.numel(), block_size),)](
                q_contiguous,
                q_contiguous.numel(),
                BLOCK_SIZE=block_size,
            )

    reduction_size = reduced.size(-1)
    if reduction_size > MAX_REDUCTION_SIZE:
        raise RuntimeError(
            "quantile() input tensor is too large; the reduction dimension "
            f"must not exceed {MAX_REDUCTION_SIZE} elements"
        )
    n_rows = reduced.numel() // reduction_size
    q_size = q_contiguous.numel()
    internal_shape = (*reduced.shape[:-1], q_size)
    if q_is_scalar:
        result_shape = list(reduced.shape[:-1])
        if keepdim:
            if dim_was_none:
                result_shape = [1] * original_ndim
            else:
                result_shape.insert(dim, 1)
    else:
        result_shape = [q_size, *reduced.shape[:-1]]
        if keepdim:
            if dim_was_none:
                result_shape = [q_size, *([1] * original_ndim)]
            else:
                result_shape.insert(dim + 1, 1)
    direct_out = False
    if out is not None and q_is_scalar:
        out.resize_(result_shape)
        out_view = out.reshape(reduced.shape[:-1])
        if out_view.is_contiguous():
            internal = out_view.unsqueeze(-1)
            direct_out = True
        else:
            internal = torch.empty(internal_shape, dtype=inp.dtype, device=inp.device)
    elif out is not None and n_rows == 1:
        out.resize_(result_shape)
        if out.is_contiguous():
            internal = out.reshape(internal_shape)
            direct_out = True
        else:
            internal = torch.empty(internal_shape, dtype=inp.dtype, device=inp.device)
    else:
        internal = torch.empty(internal_shape, dtype=inp.dtype, device=inp.device)

    if q_size:
        if reduction_size:
            with torch_device_fn.device(inp.device):
                if reduction_size <= MAX_BITONIC_SIZE:
                    block_m = triton.next_power_of_2(reduction_size)
                    block_q = min(triton.next_power_of_2(q_size), 16)
                    _nanquantile_bitonic_kernel[(n_rows, triton.cdiv(q_size, block_q))](
                        reduced,
                        q_contiguous,
                        internal,
                        reduction_size,
                        q_size,
                        BLOCK_M=block_m,
                        BLOCK_Q=block_q,
                        interpolation=INTERPOLATION_CODES[interpolation],
                        num_warps=min(16, max(4, block_m // 256)),
                    )
                else:
                    keys = torch.empty_like(reduced)
                    _sort_keys_kernel[(triton.cdiv(reduced.numel(), 1024),)](
                        reduced, keys, reduced.numel(), BLOCK_SIZE=1024
                    )
                    sorted_values, _ = sort_stable(
                        keys, stable=False, dim=-1, descending=False
                    )
                    grid = lambda meta: (
                        triton.cdiv(q_size, meta["BLOCK_Q"]),
                        triton.cdiv(n_rows, meta["BLOCK_N"]),
                    )
                    _nanquantile_gather_kernel[grid](
                        sorted_values,
                        q_contiguous,
                        internal,
                        n_rows,
                        reduction_size,
                        q_size,
                        interpolation=INTERPOLATION_CODES[interpolation],
                    )

    if q_is_scalar:
        result = internal.squeeze(-1)
    else:
        result = internal.movedim(-1, 0)
    if keepdim:
        result = result.reshape(result_shape)

    if out is not None:
        if direct_out:
            return out
        out.resize_(result.shape)
        copy_(out, result)
        return out
    return result


def nanquantile(inp, q, dim=None, keepdim=False, interpolation="linear") -> Tensor:
    return _nanquantile_impl(inp, q, dim, keepdim, interpolation)


def nanquantile_scalar(
    inp, q, dim=None, keepdim=False, interpolation="linear"
) -> Tensor:
    return _nanquantile_impl(inp, q, dim, keepdim, interpolation)


def nanquantile_out(
    inp, q, dim=None, keepdim=False, interpolation="linear", out=None
) -> Tensor:
    return _nanquantile_impl(inp, q, dim, keepdim, interpolation, out)


def nanquantile_scalar_out(
    inp, q, dim=None, keepdim=False, interpolation="linear", out=None
) -> Tensor:
    return _nanquantile_impl(inp, q, dim, keepdim, interpolation, out)
