# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _native_channel_shuffle_kernel(
    x_ptr,
    o_ptr,
    numel,
    C,
    HW,
    cpg,
    groups,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < numel

    # Decode linear output index to (n, c_out, spatial)
    row = offs // HW
    hw = offs - row * HW
    n = row // C
    c_out = row - n * C

    # Channel shuffle: c_out = (c_in % cpg) * groups + (c_in // cpg)
    # Inverse: c_in = (c_out % groups) * cpg + (c_out // groups)
    within = c_out // groups
    group = c_out - within * groups
    c_in = group * cpg + within

    # Compute input linear index
    src = (n * C + c_in) * HW + hw

    val = tl.load(x_ptr + src, mask=mask)
    tl.store(o_ptr + offs, val, mask=mask)


def native_channel_shuffle(input: torch.Tensor, groups: int) -> torch.Tensor:
    logger.debug("GEMS NATIVE_CHANNEL_SHUFFLE")
    x = input
    if not x.is_contiguous():
        x = x.contiguous()

    # native_channel_shuffle expects (N, C, *spatial) where C is divisible by groups
    if x.ndim < 2:
        raise ValueError(
            f"Input must have at least 2 dimensions (N, C, ...), got {x.ndim}"
        )

    C = x.shape[1]
    HW = 1
    for d in x.shape[2:]:
        HW *= d

    g = int(groups)
    assert g > 0, "groups must be > 0"
    assert C % g == 0, f"C ({C}) must be divisible by groups ({g})"

    out = torch.empty_like(x)
    numel = x.numel()
    if numel == 0:
        return out

    cpg = C // g

    # BLOCK size determined by SimpleOpt as optimal for this memory-bound shuffle
    BLOCK = 1024
    grid = lambda META: (triton.cdiv(numel, META["BLOCK"]),)
    with torch_device_fn.device(x.device):
        _native_channel_shuffle_kernel[grid](
            x,
            out,
            numel,
            C,
            HW,
            cpg,
            g,
            BLOCK=BLOCK,
        )
    return out
