# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def sign_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
    IS_BOOL: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)

    if IS_BOOL:
        result = x
    else:
        # For real dtypes: sign(x) = 1 if x>0, -1 if x<0, 0 if x==0
        # NaN: x>0 and x<0 both False -> 0-0=0 (matches torch.sign behavior)
        pos = x > 0
        neg = x < 0
        result = pos.to(x.dtype) - neg.to(x.dtype)

    tl.store(out_ptr + offsets, result, mask=mask)


def _sign_impl(x: torch.Tensor, out: torch.Tensor):
    if x.is_complex():
        raise NotImplementedError(
            "Complex dtypes are not supported. Use torch.sgn for complex numbers."
        )
    if x.device != out.device:
        raise RuntimeError("input and out must be on the same device")
    if x.dtype != out.dtype:
        raise RuntimeError(f"out must have dtype {x.dtype}, but got {out.dtype}")
    if out.shape != x.shape:
        out.resize_(x.shape)

    n_elements = x.numel()
    if n_elements == 0:
        return out

    x_contig = x.contiguous()
    if out.is_contiguous():
        out_contig = out
    else:
        out_contig = torch.empty_like(x, memory_format=torch.contiguous_format)

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    # sign is pure memory traffic. At BLOCK_SIZE=1024 a 16-bit element moves
    # half the bytes per thread of a 32-bit one, so 4 warps leave the loads
    # latency-bound; 2 warps raises the per-thread work and measures ~3-7%
    # faster for fp16/bf16 while fp32 is unchanged (or marginally worse).
    num_warps = 2 if x.dtype in (torch.float16, torch.bfloat16) else 4
    with torch_device_fn.device(x.device):
        sign_kernel[grid](
            x_contig.view(-1),
            out_contig.view(-1),
            n_elements,
            BLOCK_SIZE=1024,
            IS_BOOL=x.dtype == torch.bool,
            num_warps=num_warps,
        )

    if out_contig is not out:
        out.copy_(out_contig)
    return out


def sign(x: torch.Tensor):
    logger.debug("GEMS SIGN")
    out = torch.empty_like(x)
    return _sign_impl(x, out)


def sign_out(x: torch.Tensor, *, out: torch.Tensor):
    logger.debug("GEMS SIGN_OUT")
    return _sign_impl(x, out)


def sign_(x: torch.Tensor):
    logger.debug("GEMS SIGN_")
    return _sign_impl(x, x)
