# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@libentry()
@triton.jit(do_not_specialize=["alpha"])
def _sspaddmm_row_kernel(
    row_start_ptr,  # [R] start offset of each active row in mat1 nnz
    row_end_ptr,  # [R] end offset of each active row in mat1 nnz
    col_ptr,  # [nnz1] column indices of mat1 nonzeros (i.e. k index)
    val_ptr,  # [nnz1] values of mat1 nonzeros
    mat2_ptr,  # [K, N] dense matrix
    out_ptr,  # [R, N] dense result (alpha * mat1 @ mat2 over active rows)
    alpha,
    N,
    stride_mat2_k,
    stride_mat2_n,
    IS_FP64: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    pid_r = ext.program_id(0)
    pid_n = ext.program_id(1)

    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    mask_n = offs_n < N

    row_start = tl.load(row_start_ptr + pid_r).to(tl.int64)
    row_end = tl.load(row_end_ptr + pid_r).to(tl.int64)

    acc_dtype = tl.float64 if IS_FP64 else tl.float32
    acc = tl.zeros((BLOCK_N,), dtype=acc_dtype)

    for e in range(row_start, row_end):
        k = tl.load(col_ptr + e).to(tl.int64)
        v = tl.load(val_ptr + e).to(acc_dtype)
        m2 = tl.load(
            mat2_ptr + k * stride_mat2_k + offs_n * stride_mat2_n,
            mask=mask_n,
            other=0.0,
        ).to(acc_dtype)
        acc += v * m2

    acc = acc * alpha.to(acc_dtype)
    out_base = out_ptr + pid_r.to(tl.int64) * N + offs_n
    tl.store(out_base, acc, mask=mask_n)


def _sspaddmm_impl(input, mat1, mat2, beta=1.0, alpha=1.0, out=None):
    assert input.is_sparse, "sspaddmm: input must be a sparse COO tensor"
    assert mat1.is_sparse, "sspaddmm: mat1 must be a sparse COO tensor"
    assert not mat2.is_sparse, "sspaddmm: mat2 must be a dense tensor"

    input = input.coalesce()
    mat1 = mat1.coalesce()

    n = mat1.shape[0]
    N = mat2.shape[1]
    dtype = input.dtype
    device = input.device

    # Keep the whole reduce/accumulate pipeline in a wider dtype for low
    # precision inputs, casting back to `dtype` only at the very end. This avoids
    # near-cancellation error when beta*input and alpha*mm overlap at an index.
    is_low_prec = dtype in (torch.float16, torch.bfloat16)
    acc_dtype = torch.float32 if is_low_prec else dtype

    mat2_c = mat2.contiguous()

    mat1_indices = mat1.indices()
    mat1_rows = mat1_indices[0]
    mat1_cols = mat1_indices[1].contiguous()
    mat1_vals = mat1.values().contiguous()

    # Group mat1 nonzeros by row. Coalesced COO is sorted row-major, so rows
    # are already in non-decreasing order.
    if mat1_rows.numel() == 0:
        active_rows = mat1_rows.new_empty((0,))
        counts = mat1_rows.new_empty((0,))
    else:
        active_rows, counts = torch.unique_consecutive(mat1_rows, return_counts=True)
    R = active_rows.numel()

    if R > 0:
        row_end = counts.cumsum(0)
        row_start = row_end - counts
        row_start = row_start.to(torch.int64).contiguous()
        row_end = row_end.to(torch.int64).contiguous()

        dense = torch.empty((R, N), dtype=acc_dtype, device=device)

        BLOCK_N = min(triton.next_power_of_2(N), 1024) if N > 0 else 1
        grid = (R, triton.cdiv(N, BLOCK_N) if N > 0 else 1)

        with torch_device_fn.device(device):
            _sspaddmm_row_kernel[grid](
                row_start,
                row_end,
                mat1_cols,
                mat1_vals,
                mat2_c,
                dense,
                alpha,
                N,
                mat2_c.stride(0),
                mat2_c.stride(1),
                IS_FP64=dtype == torch.float64,
                BLOCK_N=BLOCK_N,
            )

        # Build indices for the mm contribution: every (active_row, col) pair.
        row_idx = active_rows.to(torch.int64).repeat_interleave(N)
        col_idx = torch.arange(N, device=device, dtype=torch.int64).repeat(R)
        mm_indices = torch.stack([row_idx, col_idx], dim=0)
        mm_values = dense.reshape(-1)
    else:
        mm_indices = torch.empty((2, 0), dtype=torch.int64, device=device)
        mm_values = torch.empty((0,), dtype=acc_dtype, device=device)

    # beta * input contribution, scaled in the wider accumulation dtype.
    input_indices = input.indices().to(torch.int64)
    input_values = input.values().to(acc_dtype)
    beta_values = input_values * beta if beta != 1.0 else input_values

    out_indices = torch.cat([input_indices, mm_indices], dim=1)
    out_values = torch.cat([beta_values, mm_values], dim=0)

    result = torch.sparse_coo_tensor(
        out_indices, out_values, size=(n, N), dtype=acc_dtype, device=device
    ).coalesce()
    if acc_dtype != dtype:
        result = torch.sparse_coo_tensor(
            result.indices(),
            result.values().to(dtype),
            size=(n, N),
            dtype=dtype,
            device=device,
        ).coalesce()

    if out is not None:
        out.copy_(result)
        return out
    return result


def sspaddmm(input, mat1, mat2, *, beta=1.0, alpha=1.0):
    logger.debug("GEMS SSPADDMM")
    return _sspaddmm_impl(input, mat1, mat2, beta=beta, alpha=alpha)


def sspaddmm_out(input, mat1, mat2, *, beta=1.0, alpha=1.0, out=None):
    logger.debug("GEMS SSPADDMM_OUT")
    if out is None:
        raise TypeError("sspaddmm(): out must be provided for the out variant")
    return _sspaddmm_impl(input, mat1, mat2, beta=beta, alpha=alpha, out=out)
