# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Optional, Tuple

import torch
import triton
import triton.language as tl

from flag_gems.runtime import device, torch_device_fn

logger = logging.getLogger(__name__)


# Gather-based backward kernel for nearest-neighbor 3D upsampling.
# Each thread owns one input voxel and sums the gradients of every output
# voxel that mapped to it in the forward pass. This avoids atomics and the
# float32 scratch buffer, writing the result directly in the output dtype.
#
# The candidate output range per input voxel is derived from the forward
# mapping input = floor(output * reciprocal_scale) clamped to [0, I-1].
# For each candidate output index we re-evaluate that exact mapping and only
# accumulate when it lands on the current input voxel, so the result matches
# the forward rule regardless of floating-point edge cases.
@triton.jit
def _upsample_nearest3d_backward_kernel(
    grad_output_ptr,
    grad_input_ptr,
    OD,
    OH,
    OW,
    ID,
    IH,
    IW,
    reciprocal_scale_d,
    reciprocal_scale_h,
    reciprocal_scale_w,
    MAX_D: tl.constexpr,
    MAX_H: tl.constexpr,
    MAX_W: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    nc_pid = tl.program_id(1)

    # Linear index over the spatial input volume (ID * IH * IW).
    idx = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = idx < (ID * IH * IW)

    iw = idx % IW
    tmp = idx // IW
    ih = tmp % IH
    id_ = tmp // IH

    # Starting candidate output index for each dimension (one before the
    # nominal start to stay robust to rounding).
    od_start = (id_.to(tl.float32) / reciprocal_scale_d).to(tl.int32) - 1
    oh_start = (ih.to(tl.float32) / reciprocal_scale_h).to(tl.int32) - 1
    ow_start = (iw.to(tl.float32) / reciprocal_scale_w).to(tl.int32) - 1
    od_start = tl.maximum(od_start, 0)
    oh_start = tl.maximum(oh_start, 0)
    ow_start = tl.maximum(ow_start, 0)

    acc = tl.zeros((BLOCK_SIZE,), dtype=tl.float32)

    for dd in tl.static_range(MAX_D):
        od = od_start + dd
        src_d = tl.minimum((od * reciprocal_scale_d).to(tl.int32), ID - 1)
        valid_d = (od < OD) & (src_d == id_)
        for hh in tl.static_range(MAX_H):
            oh = oh_start + hh
            src_h = tl.minimum((oh * reciprocal_scale_h).to(tl.int32), IH - 1)
            valid_h = (oh < OH) & (src_h == ih)
            for ww in tl.static_range(MAX_W):
                ow = ow_start + ww
                src_w = tl.minimum((ow * reciprocal_scale_w).to(tl.int32), IW - 1)
                valid_w = (ow < OW) & (src_w == iw)

                valid = mask & valid_d & valid_h & valid_w
                offset_o = ((nc_pid * OD + od) * OH + oh) * OW + ow
                acc += tl.load(grad_output_ptr + offset_o, mask=valid, other=0.0)

    offset_i = ((nc_pid * ID + id_) * IH + ih) * IW + iw
    tl.store(grad_input_ptr + offset_i, acc, mask=mask)


def _upsample_nearest3d_backward_impl(
    grad_output: torch.Tensor,
    output_size: Tuple[int, int, int],
    input_size: Tuple[int, int, int, int, int],
    scales_d: Optional[float] = None,
    scales_h: Optional[float] = None,
    scales_w: Optional[float] = None,
    grad_input: Optional[torch.Tensor] = None,
) -> torch.Tensor:
    assert grad_output.device.type == device.name
    assert grad_output.ndim == 5, "The ndim of grad_output must be 5"
    assert len(output_size) == 3, "The len of output_size must be 3"
    assert len(input_size) == 5, "The len of input_size must be 5"

    OD, OH, OW = output_size
    N, C, ID, IH, IW = input_size

    assert grad_output.shape == (N, C, OD, OH, OW), (
        f"grad_output shape {grad_output.shape} does not match "
        f"expected shape (N={N}, C={C}, OD={OD}, OH={OH}, OW={OW})"
    )

    # Reciprocal scales: prefer explicit scales, otherwise derive from sizes.
    reciprocal_scale_d = 1.0 / scales_d if scales_d is not None else ID / OD
    reciprocal_scale_h = 1.0 / scales_h if scales_h is not None else IH / OH
    reciprocal_scale_w = 1.0 / scales_w if scales_w is not None else IW / OW

    grad_output = grad_output.contiguous()

    if grad_input is None:
        grad_input = torch.empty(
            (N, C, ID, IH, IW), device=grad_output.device, dtype=grad_output.dtype
        )

    # Upper bound on the number of output voxels that map to a single input
    # voxel along each dimension (roughly the up-scaling factor). A small pad
    # keeps the scan robust to floating-point rounding at the boundaries.
    def _window(o, i, recip):
        # Number of output positions per input position is ~ o / i. Add a
        # single pad element to stay robust to floating-point rounding at the
        # candidate-range boundaries.
        if i <= 0:
            return 1
        return max(1, -(-o // i) + 1)  # ceil(o / i) + 1

    MAX_D = _window(OD, ID, reciprocal_scale_d)
    MAX_H = _window(OH, IH, reciprocal_scale_h)
    MAX_W = _window(OW, IW, reciprocal_scale_w)

    # One program handles BLOCK input voxels along the flattened spatial axis.
    # 256 is a good default: a multiple of the warp size that keeps occupancy
    # high while bounding register pressure from the static candidate scan.
    BLOCK = 256
    grid = (triton.cdiv(ID * IH * IW, BLOCK), N * C)

    with torch_device_fn.device(grad_output.device):
        _upsample_nearest3d_backward_kernel[grid](
            grad_output,
            grad_input,
            OD,
            OH,
            OW,
            ID,
            IH,
            IW,
            reciprocal_scale_d,
            reciprocal_scale_h,
            reciprocal_scale_w,
            MAX_D,
            MAX_H,
            MAX_W,
            BLOCK,
        )

    return grad_input


def upsample_nearest3d_backward(
    grad_output: torch.Tensor,
    output_size: Tuple[int, int, int],
    input_size: Tuple[int, int, int, int, int],
    scales_d: Optional[float] = None,
    scales_h: Optional[float] = None,
    scales_w: Optional[float] = None,
) -> torch.Tensor:
    logger.debug("GEMS UPSAMPLE_NEAREST3D_BACKWARD")
    return _upsample_nearest3d_backward_impl(
        grad_output, output_size, input_size, scales_d, scales_h, scales_w
    )


def upsample_nearest3d_backward_grad_input(
    grad_output: torch.Tensor,
    output_size: Tuple[int, int, int],
    input_size: Tuple[int, int, int, int, int],
    scales_d: Optional[float] = None,
    scales_h: Optional[float] = None,
    scales_w: Optional[float] = None,
    grad_input: torch.Tensor = None,
) -> torch.Tensor:
    logger.debug("GEMS UPSAMPLE_NEAREST3D_BACKWARD_GRAD_INPUT")
    return _upsample_nearest3d_backward_impl(
        grad_output,
        output_size,
        input_size,
        scales_d,
        scales_h,
        scales_w,
        grad_input,
    )
